/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class QueryCreater {
    global QueryCreater() {

    }
    global static Map<String,List<String>> getCondition(String strValue, Boolean eventType) {
        return null;
    }
    global static Map<String,List<String>> getWhereClause(String settingName, Boolean eType) {
        return null;
    }
}
