/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GDMServiceMock implements System.WebServiceMock {
    global GDMServiceMock() {

    }
    global void doInvoke(Object stub, Object request_x, Map<String,Object> response, String endpoint, String soapAction, String requestName, String responseNS, String responseName, String responseType) {

    }
}
