/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class checkRecursive {
    global static Boolean accountGlobalMatchRun;
    global static Boolean accountKvkRun;
    global static Boolean accountVATRun;
    global static Boolean creditCheckRun;
    global static Boolean enterpriseRun;
    global static Boolean leadGlobalMatchRun;
    global static Boolean leadKvkRunRun;
    global static Boolean quickCheckRun;
    global static Boolean run;
    global checkRecursive() {

    }
    global static Boolean runOnce() {
        return null;
    }
    global static void runTriggerOnce(String triggerName) {

    }
}
