/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class APIConectorResult {
    @RemoteAction
    global static API_Connector.APIConectorResult getAPIConectorResult() {
        return null;
    }
    global static Map<String,List<String>> getCustomMapsobjectFieldType(String sObjectName) {
        return null;
    }
    global static List<String> getListsObjectFields(String sObjectName) {
        return null;
    }
    global static Map<String,List<String>> getMapsobjectFieldType(String sObjectName) {
        return null;
    }
}
