/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DuplicateCheckHandler {
    global DuplicateCheckHandler() {

    }
    global static void AccountCheck(Set<Id> newleadlstId) {

    }
    global static void AccountKvkCheck(Set<Id> newAccountId) {

    }
    global static void ContactCheck(Set<Id> newleadlstId) {

    }
    global static void LeadkvkCheck(Set<Id> newleadSetId) {

    }
    @AuraEnabled
    webService static void duplicateCheck(Id leadId, String objType) {

    }
    global static String getFieldType(String fieldName, String objectName) {
        return null;
    }
}
