/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class AccountTriggerHandler {
    @AuraEnabled
    webService static void callOutToKvkCheck(Id recordId, String serviceName) {

    }
    @AuraEnabled
    webService static void dnsCreditCheck(Id accId) {

    }
    @AuraEnabled
    webService static void dnsToolkitCheck(Id accId) {

    }
    @Deprecated
    global static String formatDate(Date requestDate) {
        return null;
    }
    @AuraEnabled
    webService static void quickCheckService(Id accId) {

    }
    @Deprecated
    global static void toolkitEnterPriseCallout(Set<Id> setAccId) {

    }
    @Deprecated
    global static void toolkitQuickCheck(Set<Id> setAccId) {

    }
    @Deprecated
    global static void updateDunsNumber(String ServiceType) {

    }
    @Deprecated
    global static void updateDunsNumberCallout(Set<Id> setAccId) {

    }
    @Deprecated
    global static void updateDunsNumberOnUpdate(String ServiceType) {

    }
    webService static String validateVAT(String accountId) {
        return null;
    }
    webService static void validateVatNumberCallOut(List<String> lstVatNumAccId) {

    }
    @Deprecated
    global static void validateVatNumberOnInsert() {

    }
    @Deprecated
    global static void validateVatNumberOnUpdate() {

    }
}
