/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Engine {
    global Engine() {

    }
    @RemoteAction
    global static Object accountKvkIOCallout() {
        return null;
    }
    global static void createDefaultCustomSetting() {

    }
    @RemoteAction
    global static Map<String,List<String>> getFieldType(String fieldName, String objectName) {
        return null;
    }
    global static List<String> getPicklistValues(String ObjectApi_name, String Field_name) {
        return null;
    }
    @RemoteAction
    global static Map<String,String> getlabels() {
        return null;
    }
    @RemoteAction
    global static Map<String,List<System.SelectOption>> leadFields() {
        return null;
    }
    @RemoteAction
    global static Object leadKvkIOCallout() {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> makeGetAccCallout() {
        return null;
    }
    @RemoteAction
    global static Object makeGetConCallout() {
        return null;
    }
    @RemoteAction
    global static Map<String,List<Object>> mappingFields() {
        return null;
    }
    @RemoteAction
    global static Boolean saveAccountKvkDetails(String credentials, String criteriaArray, String filterLogic, String custFilterLogic, String accKvInkmapping, String accRecord, String caseKey) {
        return null;
    }
    @RemoteAction
    global static Boolean saveAccountMapping(String inPutFieldMapRecords, String outPutFieldMapRecords, String caseKeyRecord) {
        return null;
    }
    @RemoteAction
    global static Boolean saveContactMapping(String inPutFieldMapRecords, String outputFieldMapRecords, String caseKeyRecord) {
        return null;
    }
    @RemoteAction
    global static Boolean saveCreditCheck(String username, String password, String DunsField, Boolean IsCheckCredit, String creditRecord, String creditDate, String creditStatus, String credtObj, String creditFilterField, String customLogic) {
        return null;
    }
    @RemoteAction
    global static Boolean saveLeadKvkDetails(String credentials, String criteriaArray, String filterLogic, String custFilterLogic, String leadKvInkmapping, String leadRecord, String caseKey) {
        return null;
    }
    @RemoteAction
    global static Boolean saveToolkitCheck(String toolkitCredential, String toolkitCriteria, String filterLogic, String custFilterLogic, String lstOutPutField, String outPutFieldMapping) {
        return null;
    }
    @RemoteAction
    global static Boolean saveToolkitQuickCheck(String toolkitCredential, String toolkitCriteria, String filterLogic, String custFilterLogic, String lstOutPutField, String outPutFieldMapping) {
        return null;
    }
    @RemoteAction
    global static Boolean saveUserInfo(String userInfo, String arrayAccount, String arrayContact) {
        return null;
    }
    @RemoteAction
    global static Boolean saveVatCheck(String ObjvatInfo, String objVat) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<String>> testMap() {
        return null;
    }
    @RemoteAction
    global static Boolean updateCredentialSetting(String duplicateCredential, String creditCredential, String EntrPrizeCredential) {
        return null;
    }
    @RemoteAction
    global static Boolean updateCredentialSettingV1(String duplicateCredential, String creditCredential, String EntrPrizeCredential, String QckChkCredential) {
        return null;
    }
    @RemoteAction
    global static Boolean updateCredentialSettings(Map<String,String> serviceCredentials) {
        return null;
    }
    global static void updateCustomMetadata(Metadata.CustomMetadata customMetadata) {

    }
    @RemoteAction
    global static Map<String,SObject> userInformation() {
        return null;
    }
}
