/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class TaxParameters {
    global List<Id> listOfSObjectIds;
    global List<SObject> listOfSObjects;
    global TaxParameters() {

    }
    global Boolean getIsCommitOnGetTax() {
        return null;
    }
    global String getLegalEntityReferences() {
        return null;
    }
    global List<SObject> getListOfSObjects() {
        return null;
    }
    global SObject getSObject() {
        return null;
    }
    global Id getSObjectId() {
        return null;
    }
    global List<Id> getSObjectListOfIds() {
        return null;
    }
    global Schema.SObjectType getSObjectType() {
        return null;
    }
    global String getTaxMethod() {
        return null;
    }
    global void setIsCommitOnGetTax(Boolean isCommitOnGetTax) {

    }
    global void setLegalEntityReferences(String legalEntityReference) {

    }
    global void setSObject(SObject sobjectInstance) {

    }
    global void setSObjectId(Id sObjectId) {

    }
    global void setSObjectListOfIds(List<Id> listOfSObjectIds) {

    }
    global void setSObjectType(Schema.SObjectType sObjectTypeInstance) {

    }
    global void setTaxMethod(String taxMethod) {

    }
}
