/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class TaxResults {
    global TaxResults() {

    }
    global String getDetails() {
        return null;
    }
    global String getId() {
        return null;
    }
    global Decimal getRate() {
        return null;
    }
    global String getSummary() {
        return null;
    }
    global Decimal getTax() {
        return null;
    }
    global Boolean isSuccess() {
        return null;
    }
    global void setDetails(String details) {

    }
    global void setId(String id) {

    }
    global void setIsSuccess(Boolean isSuccess) {

    }
    global void setRate(Decimal rate) {

    }
    global void setSummary(String summary) {

    }
    global void setTax(Decimal tax) {

    }
}
