/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RevenueRecognitionResponse {
    @InvocableVariable( required=false)
    global List<List<String>> inputValidationStatus;
    @InvocableVariable( required=true)
    global Id jobId;
    @InvocableVariable( required=false)
    global Integer totalNumberOfInputsWithErrors;
    @InvocableVariable( required=false)
    global Integer totalNumberOfInputsWithoutErrors;
    global RevenueRecognitionResponse() {

    }
}
