/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RefundParameter {
    global RefundParameter() {

    }
    global Decimal getAmount() {
        return null;
    }
    global String getIndex() {
        return null;
    }
    global blng__Payment__c getPayment() {
        return null;
    }
    global blng__Refund__c getRefund() {
        return null;
    }
    global List<blng__RefundLineCreditNoteLine__c> getRefundCreditNoteLines() {
        return null;
    }
    global List<blng__RefundLinePayment__c> getRefundLinePayments() {
        return null;
    }
    global void setAmount(Decimal amount) {

    }
    global void setIndex(String index) {

    }
    global void setPayment(blng__Payment__c payment) {

    }
    global void setRefund(blng__Refund__c refund) {

    }
    global void setRefundCreditNoteLines(List<blng__RefundLineCreditNoteLine__c> listOfRefundCreditNoteLine) {

    }
    global void setRefundLinePayments(List<blng__RefundLinePayment__c> listOfRefundPayment) {

    }
    global void setRefundParameterValues(String index, Decimal amount, blng__Payment__c payment, blng__Refund__c refund, String currencyIsoCode, List<blng__RefundLinePayment__c> listOfRefundPayment, List<blng__RefundLineCreditNoteLine__c> listOfRefundCreditNoteLine) {

    }
}
