/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RevenueRecognition {
    global RevenueRecognition() {

    }
    @InvocableMethod(label='Recognize Revenue' description='Recognize revenue for any object')
    global static List<blng.RevenueRecognitionResponse> recognizeRevenue(List<blng.RevenueRecognitionInput> recognitionInputs) {
        return null;
    }
}
