/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class BatchInvoicePostUsageOperation implements Database.Batchable<SObject>, Database.Stateful, blng.BatchInvoice {
    global String query;
    global BatchInvoicePostUsageOperation() {

    }
    global void execute(Database.BatchableContext BC, List<blng__Usage__c> listOfUsages) {

    }
    global void finish(Database.BatchableContext BC) {

    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return null;
    }
}
