/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class NegativeInvoiceToCreditNoteAction {
    global NegativeInvoiceToCreditNoteAction() {

    }
    @InvocableMethod(label='Convert Negative Invoice to Credit Note' description='Create credit notes and credit note lines for posted invoices with negative invoice lines.')
    global static List<blng.NegativeInvoiceLineConversionResponse> negativeInvoicesToCreditNotes(List<blng.NegativeInvoiceToCreditNoteInput> invoiceToCreditNoteInput) {
        return null;
    }
}
