/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class CaptureInputParameter extends blng.InputParameter {
    global CaptureInputParameter() {

    }
    global Decimal getAmount() {
        return null;
    }
    global blng__PaymentAuthorization__c getPaymentAuthorization() {
        return null;
    }
    global void setAmount(Decimal amount) {

    }
    global void setPaymentAuthorization(blng__PaymentAuthorization__c paymentAuthorization) {

    }
}
