/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class AstreaEventReminderBatch implements Database.Batchable<SObject> {
    global String query;
    global AstreaEventReminderBatch() {

    }
    global void execute(Database.BatchableContext BC, List<SObject> scope) {

    }
    global void finish(Database.BatchableContext sc) {

    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return null;
    }
}
