/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class CommentThreadTab extends dfsle.Tab {
    global dfsle.Tab.Formatting formatting {
        get;
    }
    global String threadId {
        get;
    }
    global CommentThreadTab() {

    }
    global dfsle.CommentThreadTab withFormatting(dfsle.Tab.Formatting formatting) {
        return null;
    }
    global dfsle.CommentThreadTab withThreadId(String threadId) {
        return null;
    }
}
