/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global abstract class ReadOnlyTab extends dfsle.Tab {
    global dfsle.Tab.Formatting formatting {
        get;
    }
    global Object value {
        get;
    }
    global dfsle.ReadOnlyTab withFormatting(dfsle.Tab.Formatting formatting) {
        return null;
    }
    global dfsle.ReadOnlyTab withValue(Object value) {
        return null;
    }
}
