/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class BulkSendService {
    global BulkSendService() {

    }
    global static List<dfsle.BulkList> createLists(List<dfsle.BulkList> bulkLists) {
        return null;
    }
    global static Boolean deleteLists(Set<Id> bulkListIds) {
        return null;
    }
    global static dfsle.Envelope getDraftEnvelope(List<dfsle.Document> documents, dfsle.Entity source) {
        return null;
    }
    global static List<dfsle.BulkList.Status> getStatus(Set<Id> bulkStatusIds) {
        return null;
    }
    global static List<dfsle.BulkList> searchLists(String name, Integer maximumRecords) {
        return null;
    }
    global static dfsle.BulkList.Result sendEnvelope(Id bulkListId, dfsle.Envelope envelope) {
        return null;
    }
    global static List<dfsle.BulkList> updateLists(List<dfsle.BulkList> bulkLists) {
        return null;
    }
}
