/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class NotarizeTab extends dfsle.Tab {
    global Boolean readOnly {
        get;
    }
    global Boolean required {
        get;
    }
    global NotarizeTab() {

    }
    global dfsle.NotarizeTab withReadOnly(Boolean readOnly) {
        return null;
    }
    global dfsle.NotarizeTab withRequired(Boolean required) {
        return null;
    }
}
