/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Notifications {
    global Integer expireAfterDays {
        get;
    }
    global Boolean expires {
        get;
    }
    global Integer expireWarnDays {
        get;
    }
    global Boolean remind {
        get;
    }
    global Integer remindAfterDays {
        get;
    }
    global Integer remindFrequencyDays {
        get;
    }
    global Boolean updateChatter {
        get;
    }
    global Notifications(Boolean remind, Integer remindAfterDays, Integer remindFrequencyDays, Boolean expires, Integer expireAfterDays, Integer expireWarnDays, Boolean updateChatter) {

    }
}
