/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global abstract class SignatureTab extends dfsle.Tab {
    global Boolean required {
        get;
    }
    global Decimal scale {
        get;
    }
    global dfsle.SignatureTab withRequired(Boolean required) {
        return null;
    }
    global dfsle.SignatureTab withScale(Decimal scale) {
        return null;
    }
}
