/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Entity {
    global Id id {
        get;
    }
    global Boolean isValid {
        get;
    }
    global String label {
        get;
    }
    global String name {
        get;
    }
    global dfsle.Entity parent {
        get;
    }
    global String typeName {
        get;
    }
    global Entity(Id id) {

    }
    global Entity(Id id, String name, dfsle.Entity parent) {

    }
    global static dfsle.Entity resolve(Id id) {
        return null;
    }
}
