/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class EnvelopeService {
    global EnvelopeService() {

    }
    @Deprecated
    global static dfsle.Envelope createEnvelope(dfsle.Envelope envelope, dfsle.EnvelopeConfiguration envelopeConfiguration, Boolean addFromSource) {
        return null;
    }
    global static Id deleteEnvelope(Id envelopeId) {
        return null;
    }
    global static dfsle.Envelope getEmptyEnvelope(dfsle.Entity source) {
        return null;
    }
    global static dfsle.Envelope getEnvelope(Id envelopeId) {
        return null;
    }
    global static System.Url getSenderViewUrl(dfsle.UUID docuSignId, System.Url returnUrl) {
        return null;
    }
    global static dfsle.Envelope retryEnvelope(dfsle.UUID transactionId, Boolean sendNow) {
        return null;
    }
    global static List<dfsle.Envelope> saveSentEnvelopes(List<dfsle.Envelope> envelopes) {
        return null;
    }
    global static dfsle.Envelope sendEnvelope(dfsle.Envelope envelope, Boolean sendNow) {
        return null;
    }
    global static List<dfsle.Envelope> sendEnvelopes(List<dfsle.Envelope> envelopes) {
        return null;
    }
    global static dfsle.Envelope updateEnvelope(dfsle.Envelope envelope) {
        return null;
    }
}
