/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DrawTab extends dfsle.Tab {
    global Boolean allowBackgroundImageUpload {
        get;
    }
    global dfsle.Tab.Collaboration collaboration {
        get;
    }
    global Boolean readOnly {
        get;
    }
    global Boolean required {
        get;
    }
    global DrawTab() {

    }
    global dfsle.DrawTab withAllowBackgroundImageUpload(Boolean allowBackgroundImageUpload) {
        return null;
    }
    global dfsle.DrawTab withCollaboration(dfsle.Tab.Collaboration collaboration) {
        return null;
    }
    global dfsle.DrawTab withReadOnly(Boolean readOnly) {
        return null;
    }
    global dfsle.DrawTab withRequired(Boolean required) {
        return null;
    }
}
