/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global virtual class FormulaTab extends dfsle.ReadWriteTab {
    global String formula {
        get;
    }
    global Boolean hidden {
        get;
    }
    global Integer roundDecimalPlaces {
        get;
    }
    global FormulaTab() {

    }
    global dfsle.FormulaTab withFormula(String formula) {
        return null;
    }
    global dfsle.FormulaTab withHidden(Boolean hidden) {
        return null;
    }
    global dfsle.FormulaTab withRoundDecimalPlaces(Integer roundDecimalPlaces) {
        return null;
    }
}
