/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SigningService {
    global SigningService() {

    }
    global static System.Url getEmbeddedSigningUrl(dfsle.UUID envelopeId, System.Url returnUrl) {
        return null;
    }
    global static System.Url getRecipientPreviewUrl(dfsle.UUID envelopeId, Integer recipientSequence) {
        return null;
    }
    global static System.Url getSigningUrl(dfsle.Envelope envelope, System.Url returnUrl, Boolean checkFirstRecipientOnly) {
        return null;
    }
    global static Boolean shouldSignNow(dfsle.Envelope envelope) {
        return null;
    }
}
