/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ESignatureAPIMock extends dfsle.OAuthTokenMock implements System.HttpCalloutMock {
    global ESignatureAPIMock() {

    }
    global ESignatureAPIMock(Boolean success) {

    }
    global static dfsle.ESignatureAPIMock failure() {
        return null;
    }
    global static dfsle.ESignatureAPIMock success() {
        return null;
    }
}
