/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class StatusService {
    global StatusService() {

    }
    global static List<dfsle.Envelope.Status> createStatus(List<dfsle.Envelope.Status> envelopes) {
        return null;
    }
    global static System.Url getCorrectUrl(dfsle.UUID docuSignId, System.Url returnUrl) {
        return null;
    }
    global static List<dfsle.Envelope.Status> getStatus(Set<Id> sourceIds, Integer maximumRecords) {
        return null;
    }
    global static System.Url getViewUrl(dfsle.UUID docuSignId, System.Url returnUrl) {
        return null;
    }
    global static Boolean resendEnvelope(dfsle.UUID docuSignId) {
        return null;
    }
    global static List<dfsle.Recipient.ResendResult> resendRecipients(dfsle.UUID docuSignId, List<dfsle.Recipient> recipients) {
        return null;
    }
    global static Boolean voidEnvelope(dfsle.UUID docuSignId, String reason) {
        return null;
    }
}
