/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class TabGroup extends dfsle.Tab {
    global Integer maximumTabs {
        get;
    }
    global Integer minimumTabs {
        get;
    }
    global String rule {
        get;
    }
    global String scope {
        get;
    }
    global TabGroup() {

    }
    global dfsle.TabGroup withMaximumTabs(Integer maximumTabs) {
        return null;
    }
    global dfsle.TabGroup withMinimumTabs(Integer minimumTabs) {
        return null;
    }
    global dfsle.TabGroup withRule(String rule) {
        return null;
    }
    global dfsle.TabGroup withScope(String scope) {
        return null;
    }
}
