/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global abstract class ReadWriteTab extends dfsle.Tab {
    global dfsle.Tab.Collaboration collaboration {
        get;
    }
    global dfsle.Tab.Formatting formatting {
        get;
    }
    global dfsle.Tab.MergeField mergeField {
        get;
    }
    global Boolean readOnly {
        get;
    }
    global Boolean required {
        get;
    }
    global dfsle.Tab.Validation validation {
        get;
    }
    global Object value {
        get;
    }
    global dfsle.ReadWriteTab withCollaboration(dfsle.Tab.Collaboration collaboration) {
        return null;
    }
    global dfsle.ReadWriteTab withFormatting(dfsle.Tab.Formatting formatting) {
        return null;
    }
    global dfsle.ReadWriteTab withMergeField(dfsle.Tab.MergeField mergeField) {
        return null;
    }
    global dfsle.ReadWriteTab withReadOnly(Boolean readOnly) {
        return null;
    }
    global dfsle.ReadWriteTab withRequired(Boolean required) {
        return null;
    }
    global dfsle.ReadWriteTab withValidation(dfsle.Tab.Validation validation) {
        return null;
    }
    global dfsle.ReadWriteTab withValue(Object value) {
        return null;
    }
}
