/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ViewTab extends dfsle.ButtonTab {
    global Boolean required {
        get;
    }
    global Boolean requiredRead {
        get;
    }
    global ViewTab() {

    }
    global dfsle.ViewTab withRequired(Boolean required) {
        return null;
    }
    global dfsle.ViewTab withRequiredRead(Boolean requiredRead) {
        return null;
    }
}
