/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class APIErrorCode {
    global static Integer ACCOUNT_LACKS_PERMISSIONS;
    global static Integer CONSENT_REQUIRED;
    global static Integer FAILURE;
    global static Integer HOURLY_API_LIMIT_EXCEEDED;
    global static Integer INVALID_DOCUMENT;
    global static Integer INVALID_RECIPIENT;
    global static Integer INVALID_RECIPIENT_SEQUENCE;
    global static Integer INVALID_SIGNING_GROUP;
    global static Integer NOT_FOUND;
    global static Integer SUCCESS;
    global static Integer TRIAL_ACCOUNT_EXPIRED;
    global static Integer UNKNOWN_RECIPIENT;
    global static Integer UNKNOWN_USER;
    global static Integer USER_ALREADY_EXISTS_IN_ACCOUNT;
    global static Integer USER_NOT_ACTIVATED;
    global static Integer USER_PENDING;
    global APIErrorCode() {

    }
}
