/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class PolyLineOverlayTab extends dfsle.Tab {
    global String overlayType {
        get;
    }
    global List<dfsle.PolyLineOverlayTab.PolyLine> polyLines {
        get;
    }
    global PolyLineOverlayTab() {

    }
    global dfsle.PolyLineOverlayTab withOverlayType(String overlayType) {
        return null;
    }
    global dfsle.PolyLineOverlayTab withPolyLines(List<dfsle.PolyLineOverlayTab.PolyLine> polyLines) {
        return null;
    }
global class PolyLine {
    global Integer x1 {
        get;
    }
    global Integer x2 {
        get;
    }
    global Integer y1 {
        get;
    }
    global Integer y2 {
        get;
    }
    global PolyLine(Integer x1, Integer y1, Integer x2, Integer y2) {

    }
}
}
