/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ListTab extends dfsle.ReadWriteTab {
    global List<dfsle.ListTab.Item> items {
        get;
    }
    global ListTab() {

    }
    global dfsle.ListTab withItems(List<dfsle.ListTab.Item> items) {
        return null;
    }
global class Item {
    global String label {
        get;
    }
    global Boolean selected {
        get;
    }
    global Object value {
        get;
    }
    global Item(String label, Object value, Boolean selected) {

    }
}
}
