/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global abstract class SignatureProvider {
    global dfsle.SignatureProvider.Type providerType {
        get;
    }
global enum Type {ElectronicSignature, EUAdvancedAccessCode, EUAdvancedSms, ExpressSignature, IcpBrasil, IDNow, ITAgile, Piv, SignatureAppliance}
}
