/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class CustomField {
    global Boolean isList {
        get;
    }
    global Boolean isText {
        get;
    }
    global List<String> items {
        get;
    }
    global String name {
        get;
    }
    global Boolean required {
        get;
    }
    global Boolean show {
        get;
    }
    global String type {
        get;
    }
    global String value {
        get;
    }
    global CustomField(String type, String name, String value, List<String> items, Boolean required, Boolean show) {

    }
}
