/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DocumentService {
    global DocumentService() {

    }
    global static dfsle.Document.Folders getDocumentFolders(Schema.SObjectType type) {
        return null;
    }
    global static List<dfsle.Document> getDocuments(Schema.SObjectType type, Set<Id> sObjectIds) {
        return null;
    }
    global static List<dfsle.Document> getEnvelopeDocuments(Id envelopeId) {
        return null;
    }
    global static List<dfsle.Document> getFolderDocuments(Schema.SObjectType type, Set<Id> folderIds) {
        return null;
    }
    global static List<dfsle.Document> getLinkedDocuments(Schema.SObjectType type, Set<Id> linkedEntityIds, Boolean getLastUpdatedOnly) {
        return null;
    }
}
