/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RecipientService {
    global RecipientService() {

    }
    global static List<dfsle.Recipient.Role> getDefaultRoles() {
        return null;
    }
    global static List<dfsle.Recipient> getRecipients(Schema.SObjectType type, Set<Id> ids) {
        return null;
    }
    global static List<dfsle.Recipient> searchRecipients(Schema.SObjectType type, String firstName, String lastName) {
        return null;
    }
}
