/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3TelemetryHttpMock implements System.HttpCalloutMock {
    global dc3TelemetryHttpMock() {

    }
    global Boolean gotCalls() {
        return null;
    }
    global System.HttpResponse respond(System.HttpRequest req) {
        return null;
    }
}
