/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3ComponentMergeList {
    global List<String> allRecords {
        get;
        set;
    }
    global Boolean isDev {
        get;
        set;
    }
    global List<String> selectedRecords {
        get;
        set;
    }
    global dc3ComponentMergeList() {

    }
    global String getAssetsUrl() {
        return null;
    }
    global String getAssetsUrlStatic() {
        return null;
    }
    global String getJSONAllRecords() {
        return null;
    }
    global String getJSONSelectedRecords() {
        return null;
    }
    @RemoteAction
    global static Object getMergeData(List<Id> recordList) {
        return null;
    }
}
