/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3ControllerSearch {
    global dc3ControllerSearch() {

    }
    @RemoteAction
    global static dupcheck.dc3HelperGlobal.remoteResult getLayout(String objectPrefix) {
        return null;
    }
    @RemoteAction
    global static dupcheck.dc3HelperGlobal.remoteResult search(String objectPrefix, Map<String,String> inputData) {
        return null;
    }
}
