/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3Constant {
    global dc3Constant() {

    }
global enum Feature {ON_API, ON_BATCH, ON_CHECK, ON_CONVERT, ON_DATAAPI, ON_DIRECT, ON_ENTRY, ON_FLOW, ON_INSERT, ON_LAYOUT, ON_RVINSERT, ON_RVUPDATE, ON_SEARCH, ON_SINGLEUPLOAD, ON_UPDATE, ON_UPLOAD, ON_WEB2LEAD}
}
