/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3SearchBatch implements Database.AllowsCallouts, Database.Batchable<SObject>, Database.Stateful {
    global dc3SearchBatch(Id jid) {

    }
    global dc3SearchBatch(String objectPrefix, Id jid) {

    }
    global dc3SearchBatch(String objectPrefix, Id jid, String f) {

    }
    global dc3SearchBatch(String objectPrefix, String toPrefix, Set<Id> scenarioIds, Id jid) {

    }
    global dc3SearchBatch(String objectPrefix, String toPrefix, Set<Id> scenarioIds, Id jid, String f) {

    }
    global dc3SearchBatch(String objectPrefix, String toPrefix, Set<Id> scenarioIds, Id jid, String f, String fo) {

    }
    global void execute(Database.BatchableContext BC, List<SObject> scope) {

    }
    global void finish(Database.BatchableContext BC) {

    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return null;
    }
}
