/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3HelperGlobal {
    global dc3HelperGlobal() {

    }
    global static Map<String,Map<String,Object>> getDependentOptionsImpl(String objectName, String c, String f) {
        return null;
    }
    global static String getLabelString(String labelName) {
        return null;
    }
    global static Map<String,Object> getRelatedTypeAheadAdvanced(String objectName, String objectQuery, List<String> additionalFields) {
        return null;
    }
    global static List<dupcheck.dc3HelperGlobal.relatedInformation> getRelatedTypeAhead(String objectName, String objectQuery) {
        return null;
    }
    global static void setPreventionStatus(Id recordId, dupcheck.dc3Plugin.PreventionStatus status) {

    }
    global static void setPreventionStatus(Set<Id> recordIdSet, dupcheck.dc3Plugin.PreventionStatus status) {

    }
global class relatedInformation {
    global String id {
        get;
        set;
    }
    global String name {
        get;
        set;
    }
    global relatedInformation() {

    }
}
global class remoteResult {
    global String errorMessage {
        get;
        set;
    }
    global Boolean isError {
        get;
        set;
    }
    global Integer totalItems {
        get;
        set;
    }
    global Integer totalPages {
        get;
        set;
    }
    global Object value {
        get;
        set;
    }
    global remoteResult() {

    }
}
}
