/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3ExtentionEntry {
    global Boolean cloneAction {
        get;
        set;
    }
    global String dataMap {
        get;
        set;
    }
    global String objectPrefix {
        get;
        set;
    }
    global Id recordId {
        get;
        set;
    }
    global Id recType {
        get;
        set;
    }
    global String retUrl {
        get;
        set;
    }
    global Boolean saveAndNew {
        get;
        set;
    }
    global dc3ExtentionEntry(ApexPages.StandardController controller) {

    }
}
