/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3ControllerLayout {
    @Deprecated
    @RemoteAction
    global static dupcheck.dc3ControllerLayout.remoteResult doCheck(Id recordId) {
        return null;
    }
global class remoteResult {
    global remoteResult() {

    }
}
}
