/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/dc3permissioncheck/*')
global class dc3PermissionCheck {
    global dc3PermissionCheck() {

    }
    @HttpPost
    global static void handlePostRequest(Id jobId) {

    }
}
