/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3Exception extends Exception {
global class ApiException extends Exception {
}
global class BatchException extends Exception {
}
global class ConcurrencyException extends Exception {
}
global class ConfigurationException extends Exception {
}
global class ConvertException extends Exception {
}
global class FlowException extends Exception {
}
global class GenericConfigException extends Exception {
}
global class GenericJsonConfigException extends Exception {
}
global class LicenseException extends Exception {
}
global class LimitException extends Exception {
}
global class MergeException extends Exception {
}
global class MergeFieldNullException extends Exception {
}
global class MetadataInconsistencyException extends Exception {
}
global class NoProcessException extends Exception {
}
global class NoScenarioException extends Exception {
}
global class ObjectException extends Exception {
}
global class PluginException extends Exception {
}
global class SearchException extends Exception {
}
global class SecurityException extends Exception {
}
global class ShareException extends Exception {
}
}
