/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3ApiDynamic implements Process.Plugin {
    global dc3ApiDynamic() {

    }
    global Process.PluginDescribeResult describe() {
        return null;
    }
    global Process.PluginResult invoke(Process.PluginRequest request) {
        return null;
    }
}
