/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3ControllerHomeSearch {
    global dc3ControllerHomeSearch() {

    }
    global String getAssetsUrl() {
        return null;
    }
    global String getAssetsUrlStatic() {
        return null;
    }
    @RemoteAction
    global static dupcheck.dc3HelperGlobal.remoteResult getLayout(String objectPrefix) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getRelatedTypeAheadAdvanced(String objectName, String objectQuery, List<String> additionalFields) {
        return null;
    }
    @Deprecated
    @RemoteAction
    global static List<dupcheck.dc3HelperGlobal.relatedInformation> getRelatedTypeAhead(String objectName, String objectQuery) {
        return null;
    }
    @RemoteAction
    global static dupcheck.dc3HelperGlobal.remoteResult search(String objectPrefix, Map<String,String> inputData) {
        return null;
    }
}
