/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class dc3TriggerProcessGlobal {
    global dc3TriggerProcessGlobal(Boolean isbef, Boolean isaft, Boolean isi, Boolean isup, Boolean isd, Boolean isud, String d) {

    }
    global String execute(List<SObject> NewScope, Map<Id,SObject> OldScope) {
        return null;
    }
    global String getEnvironment(SObject objectData, String objectPrefix) {
        return null;
    }
    global static String getEnvironmentOverride() {
        return null;
    }
    global static String getTriggerSource() {
        return null;
    }
    global static void setEnvironmentOverride(String env) {

    }
    global static void setTriggerSource(String source) {

    }
}
