/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/OAASRestHealthCheck/*')
global class OAASRestHealthCheck {
    global OAASRestHealthCheck() {

    }
    @HttpPatch
    global static void UpdateHealthCheck(FSL.OAASRestHealthCheck.InsightsHealthCheckData insightsHealthCheckData) {

    }
global class HealthCheckTestResults {
    global HealthCheckTestResults() {

    }
}
global class InsightsHealthCheckData {
    global InsightsHealthCheckData() {

    }
}
}
