/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SchedulingOption implements System.Comparable {
    global Decimal Grade;
    global List<FSL.GradeSlotResult> Grades;
    global FSL.TimeInterval Interval;
    global FSL.EncapsulatedResource Resource;
    global FSL.TimeInterval ScheduleWindow;
    global Integer TravelAfterScheduale;
    global Integer TravelBeforeSchedule;
    global Integer TravelFromAfterSchedule;
    global Integer TravelToAfterSchedule;
}
