/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class BatchTryRescheduleToOtherResource implements Database.AllowsCallouts, Database.Batchable<SObject>, Database.Stateful {
    global void execute(Database.BatchableContext BC, List<ServiceAppointment> services) {

    }
    global void finish(Database.BatchableContext BC) {

    }
    global List<ServiceAppointment> start(Database.BatchableContext bc) {
        return null;
    }
}
