/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class TimeInterval implements System.Comparable {
    global Datetime Finish {
        get;
        set;
    }
    global Datetime Start {
        get;
        set;
    }
    global TimeInterval(Datetime Start, Datetime Finish) {

    }
    global Integer compareTo(Object compareTo) {
        return null;
    }
    global override String toString() {
        return null;
    }
}
