/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ctrl008_BundlerLightboxExt {
    @RemoteAction
    global static Map<String,Object> detachSAFromBundle(List<Id> serviceAppointmentIdsToDetach) {
        return null;
    }
    @RemoteAction
    global static List<WorkOrder> getWorkOrdersById(Id saId) {
        return null;
    }
    @RemoteAction
    global static List<WorkOrder> getWorkOrders() {
        return null;
    }
    @RemoteAction
    global static List<WorkOrder> getWorkOrders(Id saId) {
        return null;
    }
    global void setBundleChilds() {

    }
    global void setBundleMemberSibling() {

    }
}
