/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GetStatusTransition {
    global GetStatusTransition() {

    }
    global static void addNewStatusTransitionToUT(String fromStatus, String toStatus) {

    }
    global static List<FSL__Service_Legal_Statuses__c> gatAllStatusTransitions() {
        return null;
    }
}
