/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RecurringSequence {
    global List<FSL.GradeSlotResult> averageObjectivesGrades;
    global List<FSL.TimeInterval> firstPatternOccurrence;
    global List<FSL.EncapsulatedResource> participatingResources;
    global Double sequenceScore;
    global List<FSL.SchedulingOption> visitSchedulingOptions;
    global RecurringSequence() {

    }
}
