/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RSORequest {
    global Set<Id> candidateSas {
        get;
        set;
    }
    global String candidateSasField {
        get;
        set;
    }
    global FSL.TimeInterval horizon {
        get;
        set;
    }
    global Boolean includeAllTasks {
        get;
        set;
    }
    global Boolean includeOnlyResourceFutureSA {
        get;
        set;
    }
    global Double latitudeLastKnownLocation {
        get;
        set;
    }
    global Double longitudeLastKnownLocation {
        get;
        set;
    }
    global Decimal maxOptRuntime {
        get;
        set;
    }
    global Datetime nowTimeOnSchedule {
        get;
        set;
    }
    global Id policyId {
        get;
        set;
    }
    global Decimal radius {
        get;
        set;
    }
    global Id resourceId {
        get;
        set;
    }
    global String unschedulableField {
        get;
        set;
    }
    global Set<Id> unschedulableServices {
        get;
        set;
    }
    global RSORequest() {

    }
}
