/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class OAAS {
    global OAAS() {

    }
    global Id Optimize(FSL.OAASRequest Request) {
        return null;
    }
    global Id Reshuffle(Id serviceId, Id policyId) {
        return null;
    }
    global Id ResourceDayOptimization(FSL.RSORequest rsoRequest) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, String candidateSasFields, String unschedulableServicesField, Decimal maxOptRuntime) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, String candidateSasFields, String calloutField, Decimal maxOptRuntime, Datetime nowTimeOnSchedule) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, Set<Id> candidateSas, Set<Id> unschedulableServices, Decimal maxOptRuntime) {
        return null;
    }
    global Id ResourceDayOptimization(Id resourceId, Id policyId, FSL.TimeInterval horizon, Boolean includeAllTasks, Boolean includeOnlyResourceFutureSA, Decimal radius, Set<Id> candidateSas, Set<Id> calloutServices, Decimal maxOptRuntime, Datetime nowTimeOnSchedule) {
        return null;
    }
}
