/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class EmergencyWizardController implements FSL.IChatterAction {
    @RemoteAction
    global static Map<String,List<Object>> getBreadcrumbs2(List<Id> resources) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<SObject>> getBreadcrumbs(List<Id> resources) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getO2Polyline(String inputJSON, String selectedDateTime) {
        return null;
    }
    @RemoteAction
    global static List<FSL__Scheduling_Policy__c> getPolicies() {
        return null;
    }
    @RemoteAction
    global static Boolean saveConsecutiveService(Map<String,Object> data) {
        return null;
    }
}
