/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/AWSRestResource/*')
global class AWSRestResource {
    global AWSRestResource() {

    }
    @HttpPost
    global static FSL.AWSRestResource.WriteCredentialsResult UpdateAuthrizationInfo(FSL.AWSRestResource.AWSAuthorizationInfo credentials) {
        return null;
    }
global class AWSAuthorizationInfo {
    global AWSAuthorizationInfo() {

    }
}
global class WriteCredentialsResult {
    global WriteCredentialsResult() {

    }
}
}
