/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class AppointmentBookingController implements FSL.IChatterAction {
    @RemoteAction
    global static AsyncApexJob getAsyncApexJob(Id jobId) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getFslOperation(Long schedulingStartLong, Id opId) {
        return null;
    }
    @RemoteAction
    global static List<FSL__Scheduling_Policy__c> getPolicies() {
        return null;
    }
    @RemoteAction
    global static String getUserLocale() {
        return null;
    }
}
