/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ScheduleResult {
    global ResourceAbsence BreakObject {
        get;
        set;
    }
    global Decimal Grade {
        get;
        set;
    }
    global Id LongOperationId {
        get;
        set;
    }
    global List<FSL.PartialResultsInfo> PartialResults {
        get;
        set;
    }
    global ServiceResource Resource {
        get;
        set;
    }
    global ServiceAppointment Service {
        get;
        set;
    }
    global ScheduleResult() {

    }
}
