/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class OAASRequest {
    global Boolean AllTasksMode {
        get;
        set;
    }
    global Boolean ClearGantt {
        get;
        set;
    }
    global String FilterFieldAPIName {
        get;
        set;
    }
    global Datetime Finish {
        get;
        set;
    }
    global Boolean IncludeServicesWithEmptyLocation {
        get;
        set;
    }
    global String InJeopardyReason {
        get;
        set;
    }
    global String KeepApptScheduledField {
        get;
        set;
    }
    global Boolean KeepSameOrder {
        get;
        set;
    }
    global List<Id> Locations {
        get;
        set;
    }
    global Integer NumberOfServicesToSchedule {
        get;
        set;
    }
    global Id SchedulingPolicyID {
        get;
        set;
    }
    global Datetime Start {
        get;
        set;
    }
    global String StatusToUpdate {
        get;
        set;
    }
    global Id TriggeringRecipeId {
        get;
        set;
    }
    global OAASRequest() {

    }
}
