/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class BatchUpdateExistingPolygons implements Database.Batchable<SObject> {
    global BatchUpdateExistingPolygons() {

    }
    global void execute(Database.BatchableContext info, List<FSL__Polygon__c> needToBeUpdatedPolygons) {

    }
    global void finish(Database.BatchableContext info) {

    }
    global List<FSL__Polygon__c> start(Database.BatchableContext info) {
        return null;
    }
}
