/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ctrl079_ResourceCalendar {
    @RemoteAction
    global static List<FSL__Dictionaries__c> getDictionaries() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getNAFieldset() {
        return null;
    }
    @RemoteAction
    global static List<ResourceAbsence> getNAs(String strStartDate, String strFinishDate, Id resourceId) {
        return null;
    }
    @RemoteAction
    global static List<RecordType> getNaRecordTypes() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getNaTooltipFieldset() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getServiceFieldset() {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getServiceTooltipFieldset() {
        return null;
    }
    @RemoteAction
    global static List<ServiceAppointment> getServices(String strStartDate, String strFinishDate, Id resourceId) {
        return null;
    }
    @RemoteAction
    global static List<String> getStatuses() {
        return null;
    }
    @RemoteAction
    global static Map<String,String> getTranslations(String objectName, String fieldName) {
        return null;
    }
    @RemoteAction
    global static Map<String,Double> getduartionPerDay(String strStartDate, String strFinishDate, Id resourceId) {
        return null;
    }
}
