/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class StatusTransition {
    global String AllowedProfiles {
        get;
        set;
    }
    global String FromStatus {
        get;
        set;
    }
    global String ToStatus {
        get;
        set;
    }
    global StatusTransition(String FromStatus, String ToStatus) {

    }
    global StatusTransition(String FromStatus, String ToStatus, String AllowedProfiles) {

    }
}
