/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Ctrl001GroupOnRuleAndObjectives {
    global static String ObjectId {
        get;
        set;
    }
    global static String ObjectName {
        get;
        set;
    }
    global static String strCurrentObject {
        get;
        set;
    }
    @RemoteAction
    global static List<FSL.Ctrl001GroupOnRuleAndObjectives.FieldsLabelName> GetObjectFields(String ObjName) {
        return null;
    }
    @RemoteAction
    global static void SaveFieldsNamesOnWorkRule(Id objid, String ObjName, String ObjectFieldName, String ResourceFieldName) {

    }
global class FieldsLabelName {
}
}
