/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class FieldsSetUtils {
    global FieldsSetUtils() {

    }
    global static List<FSL.FieldsSetUtils.FieldSetField> getFieldSetWithRef(List<Schema.FieldSetMember> FieldSet, Boolean IsClientRequest) {
        return null;
    }
    global static List<FSL.FieldsSetUtils.FieldSetField> getFieldSet(List<Schema.FieldSetMember> FieldSet) {
        return null;
    }
    global static List<FSL.FieldsSetUtils.FieldSetField> getFieldSet(List<Schema.FieldSetMember> FieldSet, Boolean IsClientRequest) {
        return null;
    }
global class FieldSetField {
    global FieldSetField() {

    }
}
}
