/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ScheduleJobsApi {
    global static FSL.ScheduleJobsApi getJob(Id jobId) {
        return null;
    }
    global static FSL.ScheduleJobsApi getJob(String jobId) {
        return null;
    }
    global void setTerritory(List<FSL.ScheduleJobsApi.GroupData> groupList) {

    }
global class GeneralData {
    global GeneralData(String timePeriod, String generalPolicyId, String filterCriteria, String userMail) {

    }
}
global class GroupData {
    global GroupData(String groupPolicyId, List<String> territoryIds) {

    }
}
}
