/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GradeSlotsService {
    global Boolean ForceSharing {
        get;
        set;
    }
    global GradeSlotsService(Id policy, Id serviceID) {

    }
    global FSL.AdvancedGapMatrix GetGradedMatrix(Boolean i_ResultsInUserTimeZone) {
        return null;
    }
    global FSL.AdvancedGapMatrix GetGradedMatrix(Boolean i_ResultsInUserTimeZone, String isGantt) {
        return null;
    }
}
