/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/O2FetchFiles/*')
global class O2FetchFiles {
    global O2FetchFiles() {

    }
    @HttpPost
    global static Boolean IsCustomerFacingESORequestFilesAccessible(FSL.O2FetchFiles.O2FetchFilesParams params) {
        return null;
    }
    @HttpPatch
    global static Boolean IsESORequestFilesAccessible(FSL.O2FetchFiles.O2FetchFilesParams params) {
        return null;
    }
global class O2FetchFilesParams {
    global O2FetchFilesParams() {

    }
}
}
