/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ScheduleServiceProcess {
    global static Boolean ForceSharing {
        get;
        set;
    }
    global ScheduleServiceProcess() {

    }
    @InvocableMethod(label='ScheduleServiceAppointments' description='Schedule Service Appointment Process')
    global static void ScheduleServiceAppointments(List<FSL.ScheduleServiceProcess.ServiceAppointmentWrapper> servicesWrapper) {

    }
global class ServiceAppointmentWrapper {
    global ServiceAppointmentWrapper() {

    }
}
}
