/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Ctrl739_ComplexWork {
    @RemoteAction
    global static Map<String,List<Object>> addTimeDependency(Id serviceAppId, Id sa1, Id sa2, String dependency, Boolean sameResource) {
        return null;
    }
    @RemoteAction
    global static AsyncApexJob getAsyncApexJob(Id jobId) {
        return null;
    }
    @RemoteAction
    global static List<Object> getComplexWorkLookupFields(Id serviceId) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getFslOperation(Long schedulingStartLong, Id opId) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<Object>> getMstChain(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static Integer getRelatedChainLength(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static List<ServiceAppointment> getRelatedServicesByLookupFieldId(Id serviceId, String lookupField, Id lastId) {
        return null;
    }
    @RemoteAction
    global static List<ServiceAppointment> getRelatedServicesByLookupField(Id serviceId, String lookupField) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<ServiceAppointment>> getRelatedServices(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static List<FSL.FieldsSetUtils.FieldSetField> getServiceListFields() {
        return null;
    }
    @RemoteAction
    global static List<FSL.TimeDependencyUtils.SAWithLevel> getTree(Id serviceAppId) {
        return null;
    }
    @RemoteAction
    global static Map<String,List<Object>> removeTimeDependency(Id serviceAppId, Id timeDep) {
        return null;
    }
    @RemoteAction
    global static List<FSL.ScheduleResult> scheduleService2(Id service) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> scheduleService(Id service) {
        return null;
    }
}
