/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GroupNearbyService {
    global GroupNearbyService() {

    }
    global static FSL__Optimization_Request__c CallGroupNearbyService(Id serviceId, Id policyId) {
        return null;
    }
    global static void CallGroupNearbyServiceBatch(Id serviceId, Id policyId) {

    }
}
