/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ScheduleService {
    global static Boolean ForceSharing {
        get;
        set;
    }
    global ScheduleService() {

    }
    global static FSL.ScheduleResult Schedule(Id policy, Id serviceID) {
        return null;
    }
    global static List<FSL.ScheduleResult> ScheduleExtended(Id Policy, Id ServiceID) {
        return null;
    }
    global static FSL.AppointmentInsightsResult getAppointmentInsights(Id policyId, Id serviceAppointmentId) {
        return null;
    }
    global static List<FSL.ScheduleResult> scheduleHere(Datetime startDate, Id usedPolicyId, Id serviceAppointmentId, Id newResourceId) {
        return null;
    }
}
