/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DispatcherCopilot {
    global DispatcherCopilot() {

    }
    global static Boolean ShowServicesInList(List<Id> serviceIds, String infoBubble) {
        return null;
    }
    global static Map<String,Object> runScheduleSummary(List<String> territories) {
        return null;
    }
}
