/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GlobalAPIS {
    global GlobalAPIS() {

    }
    global static void ClearAllStatusTransitions() {

    }
    global static List<FSL.StatusTransition> GetAllStatusTransitions() {
        return null;
    }
    global static List<FSL__Service_Legal_Statuses__c> GetStatusTransitions() {
        return null;
    }
    global static void addStatusTransition(FSL.StatusTransition statusTransition) {

    }
    global static void addStatusTransition(String fromStatus, String toStatus) {

    }
    global static void addStatusTransition(String fromStatus, String toStatus, Set<String> allowedProfilesId) {

    }
}
