/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GradeSlotResult {
    global Decimal Grade {
        get;
        set;
    }
    global String HeaderText {
        get;
        set;
    }
    global Integer NumberOfAppointmentsWithGrade100 {
        get;
        set;
    }
    global Id ObjectiveId {
        get;
        set;
    }
    global String ObjectiveRecordTypeName {
        get;
        set;
    }
    global Integer RankInAppointments {
        get;
        set;
    }
    global String Text {
        get;
        set;
    }
}
