/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class PolygonUtils {
    global PolygonUtils() {

    }
    global static List<FSL__Polygon__c> getAllPolygonsByLatLong(Double longitude, Double latitude) {
        return null;
    }
    global static Id getTerritoryIdByPolygons(Double longitude, Double latitude) {
        return null;
    }
}
