/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SettingsAPI {
    global SettingsAPI() {

    }
    global static Map<String,String> getCustomSettings() {
        return null;
    }
    global static Id setAutomator(String automatorName, Set<Id> TerritoriesIDs, Boolean runNow) {
        return null;
    }
    global static String setCustomSettings(String settingsObjectName, String settingName, Object value) {
        return null;
    }
    global static String setCustomSettings(String settingsObjectName, String settingName, Object value, Boolean ThrowExceptionsOrNot) {
        return null;
    }
    global static String setCustomSettings(String settingsObjectName, String instanceName, String settingName, Object value) {
        return null;
    }
    global static String setCustomSettings(String settingsObjectName, String instanceName, String settingName, Object value, Boolean ThrowExceptionsOrNot) {
        return null;
    }
    global static Map<String,String> setCustomSettings(String settingsObjectName, Map<String,Object> settingNameToValue) {
        return null;
    }
    global static Map<String,String> setCustomSettings(String settingsObjectName, Map<String,Object> settingNameToValue, Boolean ThrowExceptionsOrNot) {
        return null;
    }
    global static Map<String,String> setCustomSettings(String settingsObjectName, String instanceName, Map<String,Object> settingNameToValue) {
        return null;
    }
    global static Map<String,String> setCustomSettings(String settingsObjectName, String instanceName, Map<String,Object> settingNameToValue, Boolean ThrowExceptionsOrNot) {
        return null;
    }
}
