/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ctrl112_ResourcePriorityFieldChooser {
    @RemoteAction
    global static void SaveFieldNameOnServiceGoal(Id objID, String ObjName, String CustomPriorityFieldName) {

    }
    @RemoteAction
    global static Map<String,String> getObjectNumericFields(String ObjName) {
        return null;
    }
}
