/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Ctrl078_CapacityCalendar {
    @RemoteAction
    global static List<ServiceResourceCapacity> deleteCapacities(List<Id> capacitiesIds) {
        return null;
    }
    @RemoteAction
    global static List<ServiceResourceCapacity> getMonthlyCapacities(String startDateString, String endDateString, Id resourceId) {
        return null;
    }
    @RemoteAction
    global static List<ServiceResourceCapacity> saveChangesToCapacity(Id capacityId, Id resourceId, String periodStart, Integer hoursCapacity, Integer servicesCapacity, String durationType, Integer daysDiff) {
        return null;
    }
    @RemoteAction
    global static List<ServiceResourceCapacity> updateMultipleCapacities(List<Id> capacitiesIds, Integer hoursCap, Integer servicesCap) {
        return null;
    }
}
