/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class GanttPalette {
    @RemoteAction
    global static void deleteGanttPalette(String paletteId) {

    }
    @RemoteAction
    global static Map<Id,FSL__GanttPalette__c> getExistingGanttPalettes() {
        return null;
    }
    @RemoteAction
    global static Map<String,String> getServiceAppointmentFieldsMap() {
        return null;
    }
    @RemoteAction
    global static String saveGanttPalette(String paletteId, String name, String description, String serviceProperty, String colorScheme, Integer colorLevel, Boolean active) {
        return null;
    }
}
