/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/territory/query')
global class TerritoryQueryProcessor {
    global TerritoryQueryProcessor() {

    }
    @HttpPost
    global static maps.TerritoryQueryProcessor.MARestResponse post(maps.TerritoryQueryProcessor.MARestRequest request) {
        return null;
    }
global class MARestRequest {
    global MARestRequest() {

    }
}
global class MARestResponse {
    global MARestResponse() {

    }
}
}
