/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DescribeHelper {
    global DescribeHelper() {

    }
    global static Boolean checkMCEnabled() {
        return null;
    }
    global static Map<String,Schema.DescribeFieldResult> getAllFieldsDescribe(String objectName) {
        return null;
    }
    global static Schema.DescribeFieldResult getFieldDescribe(String objectName, Schema.SObjectField sObjFieldType) {
        return null;
    }
    global static Schema.DescribeFieldResult getFieldDescribe(String objectName, String fieldName) {
        return null;
    }
    global static String getFieldLabel(String objectName, String fieldName) {
        return null;
    }
    global static String getFieldType(String objectName, String fieldName) {
        return null;
    }
    global static Schema.DescribeSObjectResult getObjectDescribe(Schema.SObjectType objectType) {
        return null;
    }
    global static Schema.DescribeSObjectResult getObjectDescribe(String objectName) {
        return null;
    }
    global static String getObjectLabel(String objectName) {
        return null;
    }
    global static SObject getPrototypeObject(String objectName) {
        return null;
    }
    global Map<String,Schema.DescribeFieldResult> getThisAllFieldsDescribe(String objectName) {
        return null;
    }
    global Schema.DescribeFieldResult getThisFieldDescribe(String objectName, String fieldName) {
        return null;
    }
    global String getThisFieldLabel(String objectName, String fieldName) {
        return null;
    }
    global String getThisFieldType(String objectName, String fieldName) {
        return null;
    }
    global Schema.DescribeSObjectResult getThisObjectDescribe(String objectName) {
        return null;
    }
    global String getThisObjectLabel(String objectName) {
        return null;
    }
    global SObject getThisPrototypeObject(String objectName) {
        return null;
    }
    global static Boolean isObjectIdThisType(Id salesforceId, String objectName) {
        return null;
    }
    global Boolean isThisObjectIdThisType(Id salesforceId, String objectName) {
        return null;
    }
}
