/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class PS_RH_Client_Access {
    global PS_RH_Client_Access() {

    }
    global static void runManuallyForAllRecords(String rollupLabel) {

    }
    global static void runManuallyForAllRecords(String rollupLabel, String parentFilterName, String notificationEmail) {

    }
    global static void setOrgDisableRealTime(Boolean realTime) {

    }
    global static void toggleAsynchronousForObject(String objName, Boolean async) {

    }
    global static void toggleRealTime(Boolean current) {

    }
}
