/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class PS_Rollup_Context {
    global PS_Rollup_Context() {

    }
    global PS_Rollup_Context(Map<String,Object> params) {

    }
    global Boolean addCriteria(String field, String logic, String condition) {
        return null;
    }
    global void addRollup(String targetField, String rollupType, String sourceField) {

    }
    global void addRollup(String targetField, String rollupType, String delim, String sourceField) {

    }
    global Boolean addSort(String field, String logic) {
        return null;
    }
    global List<rh2__PS_Queue__c> enqueue(Integer recordScope) {
        return null;
    }
    global String getRelationshipField() {
        return null;
    }
    global String getRollupName(String targetField) {
        return null;
    }
    global void run(Integer recordScope) {

    }
    global void run(Integer recordScope, String notificationEmail) {

    }
    global void save() {

    }
    global void setFilterBoolLogic(String newBoolLogic) {

    }
    global void setFilterName(String name) {

    }
    global void setLimit(String lVar) {

    }
}
