/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class PS_Batch_Job extends rh2.PS_Batchable_Class implements Database.Batchable<SObject>, Database.Stateful {
    global PS_Batch_Job() {

    }
    global PS_Batch_Job(rh2__PS_Queue__c q) {

    }
    global override void execute(Database.BatchableContext BC, List<SObject> recs) {

    }
    global override void finish(Database.BatchableContext BC) {

    }
    global override Database.QueryLocator start(Database.BatchableContext BC) {
        return null;
    }
}
