/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ContractAPI {
    global ContractAPI() {

    }
    global static List<SObject> loadContracts(Set<Id> contractIds) {
        return null;
    }
    global static void processSubscriptionTriggerAfterUpdate(SObject recordObject) {

    }
    global static void processTriggerAfter() {

    }
    global static void renewContracts(List<SObject> contracts, Id masterContractId) {

    }
}
