/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ProductLookupController {
    global ProductLookupController() {

    }
    global static void follow(String recordId) {

    }
    @RemoteAction
    global static String loadSearchModel(String quoteJSON, String processId, String customActionId) {
        return null;
    }
    global static String loadSearchModelPaginated(String quoteJSON, String processId, String customActionId, Integer pageNumber) {
        return null;
    }
    @RemoteAction
    global static String removeFavorites(String quoteJSON, List<Id> favoriteIds) {
        return null;
    }
    @RemoteAction
    global static String search(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit) {
        return null;
    }
    global static String search(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit, String searchString) {
        return null;
    }
    global static String searchPaginated(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit, Integer pageNumber) {
        return null;
    }
    global static String searchPaginated(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit, Integer pageNumber, String searchString) {
        return null;
    }
    @RemoteAction
    global static String suggest(String quoteJSON, String processJSON, Integer resultLimit) {
        return null;
    }
    global static String suggestPaginated(String quoteJSON, String processJSON, Integer resultLimit, Integer pageNumber) {
        return null;
    }
    global static void unfollow(String recordId) {

    }
}
