/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class AmendContractController {
    global Map<Id,SBQQ.AmendContractController.AggregatedSub> aggregatedSubs {
        get;
    }
    global String contractNumber {
        get;
    }
    global String displayedSubscriptionsMsg {
        get;
    }
    global Id jobId {
        get;
    }
    global AmendContractController(ApexPages.StandardController stdController) {

    }
    global System.PageReference onAmend() {
        return null;
    }
    global System.PageReference returnToContract() {
        return null;
    }
}
