/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/v1/quotes/*')
global class QuoteRestEndpoint {
    global QuoteRestEndpoint() {

    }
    @HttpGet
    global static void doGet() {

    }
    @HttpPost
    global static void doPost() {

    }
    global static void doPostV1(System.RestRequest req) {

    }
    @HttpPut
    global static void doPut() {

    }
    global static void doPutV1(System.RestRequest req) {

    }
}
