/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global interface QuoteCalculatorPlugin {
    void onAfterCalculate(SObject param0, List<SObject> param1);
    void onAfterPriceRules(SObject param0, List<SObject> param1);
    void onBeforeCalculate(SObject param0, List<SObject> param1);
    void onBeforePriceRules(SObject param0, List<SObject> param1);
    void onInit(List<SObject> param0);
}
