/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global interface PageSecurityPlugin2 extends SBQQ.PageSecurityPlugin {
    Boolean isFieldEditable(String param0, Schema.SObjectField param1, SObject param2);
    Boolean isFieldVisible(String param0, Schema.SObjectField param1, SObject param2);
}
