/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class AssetLookupController {
    global static String amendAssets(List<Id> selectedAssetIds, Id accountId, Boolean isAssetBased) {
        return null;
    }
    @RemoteAction
    global static String amendAssets(List<Id> selectedAssetIds, Id accountOrOppId, Boolean isAssetBased, Id pricebookId) {
        return null;
    }
    @RemoteAction
    global static String loadPricebooks() {
        return null;
    }
    @RemoteAction
    global static String loadSearchModel(String quoteJSON, String customActionId) {
        return null;
    }
    @RemoteAction
    global static String onloadSearchModel(String accountId, Boolean isAmend) {
        return null;
    }
    @RemoteAction
    global static String renewAssetsByMasterId(List<Id> selectedAssetIds, Id accountId, Boolean isAssetBased, Id masterAssetId) {
        return null;
    }
    @RemoteAction
    global static String renewAssets(List<Id> selectedAssetIds, Id accountId, Boolean isAssetBased) {
        return null;
    }
    @RemoteAction
    global static String search(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit) {
        return null;
    }
    @RemoteAction
    global static String searchByAssetBased(String accountId, Boolean isAmend, String filterValuesJSON) {
        return null;
    }
}
