/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SubscriptionLookupController {
    global SubscriptionLookupController() {

    }
    @RemoteAction
    global static String loadSearchModel(String quoteJSON, String customActionId) {
        return null;
    }
    @RemoteAction
    global static String search(String quoteJSON, String filterValuesJSON, String customActionId, Integer resultLimit) {
        return null;
    }
}
