/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/ServiceRouter/*')
global class ServiceRouter {
    @HttpPatch
    global static String load(String context) {
        return null;
    }
    global static String load(String loader, String uid, String context) {
        return null;
    }
    @RemoteAction
    global static String load(String loader, String uid, String context, Boolean includeSPT) {
        return null;
    }
    @HttpGet
    global static String read() {
        return null;
    }
    global static String read(String reader, String uid) {
        return null;
    }
    @RemoteAction
    global static String read(String reader, String uid, Boolean includeSPT) {
        return null;
    }
    @HttpPost
    global static String save(String saver, String model) {
        return null;
    }
    @RemoteAction
    global static String save(String saver, String model, Boolean includeSPT) {
        return null;
    }
}
