/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RenewContractsController {
    global Boolean isEvergreen {
        get;
        set;
    }
    global Id jobId {
        get;
    }
    global String masterContractId {
        get;
        set;
    }
    global List<SObject> selectedServiceContracts {
        get;
    }
    global RenewContractsController(ApexPages.StandardSetController setController) {

    }
    global void displayCheckerErrorMessage() {

    }
    global void displayIndividualFailureMessages() {

    }
    global String getRenewedContractIdsJson() {
        return null;
    }
    global System.PageReference onCancel() {
        return null;
    }
    global System.PageReference onInit() {
        return null;
    }
    global System.PageReference onRenew() {
        return null;
    }
}
