/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class QueueableJobCheckerExt {
    global QueueableJobCheckerExt(ApexPages.StandardController controller) {

    }
    global QueueableJobCheckerExt(ApexPages.StandardSetController controller) {

    }
    global static AsyncApexJob checkJobStatus(String recordId, String jobId) {
        return null;
    }
    global static String checkJobStatus(String jobId) {
        return null;
    }
    global Boolean getAutoRefresh() {
        return null;
    }
    global String getClassPrefix() {
        return null;
    }
    global String getJobDetails() {
        return null;
    }
    global String getJobStatus() {
        return null;
    }
    global String getJobStatus(String jobId) {
        return null;
    }
    global static Map<String,Object> getJobStatus(String recordId, String jobId) {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getJobStatus(String recordId, String jobType, String jobId) {
        return null;
    }
    global String getJobType() {
        return null;
    }
    @RemoteAction
    global static Map<String,Object> getJobsStatuses(List<String> recordIds, String jobType, String asyncJobId) {
        return null;
    }
    global String getQueueableJobId() {
        return null;
    }
    @RemoteAction
    global static Boolean getUncalculatedWithSetting(Id quoteId) {
        return null;
    }
}
