/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class QuotePriceRefreshBatch implements Database.AllowsCallouts, Database.Batchable<SObject>, Database.Stateful {
    global QuotePriceRefreshBatch(Schema.SObjectType quoteType, Set<Id> quoteIds) {

    }
    global void execute(Database.BatchableContext ctx, List<SObject> scope) {

    }
    global void finish(Database.BatchableContext ctx) {

    }
    global Database.QueryLocator start(Database.BatchableContext ctx) {
        return null;
    }
}
