/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class FavoritesManagerController {
    global FavoritesManagerController() {

    }
    @RemoteAction
    global static String loadFavoriteModel(String quoteJSON) {
        return null;
    }
    @RemoteAction
    global static String loadUsersToShare(String searchCriteria) {
        return null;
    }
    @RemoteAction
    global static String removeFromFavorites(String quoteJSON, List<Id> favoriteIds) {
        return null;
    }
    @RemoteAction
    global static String shareFavoritesWithUsersAndGroups(String quoteJSON, List<Id> favoriteIds, List<Id> groupIds, List<Id> userIds) {
        return null;
    }
}
