/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global interface RuleActionListener extends SBQQ.RuleListener {
    void onAfterRuleActionExecuted(SObject param0, SObject param1, Schema.SObjectField param2);
    void onBeforeRuleActionExecuted(SObject param0, SObject param1, Schema.SObjectField param2);
}
