/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class InstallProcessor implements SBQQ.InstallExecutor, System.InstallHandler {
    global static void emailOnAbort(String msg) {

    }
    global static void emailOnFail(String msg, Boolean isInstall) {

    }
    global static void emailOnFailedJob(String jobName, AsyncApexJob apexJob, Map<Id,List<String>> errorMap, Boolean isInstall) {

    }
    global static List<Id> execute() {
        return null;
    }
}
