/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@RestResource(urlMapping='/LookupCallout/*')
global class LookupTableCallout implements SBQQ.ServiceLoader {
    global LookupTableCallout() {

    }
    @HttpGet
    global static String callGet() {
        return null;
    }
    @HttpPost
    global static Map<String,List<SObject>> queryRows() {
        return null;
    }
global class TableMap {
}
}
