/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global virtual class DefaultPageSecurityPlugin implements SBQQ.PageSecurityPlugin, SBQQ.PageSecurityPlugin2 {
    global DefaultPageSecurityPlugin() {

    }
    global virtual Boolean isFieldEditable(String pageName, Schema.SObjectField field) {
        return null;
    }
    global virtual Boolean isFieldEditable(String pageName, Schema.SObjectField field, SObject recordz) {
        return null;
    }
    global virtual Boolean isFieldVisible(String pageName, Schema.SObjectField field) {
        return null;
    }
    global virtual Boolean isFieldVisible(String pageName, Schema.SObjectField field, SObject record) {
        return null;
    }
}
