/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global virtual class DefaultElectronicSignaturePlugin implements SBQQ.ElectronicSignaturePlugin, SBQQ.ElectronicSignaturePlugin2, SBQQ.ElectronicSignaturePlugin3 {
    global DefaultElectronicSignaturePlugin() {

    }
    global virtual String getSendButtonLabel() {
        return null;
    }
    global virtual Boolean isSendButtonEnabled() {
        return null;
    }
    global virtual void revoke(List<SBQQ__QuoteDocument__c> documents) {

    }
    global virtual String sendWithRedirect(List<SBQQ__QuoteDocument__c> documents) {
        return null;
    }
    global virtual void send(List<SBQQ__QuoteDocument__c> documents) {

    }
    global virtual void updateStatus(List<SBQQ__QuoteDocument__c> documents) {

    }
}
