/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class RenewalAPI {
    global RenewalAPI() {

    }
    global static void forecastContracts(List<SObject> contracts, Id masterContractId) {

    }
    global static Boolean hasPassedEvergreenValidationChecks(SObject oldContract, SObject newContract) {
        return null;
    }
    global static void processContracts(List<SObject> forecastContracts, List<SObject> renewedContracts, List<SObject> masterContracts) {

    }
    global static void renewContracts(List<SObject> contracts, Id masterContractId) {

    }
    global static void updateRenewalOpportunities(Set<Id> contractIds) {

    }
}
