/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class TriggerControl {
    global TriggerControl() {

    }
    global Boolean alreadyRun(SObject record) {
        return null;
    }
    global Boolean alreadyRun(List<SObject> records) {
        return null;
    }
    global void block() {

    }
    global static void disable() {

    }
    global static void enable() {

    }
    global static SBQQ.TriggerControl getInstance() {
        return null;
    }
    global Boolean isDisabled() {
        return null;
    }
    global static Boolean isEnabled() {
        return null;
    }
    global void reset() {

    }
    global void setDisabled() {

    }
    global Boolean shouldRun(SObject record) {
        return null;
    }
global class CrossPackageDisableHook {
    global CrossPackageDisableHook() {

    }
}
global class CrossPackageEnableHook {
    global CrossPackageEnableHook() {

    }
}
}
