/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class ProductUpgradeController {
    global ProductUpgradeController() {

    }
    @RemoteAction
    global static String loadAssetsWithUpgrades(List<Id> upgradedAssetIds, String quoteJSON) {
        return null;
    }
    @RemoteAction
    global static String loadUpgradedAssets(List<Id> upgradeProductIds) {
        return null;
    }
}
