/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SDGRequest {
    global String FieldSetName;
    global List<sortablegrid.SDGFilter> Filters;
    global Integer PageID;
    global Integer PageSize;
    global String ParentFieldName;
    global String ParentRecordID;
    global String RelationshipName;
    global String SDGTag;
    global String SortColumn;
    global String SortOrder;
    global SDGRequest() {

    }
}
