/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SDGField implements System.Comparable {
    global Boolean canFilter;
    global Boolean canSort;
    global String ColumnName;
    global Integer FieldOrder;
    global String FieldStyle;
    global String FieldType;
    global String FilterType;
    global String ID;
    global Boolean isHTMLFormatted;
    global String Label;
    global List<sortablegrid.AuraSelectOption> options;
    global sortablegrid.SDGFilter Preferences;
    global Integer scale;
    global SDGField(String ID, String Label, String ColumnName, String FieldType, String FieldStyle, Boolean canSort, List<sortablegrid.AuraSelectOption> options) {

    }
    global SDGField(String ID, String Label, String ColumnName, String FieldType, String FieldStyle, Boolean canSort, Boolean isHTMLFormatted, List<sortablegrid.AuraSelectOption> options) {

    }
    global SDGField(String ID, String Label, String ColumnName, String FieldType, String FieldStyle, Boolean canSort, Boolean isHTMLFormatted, List<sortablegrid.AuraSelectOption> options, Integer FieldOrder) {

    }
    global SDGField(String ID, String Label, String ColumnName, String FieldType, String FieldStyle, Boolean canSort, Boolean canFilter, Boolean isHTMLFormatted, List<sortablegrid.AuraSelectOption> options, Integer FieldOrder) {

    }
}
