/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class sdgSecurity {
    global sdgSecurity() {

    }
    global static Boolean CanQuery(String Context, String sObjectType, String commaDelimitedFields, String nonNamespaceFields, String namespace, Boolean ThrowEx) {
        return null;
    }
global class sdgInvalidPermissionsException extends Exception {
}
}
