/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class sdgDataProviderRelationship implements sortablegrid.sdgIDataProvider {
    global sdgDataProviderRelationship() {

    }
    global sortablegrid.SDG LoadSDG(String SDGTag, String ParentRecordId) {
        return null;
    }
    global sortablegrid.SDG LoadSDG(String ParentRecordID, String RelationshipName, String FieldSetName) {
        return null;
    }
    global static sortablegrid.SDGResult getData(sortablegrid.SDG CoreSDG, sortablegrid.SDGRequest request) {
        return null;
    }
    global static Boolean isUserSelectable() {
        return null;
    }
}
