/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class sdgProperties extends VisualEditor.DynamicPickList {
    global sdgProperties() {

    }
    global override VisualEditor.DataRow getDefaultValue() {
        return null;
    }
    global override VisualEditor.DynamicPickListRows getValues() {
        return null;
    }
}
