/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class CustomDataProviderExample implements sortablegrid.sdgDataProvider {
    global CustomDataProviderExample() {

    }
    global sortablegrid.SDG LoadSDG(sortablegrid.SDG coreSDG) {
        return null;
    }
    global static sortablegrid.SDGResult getData(sortablegrid.SDG CoreSDG, sortablegrid.SDGRequest request) {
        return null;
    }
}
