/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class SDG {
    global sortablegrid.SDGInternal internalData;
    global List<sortablegrid.SDGAction> SDGActions;
    global List<sortablegrid.SDGField> SDGFields;
    global String sObjectName;
    global SDG() {

    }
    global SDG(String sUniqueKey) {

    }
    global SDG(String objectname, String ParentFieldName, String sObjectName, String sFilter, String sDefaultSort, String sUniqueKey) {

    }
    global SDG(String objectname, String ParentFieldName, String sObjectName, String sFilter, String sDefaultSort, String sUniqueKey, Boolean AllRows) {

    }
}
