/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class MetadataUtils {
    global MetadataUtils() {

    }
    global static void DeleteFlowMetadata(String flowName) {

    }
    global static void DeleteFlowMetadata(List<String> flowNameList) {

    }
    global static void createFlowMetadata(usf3.MetadataService.Flow flow) {

    }
    global static String filterLabelToApiName(String flowName) {
        return null;
    }
    global static usf3.MetadataService.Flow getFlowMetadata(String flowName) {
        return null;
    }
    global static List<usf3.MetadataService.Flow> getFlowMetadataFromNameList(List<String> flowNameList) {
        return null;
    }
    global static List<usf3.MetadataService.Flow> getFlowMetadataFromName(String flowName) {
        return null;
    }
    global static void handleDeleteResults(usf3.MetadataService.DeleteResult deleteResult) {

    }
    global static void handleUpsertResults(usf3.MetadataService.UpsertResult upsertResult) {

    }
    global static String upsertFlowMetadata(usf3.MetadataService.Flow flow) {
        return null;
    }
}
