/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class XmlUtils {
    global static String SOAP_NS;
    global XmlUtils() {

    }
    global static dom.XmlNode changeTextValue(String newTextValue, dom.XmlNode curNode) {
        return null;
    }
    global static dom.XmlNode getChildNodeByInternalName(dom.XmlNode flowXml, String target) {
        return null;
    }
    global static dom.XmlNode getChildProcessMetadataValueByName(dom.XmlNode flowXML, String pmvTargetName) {
        return null;
    }
    global static List<dom.XmlNode> getChildrenByName(dom.XmlNode flowXml, String elementName) {
        return null;
    }
    global static String getInternalName(dom.XmlNode curNode) {
        return null;
    }
    global static String getProcessMetadataValue(dom.XmlNode curPMV) {
        return null;
    }
global class PBConvertException extends Exception {
}
}
