/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class FormulaEvaluator {
    global FormulaEvaluator() {

    }
    global static usf3.RegExps.ParserContext evaluate(String formula, String outputType, Integer scale) {
        return null;
    }
    global static String evaluateFormula(String formula, String resultType) {
        return null;
    }
    global static String parseFormula(String formula, String context) {
        return null;
    }
    global static void replaceExpressionValues(usf3.RegExps.ParserContext context) {

    }
    global static String updateFormulaFields(String objectName, String objectId, String formula, Set<String> fields) {
        return null;
    }
global class ContextWrapper {
    global String name;
    global String value;
    global ContextWrapper(String name, String value) {

    }
}
global class ExpressionParsingException extends Exception {
}
}
