/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DeployMetadata {
    global DeployMetadata() {

    }
    @AuraEnabled
    global static String checkAsyncRequest(String jobId) {
        return null;
    }
    @AuraEnabled
    global static String deploy(String metadataText, String metadataName, String testLevel, String objectType) {
        return null;
    }
    global static String generateZipfile(String classText, String objectName, String objectType) {
        return null;
    }
    global static usf3.MetadataService.DeployOptions getDeployOptions() {
        return null;
    }
    global static String getObjectMetadata(String objectName) {
        return null;
    }
    global static String getPackageXml(String className, String objectType) {
        return null;
    }
}
