/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class FormulaEvaluatorTest {
    global FormulaEvaluatorTest() {

    }
global class ContextWrapper {
    global String name;
    global String value;
    global ContextWrapper(String name, String value) {

    }
}
}
