/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class HexUtil {
    global HexUtil() {

    }
    global static Integer CRC32Table(Blob data) {
        return null;
    }
    global static Integer CRC32Table(String hexStr) {
        return null;
    }
    global static Integer hexToIntLE(String hexStr) {
        return null;
    }
    global static String intToHexLE(Integer decNumber, Integer sizeInBytes) {
        return null;
    }
}
