/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class FieldDescriptor {
    @AuraEnabled
    global String label;
    @AuraEnabled
    global String name;
    @AuraEnabled
    global List<String> referenceTo;
    @AuraEnabled
    global Boolean required;
    @AuraEnabled
    global String type;
    global FieldDescriptor() {

    }
    global FieldDescriptor(Schema.DescribeFieldResult field) {

    }
    global FieldDescriptor(String name, String label, String type, Boolean required) {

    }
}
