/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class Puff {
    global Puff(String source, Integer srclen, Integer destlen) {

    }
    global Integer codes(usf.Puff.State s, usf.Puff.Huffman lencode, usf.Puff.Huffman distcode) {
        return null;
    }
    global Integer decode(usf.Puff.State s, usf.Puff.Huffman h) {
        return null;
    }
    global String inflate() {
        return null;
    }
global class Huffman {
    global Huffman() {

    }
}
global class State {
    global Integer bitbuf;
    global Integer bitcnt;
    global Integer incnt;
    global Integer inlen;
    global String inStr;
    global String out;
    global Integer outcnt;
    global Integer outlen;
    global State() {

    }
}
}
