/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
@isTest
global class FieldPickerControllerTest {
    global FieldPickerControllerTest() {

    }
    @isTest(SeeAllData=false OnInstall=false)
    global static void testGetObjects() {

    }
    @isTest(SeeAllData=false OnInstall=false)
    global static void testGetPicklistValues() {

    }
}
