/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class FieldSelectorController {
    global FieldSelectorController() {

    }
    @AuraEnabled
    global static List<usf.FieldSelectorController.Field> getObjectFields(String objectName) {
        return null;
    }
global class Field {
    global Field(String name, String label, String type) {

    }
}
global class Response {
    global String errorMessage;
    global List<usf.FieldSelectorController.Field> fields;
    global Response() {

    }
}
}
