export default {
    DCJOB_INFOMODALTAB_GENERALINFO: 'General Info',
    DCJOB_INFOMODALTAB_SELECTEDRECORDS: 'Selected Records',
    DCJOB_INFOMODALTAB_APPLIEDSCENARIOS: 'Applied Scenarios',
    DCJOB_INFOMODALTAB_UNPROCESSEDRESULTS: 'Unprocessed Results',
    DCJOB_INFOMODALTAB_DUPLICATERESULTS: 'Duplicates Found',
    DCJOB_INFOMODALTAB_CONVERTLOG: 'Convert Log',
    DCJOB_INFOMODALTAB_MERGELOG: 'Merge Log',
    DCJOB_OBJECT_USERS: 'Users',
    DCJOB_OBJECT_GROUPS: 'Groups',
    DCJOB_OBJECT_QUEUES: 'Queues',
    DCJOB_BUTTON_CANCEL: 'Cancel',
    DCJOB_BUTTON_CALCULATING: 'Calculating record count',
    DCJOB_BUTTON_TAKINGLONGER: 'Calculation is taking a bit longer...',
    DCJOB_BUTTON_NEXTWITHLIMIT: 'Next with Limit',
    DCJOB_BUTTON_ABORTING: 'Aborting',
    DCJOB_BUTTON_REFRESH: 'Refresh',
    DCJOB_LINK_READMORE: 'Read more',
    DCJOB_SHAREMODAL_SHAREMETHOD: 'Share Method',
    DCJOB_SHAREMODAL_LINK: 'Link',
    DCJOB_SHAREMODAL_COPY: 'Copy to Clipboard',
    DCJOB_SHAREMODAL_COPIED: 'Copied to Clipboard',
    DCJOB_SHAREMODAL_SHAREJOB: 'Share Job',
    DCJOB_SHAREMODAL_DIRECTLINK: 'Direct Link',
    DCJOB_SHAREMODAL_TASK: 'Create a Task',
    DCJOB_SHAREMODAL_EMAIL: 'Send Email',
    DCJOB_SHAREMODAL_RECIPIENTS: 'Recipients',
    DCJOB_SHAREMODAL_SUBJECT: 'Subject',
    DCJOB_SHAREMODAL_TEXT: 'Text',
    DCJOB_SHAREMODAL_ASSIGNTO: 'Assign to',
    DCJOB_SHAREMODAL_STATUS: 'Status',
    DCJOB_SHAREMODAL_DUEDATE: 'Due Date',
    DCJOB_SHAREMODAL_DESCRIPTION: 'Description',
    DCJOB_SHAREMODAL_PRIORITY: 'Priority',
    DCJOB_SHAREMODAL_CREATETASK: 'Create Task',
    DCJOB_SHAREMODAL_TASKSUCCESS: 'Task successfully created',
    DCJOB_SHAREMODAL_EMAILSUCCESS: 'Email sent',
    DCJOB_SHAREMODAL_SHAREINFO: 'To share, the {0} variable is needed. Do not remove it from the text field.',
    DCJOB_PLACEHOLDER_SEARCH: 'Search',
    DCJOB_PLACEHOLDER_SUBJECT: 'Please enter a subject',
    DCJOB_EDITJOB_SCHEDULE: 'Schedule',
    DCJOB_NEWJOB_RUNONPLAUTICLOUD: 'Run on Plauti Cloud',
    DCJOB_NEWJOB_PLAUTICLOUDPROCESSDESCRIPTION: 'Run this job by using Plauti Cloud, a new processing option offered by Plauti.',
    DCJOB_NEWJOB_FILTERLOGIC: 'Filter Logic',
    DCJOB_NEWJOB_FILTERLOGICDESCRIPTION: 'After adding a filter, the filter is numbered. The first filter will be numbered Filter 1, the second will be Filter 2, etc. You apply filter logic based on these numbered filters.',
    DCJOB_NEWJOB_ADDSCHEDULE: 'Add Schedule',
    DCJOB_NEWJOB_AUTOCONVERT: 'Auto Convert',
    DCJOB_NEWJOB_AUTOMERGE: 'Auto Merge',
    DCJOB_NEWJOB_ADDAUTOCONVERT: 'Add Auto Convert',
    DCJOB_NEWJOB_ADDAUTOMERGE: 'Add Auto Merge',
    DCJOB_NEWJOB_AUTOCONVERTTHRESHOLD: 'Auto Convert Threshold',
    DCJOB_NEWJOB_AUTOMERGETHRESHOLD: 'Auto Merge Threshold',
    DCJOB_NEWJOB_SCHEDULEDESCRIPTION: 'Schedule this Job to run at a set frequency and time.',
    DCJOB_NEWJOB_AUTOMERGEDESCRIPTION: 'Add a minimum score for automatically merging duplicate records right after the job is completed.',
    DCJOB_NEWJOB_AUTOCONVERTDESCRIPTION: 'Add a minimum score for automatically converting duplicate records right after the job is completed.',
    DCJOB_NEWJOB_REMOVEAUTOMERGE: 'Remove Auto Merge',
    DCJOB_NEWJOB_REMOVEAUTOCONVERT: 'Remove Auto Convert',
    DCJOB_NEWJOB_AUTOCONVERTWARNING: 'Converting records cannot be undone.',
    DCJOB_NEWJOB_AUTOMERGEWARNING: 'Merging records cannot be undone.',
    DCJOB_NEWJOB_CONVERTOWNERINFO: 'Leads will be converted to the target Account as a new Contact. Decide which user should be the owner of the new Contacts.',
    DCJOB_NEWJOB_CONVERTSTATUS: 'Status after conversion',
    DCJOB_NEWJOB_CONVERTOWNER: 'Owner of new Contact records',
    DCJOB_NEWJOB_LEADOWNER: 'Current Lead Owner',
    DCJOB_NEWJOB_ACCOUNTOWNER: 'Current Account Owner',
    DCJOB_NEWJOB_LOOKUPUSER: 'Lookup User',
    DCJOB_NEWJOB_SFPROCESSDESCRIPTION: 'Run this job on the Salesforce Platform without any data transfer.',
    DCJOB_NEWJOB_DCLOCALPROCESSDESCRIPTION: 'Run this job by using DC Local desktop or DC Local server.',
    DCJOB_NEWJOB_RECORDLIMITREACHED: 'Licensed Record Limit Reached',
    DCJOB_NEWJOB_RECORDLIMITDESCRIPTION: 'Based on the number of records that are currently selected, this job will run into the licensed record limit. As a result, not all selected records will be analyzed for duplicates.',
    DCJOB_NEWJOB_NORECORDSSELECTED: 'No records selected.',
    DCJOB_NEWJOB_SELECTSCENARIO: 'Please select at least one scenario',
    DCJOB_NEWJOB_NOSCENARIO: 'No scenarios found for {0}',
    DCJOB_NEWJOB_NOSELECTIONDESCRIPTION: 'There are currently no records that meet your filter criteria. Consider changing your filter. You can still proceed to configure a scheduled job.',
    DCJOB_NEWJOB_SFRECOMMENDATION: 'Based on the number of records that are currently selected, we recommend processing the job on the Salesforce Platform. From 15.000 records, using DC Local would be recommended for better performance.',
    DCJOB_NEWJOB_DCLOCALRECOMMENDATION: 'Based on the number of records that are currently selected (more than 15.000 records), we recommend processing the job using DC Local for better performance.',
    DCJOB_NEWJOB_FILTERNOTFOUND: 'Selected {0} filter option "{1}" isn\'t available any more.',
    DCJOB_AUTOCONVERT_DCLOCALMESSAGE: 'Run this job by using DC Local desktop or DC Local server. Currently not yet available for Auto Convert.',
    DCJOB_AUTOCONVERT_CONVERTSTATUS: 'Status after conversion',
    DCJOB_AUTOCONVERT_SELECTEDRECORDS: 'Number of records selected for Auto Convert',
    DCJOB_AUTOCONVERT_NEWCONTACTOWNER: 'Owner of new Contact records',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE: 'I acknowledge that starting this auto convert job will convert {0} duplicate records, and that converting records cannot be undone',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'I acknowledge that starting this auto convert job will convert duplicate records, and that converting records cannot be undone',
    DCJOB_AUTOCONVERT_NORECORDSSELECTED: 'There are currently no records that meet your filter criteria. Consider changing your filter.',
    DCJOB_AUTOCONVERT_TRIALWARNING: 'Auto Convert is limited to 20 records due to your trial license. Upgrade to a paid license to remove limitation.',
    DCJOB_AUTOMERGE_FILTERLOGIC: 'Filter Logic',
    DCJOB_AUTOMERGE_FILTERLOGICDESCRIPTION: 'After adding a filter, the filter is numbered. The first filter will be numbered Filter 1, the second will be Filter 2, etc. You apply filter logic based on these numbered filters.',
    DCJOB_AUTOMERGE_SELECTEDRECORDS: 'Number of records selected for Auto Merge',
    DCJOB_AUTOMERGE_SELECTEDDUPLICATEPAIRS: 'Number of duplicate pairs selected for Auto Merge',
    DCJOB_AUTOMERGE_TRIALWARNING: 'Auto Merge is limited to 20 records due to your trial license. Upgrade to a paid license to remove limitation.',
    DCJOB_OVERVIEW_PROCESSEDBY: 'Processed by',
    DCJOB_OVERVIEW_DELETINGJOB: 'Deleting Job',
    DCJOB_OVERVIEW_JOBABORTED: 'Job Aborted',
    DCJOB_ACCESS_CURRENTUSERNOACCESS: 'Current user does not have access to required classes',
    DCJOB_ACCESS_REACHOUTTOADMINISTRATOR: 'Please reach out to your Salesforce Administrator',
    DCJOB_ACCESS_DEACTIVATEDCJOBBETA: 'Deactivate DC Job Beta',
    DCJOB_ACCESS_YOUHAVENOACCESS: 'You have no access to the Apex Class named',
    DCJOB_FILTER_JOBTYPE: 'Job Type',
    DCJOB_FILTER_DUPCHECKJOB: 'Duplicate Job',
    DCJOB_FILTER_DUPCHECKLOCAL: 'DC Local / Plauti Cloud',
    DCJOB_FILTER_UNIQUEBULKAPIINSERT: 'Unique Import / Bulk API Insert',
    DCJOB_FILTER_WEBTOLEAD: 'Web to Lead',
    DCJOB_FILTER_SETFORMERGE: 'Set for Merge',
    DCJOB_FILTER_SINGLEAPIINSERT: 'Single API Insert',
    DCJOB_FILTER_FLOW: 'Flow',
    DCJOB_FILTER_ABORTED: 'Aborted',
    DCJOB_FILTER_FAILED: 'Failed',
    DCJOB_FILTER_COMPLETED: 'Completed',
    DCJOB_FILTER_HOLDING: 'Holding',
    DCJOB_FILTER_PROCESSING: 'Processing',
    DCJOB_FILTER_INCAMPAIGN: 'In Campaign',
    DCJOB_FILTER_FILTER: 'Filter',
    DCJOB_JOBCARD_PROCESSEDWITHDCLOCAL: 'DC Local Job',
    DCJOB_JOBCARD_PROCESSEDWITHCLOUD: 'Plauti Cloud Job',
    DCJOB_JOBPAGE_APEXJOBID: 'Apex Job ID',
    ONBOARDING_NEXT: 'Next',
    ONBOARDING_BACK: 'Back',
    ONBOARDING_FINISH: 'Finish',
    ONBOARDING_DOCUMENTATION: 'Documentation',
    ONBOARDING_WATCH_VIDEO: 'Watch Video',
    ONBOARDING_GETTING_STARTED: 'Getting Started with Duplicate Check',
    ONBOARDING_THANK_YOU_FOR_INSTALLING: 'Thank you for installing Duplicate Check',
    ONBOARDING_RUNNING_A_DC_JOB: 'Running a DC Job',
    ONBOARDING_SETUP_DUPLICATE_PREVENTION: 'Set up duplicate prevention',
    ONBOARDING_LEARN_ABOUT_DCLIVE: 'Learn about DC Live',
    ONBOARDING_HOW_TO_CONFIGURE_DC: 'How to configure Duplicate Check',
    ONBOARDING_OPTIONS_FOR_AUTOMATION: 'Options for automation',
    ONBOARDING_INTEGRATION: 'Integration',
    ONBOARDING_CUSTOMISATION: 'Customization',
    ONBOARDING_GET_STARTED: 'Let\'s get started!',
    ONBOARDING_NOTIFICATION_JOB_STARTED: 'DC Job started on {0}',
    ONBOARDING_NOTIFICATION_VIEW_PROGRESS: 'Click to view progress at DC Job Overview',
    ONBOARDING_JOB_INFO_CARD_OPEN_RESULTS: 'Open Results',
    ONBOARDING_JOB_INFO_CARD_STATUS: 'Status',
    ONBOARDING_JOB_INFO_CARD_RESULT: 'Result',
    ONBOARDING_INTRO_THANK_YOU_FOR_INSTALLING: 'Thank you for installing Duplicate Check!',
    ONBOARDING_INTRO_OPENING_MESSAGE: 'Hello Trailblazer! We are delighted to see that you installed Duplicate Check for Salesforce. You are a few steps away from a duplicate-free Salesforce environment that has accurate and reliable data, leading to better decision-making, increased productivity, and improved customer satisfaction.',
    ONBOARDING_INTRO_START_LOOKING_FOR_DUPLICATES: 'We took the liberty to start looking for some duplicates…',
    ONBOARDING_INTRO_LOOKING_FOR_DUPLICATE_MESSAGE: 'We took the liberty to start a quick job on a thousand {0} records so that we can show you how easy it is to find those duplicate records in the {0} object. Feel free to check out the result in a new tab by clicking “Open Results”.',
    ONBOARDING_RUN_JOB_OPENING_MESSAGE: 'DC Job is the starting point for all your deduplication efforts. To find all duplicate records in any Salesforce Object, you can run a “Duplicate Check Job”, also referred to as “DC Job”.',
    ONBOARDING_RUN_JOB_START_FIRST_JOB_HELP: 'Let us help you start your first jobs!',
    ONBOARDING_RUN_JOB_START_NOW: 'Start Now',
    ONBOARDING_RUN_JOB_STARTED: 'Started',
    ONBOARDING_RUN_JOB_LEAD_TITLE: 'Run a job on Leads',
    ONBOARDING_RUN_JOB_LEAD_DESCRIPTION: 'Find duplicates based on comparing First Name, Last Name, Email, Company, and Phone.',
    ONBOARDING_RUN_JOB_CONTACT_TITLE: 'Run a job on Contacts',
    ONBOARDING_RUN_JOB_CONTACT_DESCRIPTION: 'Find duplicates based on comparing First Name, Last Name, Email, and Phone.',
    ONBOARDING_RUN_JOB_ACCOUNT_TITLE: 'Run a job on Accounts',
    ONBOARDING_RUN_JOB_ACCOUNT_DESCRIPTION: 'Find duplicates based on comparing Company Name, Billing City and Phone.',
    ONBOARDING_RUN_JOB_THINGS_TO_KNOW: 'Things to know about DC Jobs',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_FEATURE: 'cross-object feature',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_MESSAGE: 'With the {0}, compare records in any object with records in any other object',
    ONBOARDING_RUN_JOB_PLAUTI_CLOUD: 'Plauti Cloud',
    ONBOARDING_RUN_JOB_LOCAL: 'DC Local',
    ONBOARDING_RUN_JOB_PROCESSING: 'Decide where to process a DC Job - completely within Salesforce, or externally via {0} or {1}',
    ONBOARDING_RUN_JOB_MANUALLY: 'manually',
    ONBOARDING_RUN_JOB_AUTOMATICALLY: 'automatically',
    ONBOARDING_RUN_JOB_MERGE_OR_CONVERT: 'Choose to merge or convert {0} or {1}',
    ONBOARDING_RUN_JOB_SCHEDULE_A_JOB: 'Schedule a job',
    ONBOARDING_RUN_JOB_SCHEDULE_MESSAGE: '{0} to run at a frequency and time you decide',
    ONBOARDING_PREVENTION_DUPLICATE_PREVENTION: 'Duplicate Prevention',
    ONBOARDING_PREVENTION_OPENING_MESSAGE: 'Below, find the different ways a record can enter Salesforce, and see how DC can make sure duplicates are detected and taken care of.',
    ONBOARDING_PREVENTION_MANUAL_INSERT: 'Manual Insert',
    ONBOARDING_PREVENTION_MANUAL_INSERT_DESCRIPTION: 'Even when being extra careful, duplicates can enter Salesforce through end-users entering them manually. Duplicate Check has a great feature that you can decide to implement, which we call "DC Entry". Find out more by visiting out documentation.',
    ONBOARDING_PREVENTION_IMPORT: 'Import',
    ONBOARDING_PREVENTION_IMPORT_DESCRIPTION: 'When importing records through Data Loader or the Data Import Wizard, duplicates will find their way to your Salesforce environment. Using Duplicate Check, a duplicate is flagged during an import, after which you have the option to merge the records. By not blocking the duplicate from coming in you have the chance to keep the most up-to-date information.',
    ONBOARDING_PREVENTION_INTEGRATIONS: 'Integrations (Salesforce API)',
    ONBOARDING_PREVENTION_INTEGRATIONS_DESCRIPTION: 'The average Salesforce implementation is linked to a dozen external tools that all communicate via the Salesforce API, creating a lot of new records daily. Duplicate Check can monitor the Salesforce API channel and detect any duplicate at point-of-entry.',
    ONBOARDING_PREVENTION_WEBFORMS: 'Webforms',
    ONBOARDING_PREVENTION_WEBFORMS_DESCRIPTION: 'If you have webforms linked to your Salesforce environment, you are probably familiar with the issue of getting duplicates. By using Duplicate Check, you gain the ability to detect duplicates from any webform, and process the duplicate in real-time.',
    ONBOARDING_DCLIVE_OPENING_MESSAGE: 'At Plauti, we think data quality is a shared responsibility across the whole organization. That is the reason why we created DC Live.',
    ONBOARDING_DCLIVE_DESCRIPTION: 'DC Live  is a component you can add to any objects page layout and is accessible to any user in Salesforce. When a record is opened, DC Live shows duplicates for the record that is opened.',
    ONBOARDING_DCLIVE_EMPOWER_END_USERS: 'Empower end-users by giving them insight in the quality of their data and decide to allow them to {0}, or to just {1}.',
    ONBOARDING_DCLIVE_MERGE_RECORDS_THEMSELVES: 'merge records themselves',
    ONBOARDING_DCLIVE_FLAG_FOR_ADMIN: 'flag them for an administrator',
    ONBOARDING_DCLIVE_HOW_TO_CONFIGURE: 'How to configure DC Live',
    ONBOARDING_CONFIGURE_OPENING_MESSAGE: 'One of the things that Duplicate Check is good at, is configuring the tool so that it adapts to your unique Salesforce implementation. To get the most out of the tool, please make sure to read up on the following subjects.',
    ONBOARDING_CONFIGURE_SCENARIOS_SEARCH_INDEX: 'Scenarios & Search Index',
    ONBOARDING_CONFIGURE_SCENARIO_EXPLANATION: 'A scenario in Duplicate Check is like the "matching rules" in Salesforce - it decides how to compare records and it decides what a duplicate record is. To get the most out of the tool, we recommend to read about what it can do and how it can be configured.',
    ONBOARDING_CONFIGURE_SEARCH_INDEX_EXPLANATION: 'For a scenario to work optimally, we ask you to enable and create the Search Index. Duplicate Check uses the Search Index to find duplicate records using the applied scenario. Without a Search Index, Duplicate Check is not able to find all duplicates.',
    ONBOARDING_CONFIGURE_MERGE_RULES: 'Merge Rules',
    ONBOARDING_CONFIGURE_MERGE_RULES_EXPLANATION: 'When merging records within an object, Duplicate Check calls upon the Merge Rules to pick a master record and to determine what fields should be stored in that master record. The Merge Rules also determine what fields are pre-selected on the manual merge page and the rules are executed when performing an automated merge. Learn how to configure the Merge Rules.',
    ONBOARDING_AUTOMATION_OPENING_MESSAGE: 'Being native to Salesforce, Duplicate Check offers best in class real-time duplicate detection and processing.',
    ONBOARDING_AUTOMATION_DC_LEVEL_OFFER: 'Duplicate Check offers different levels of automation',
    ONBOARDING_AUTOMATION_EXPLANATION: 'There are different levels of automation, ranging from human-operated to fully automated processes. Learn more about automation and choose what is right for you.',
    ONBOARDING_AUTOMATION_AUDIT_LOG: 'Audit Log',
    ONBOARDING_AUTOMATION_AUDIT_LOG_DESCRIPTION: 'Any merge or convert activity, executed manually or automatically, can be tracked in the audit log. The audit log needs to be enabled before logs are stored, since this takes up some storage space.',
    ONBOARDING_AUTOMATION_DIRECT_PROCESSING: 'Direct Processing',
    ONBOARDING_INTEGRATION_OPENING_MESSAGE: 'You have chosen Salesforce because of its flexibility to integrate all of your business processes. Our Apex plugins, Flow Actions, Api and SFDX plugins make sure deduplication seamlessly integrates with your existing processes.',
    ONBOARDING_INTEGRATION_APEX_API: 'Duplicate Check Apex API',
    ONBOARDING_INTEGRATION_APEX_API_DESCRIPTION: 'Duplicate Check provides an Apex API that allows you to implement all DC features in your own Apex projects. This includes finding duplicate records using the DC search engine, merging and converting, but it also allows you to export DC configuration sets via API.',
    ONBOARDING_INTEGRATION_REST_API: 'Duplicate Check Rest API',
    ONBOARDING_INTEGRATION_REST_API_DESCRIPTION: 'Duplicate Check offers a REST API which can be used to search or insert/update records in Salesforce via the Data API. The REST Data API lets you create records without creating duplicates. When a record is added via the Data API, it is directly compared with all existing records in Salesforce. If duplicates are present, it will update the existing record instead of creating a duplicate record.',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS: 'Duplicate Check Flow Actions',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS_DESCRIPTION: 'Duplicate Check offers most of its features in the form of a Flow Action. Because of this, you gain the ability to implement all features related to duplicate prevention, merging, converting, and more, in any Salesforce Flow.',
    ONBOARDING_CUSTOMISATION_OPENING_MESSAGE: 'You have chosen Salesforce because of its flexibility to integrate all of your business processes. Our Apex plugins, Flow Actions, Api and SFDX plugins make sure deduplication seamlessly integrates with your existing processes.',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS: 'Duplicate Check Plugins',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS_DESCRIPTION: 'We understand that a business has very specific processes and that it is hard to find a tool that can adapt to difficult requirements. Use the plugins that Duplicate Check offers if you wish to make changes to the out-of-the-box functionality.',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS: 'SFDX Plugins',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS_DESCRIPTION: 'The SFDX plugins allow developers to automate tasks that are related to Duplicate Check Licenses as well as Duplicate Check configurations. For example, if you have a built a pipeline with different staging environments you can automate the synchronization of Duplicate Checks Configuration so it is the same across all environments.',
    ONBOARDING_GET_STARTED_A_LOT_OF_INFO: 'That’s a lot of information, right?',
    ONBOARDING_GET_STARTED_OPENING_MESSAGE: 'You now know the basics of what Duplicate Check can do. We know it\'s a lot to take in. You are now ready to start your journey towards a duplicate-free Salesforce environment with all the amazing advantages it will provide.',
    ONBOARDING_GET_STARTED_FEELING_LOST: 'Feeling lost? Feel free to schedule a one-on-one session with one of our product experts.',
    ONBOARDING_GET_STARTED_SCHEDULE_CALL: 'Schedule a call with one of our Product Experts!',
    ONBOARDING_GET_STARTED_FLYING_START: 'Want to get a flying start implementing Duplicate Check for your organization? Feel free to schedule a call with one of our product experts, free of charge. We would be more than happy to guide you in exploring and configuring Duplicate Check.',
    ONBOARDING_GET_STARTED_SCHEDULE_A_CALL: 'Schedule a call',
    ONBOARDING_GET_STARTED_INTERESTING_LINKS: 'Interesting links',
    ONBOARDING_GET_STARTED_SCHEDULE_PRODUCT_EXPERT: 'Schedule a call with a Product Expert',
    ONBOARDING_GET_STARTED_KNOWLEDGEBASE: 'Knowledge Base',
    ONBOARDING_GET_STARTED_HOWTO_VIDEOS: 'How-to Videos',
    ONBOARDING_GET_STARTED_GUIDE: 'Getting Started Guide',
    ONBOARDING_GET_STARTED_CONTACT_SUPPORT: 'Contact Support',
    general: {
        DCJOB_AUTOCONVERT_LEARNMORE: 'Learn More',
        DCJOB_AUTOMERGE_LEARNMORE: 'Learn More',
        DCJOB_NEWJOB_LEARNMORE: 'Learn More',
        DCJOB_AUTOMERGE_SPEED: 'Speed',
        DCJOB_NEWJOB_SPEED: 'Speed',
        DCJOB_NEWJOB_MEDIUM: 'medium',
        DCJOB_AUTOMERGE_MEDIUM: 'medium',
        DCJOB_NEWJOB_RECOMMENDED: 'Recommended',
        DCJOB_AUTOMERGE_RECOMMENDED: 'Recommended',
        DCJOB_AUTOCONVERT_RECOMMENDED: 'Recommended',
        DCJOB_DELETEMODAL_ALLTIME: 'All Time',
        DCJOB_DELETEMODAL_SETDATE: 'Set Date',
        DCJOB_DELETEMODAL_SETDATERANGE: 'Set Date Range',
        DCJOB_DELETEMODAL_FROM: 'From',
        DCJOB_DELETEMODAL_UNTIL: 'Until',
        DCJOB_DELETEMODAL_TYPE: 'Type',
        DCJOB_DELETEMODAL_DATE: 'Date',
        DCJOB_JOBPAGE_OBJECT: 'Object',
        DCJOB_SCHEDULEDJOBPAGE_OBJECT: 'Object',
        DCJOB_SCHEDULEDJOBPAGE_NOTAPPLICABLE: 'N/A',
        DCJOB_SCHEDULEDJOBPAGE_NOME: 'Name',
        DCJOB_SCHEDULEDJOBPAGE_FREQUENCYANDTIME: 'Frequency & Time',
        DCJOB_SCHEDULEDJOBPAGE_STATUS: 'Status',
        DCJOB_SCHEDULEDJOBPAGE_NEXTSTART: 'Next Start',
        DCJOB_PAGINATIONCOMPONENT_PAGE: 'Page',
        DCJOB_PAGINATIONCOMPONENT_OF: 'of',
    },
    groupObject: {
        GROUPNUMBER: 'Group Number',
        GROUPPAIRCOUNT: 'Group Pair Count',
        GROUPRECORDCOUNT: 'Group Record Count',
        GROUPCONTAINSMERGEERROR: 'Group Contains Merge Error',
        GROUPCONTAINSCONVERTERROR: 'Group Contains Convert Error',
        GROUPFOUNDJOB: 'Found in Job',
    },
    days: {
        DCJOB_NEWJOB_MONDAY: 'Monday',
        DCJOB_NEWJOB_TUESDAY: 'Tuesday',
        DCJOB_NEWJOB_WEDNESDAY: 'Wednesday',
        DCJOB_NEWJOB_THURSDAY: 'Thursday',
        DCJOB_NEWJOB_FRIDAY: 'Friday',
        DCJOB_NEWJOB_SATURDAY: 'Saturday',
        DCJOB_NEWJOB_SUNDAY: 'Sunday',
    },
    monthly: {
        LAST_DAY: 'Last day',
        LAST_WEEKDAY: 'Last weekday',
    },
    frequency: {
        DCJOB_SCHEDULED_FREQUENCY_PLACEHOLDER: 'Select an Option...',
        DCJOB_SCHEDULED_FREQUENCY_DAILY: 'Daily',
        DCJOB_SCHEDULED_FREQUENCY_WEEKLY: 'Weekly',
        DCJOB_SCHEDULED_FREQUENCY_MONTHLY: 'Monthly',
        DCJOB_SCHEDULED_FREQUENCY_CUSTOM: 'Custom',
    },
    titles: {
        DCJOB_JOBPAGE_JOBOVERVIEW: 'Job Overview',
        DCJOB_SCHEDULEDJOBPAGE_SCHEDULEDJOB: 'Scheduled Job Overview',
        DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOB: 'Delete Scheduled Job',
        DCJOB_JOBPAGE_LISTVIEWS: 'LIST VIEWS',
    },
    buttons: {
        DCJOB_JOBCARD_ABORT: 'Abort',
        DCJOB_BACK: 'Back',
        DCJOB_NEWJOB_BACK: 'Back',
        DCJOB_AUTOMERGE_BACK: 'Back',
        DCJOB_AUTOCONVERT_BACK: 'Back',
        DCJOB_JOBPAGE_CANCEL: 'Cancel',
        DCJOB_NEWJOB_CANCEL: 'Cancel',
        DCJOB_JOBCARD_CANCEL: 'Cancel',
        DCJOB_EXPORTMODAL_CANCEL: 'Cancel',
        DCJOB_DELETEMODAL_CANCEL: 'Cancel',
        DCJOB_AUTOMERGE_CANCEL: 'Cancel',
        DCJOB_AUTOCONVERT_CANCEL: 'Cancel',
        DCJOB_SCHEDULEDJOBPAGE_CANCEL: 'Cancel',
        DCJOB_SCHEDULEDJOBPAGE_DELETEJOBS: 'Delete Jobs',
        DCJOB_JOBPAGE_DELETEJOBS: 'Delete Jobs',
        DCJOB_DELETEMODAL_DELETEJOBS: 'Delete Jobs',
        DCJOB_SCHEDULEDJOBPAGE_DELETE: 'Delete',
        DCJOB_JOBCARD_DELETE: 'Delete',
        DCJOB_DELETEMODAL_DELETE: 'Delete',
        DCJOB_EXPORTMODAL_EXPORTDCLOCAL: 'Export via DC Local',
        DCJOB_EXPORTMODAL_EXPORTCLOUD: 'Export via Plauti Cloud',
        DCJOB_JOBPAGE_FILTER: 'Filter',
        DCJOB_NEWJOB_FILTER: 'Filter',
        DCJOB_FILTER: 'Filter',
        DCJOB_SCHEDULEDJOBPAGE_INFO: 'Info',
        DCJOB_JOBCARD_INFO: 'Info',
        DCJOB_SCHEDULEDJOBPAGE_EDIT: 'Edit',
        DCJOB_SCHEDULEDJOBPAGE_JOBOPTIONS: 'Job Options',
        DCJOB_JOBCARD_JOBOPTIONS: 'Job Options',
        DCJOB_SCHEDULEDJOBPAGE_NEWJOB: 'New Job',
        DCJOB_JOBPAGE_NEWJOB: 'New Job',
        DCJOB_NEWJOB_NEXT: 'Next',
        DCJOB_AUTOMERGE_NEXT: 'Next',
        DCJOB_AUTOCONVERT_NEXT: 'Next',
        DCJOB_JOBPAGE_SAVE: 'Save',
        DCJOB_NEWJOB_START: 'Start',
        DCJOB_NEWJOB_SCHEDULE: 'Schedule',
        DCJOB_AUTOMERGE_START: 'Start',
        DCJOB_AUTOCONVERT_START: 'Start',
        DCJOB_JOBPAGE_SORTJOBS: 'Sort Jobs',
        DCJOB_SCHEDULEDJOBPAGE_RUNNOW: 'Run Once Now',
        DCJOB_SCHEDULEDJOBPAGE_DEACTIVATED: 'Deactivate',
        DCJOB_SCHEDULEDJOBPAGE_ACTIVATE: 'Activate',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS_NUMBER: 'View Results {0}',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS: 'View Results',
        MERGE: 'Merge',
        QUICKMERGE: 'Quick Merge',
        QUICKCONVERT: 'Quick Convert',
        MORE: 'More',
        edit: 'Edit',
        DCJOB_JOBCARD_VIEWRESULTS: 'View Results {0}',
        DCJOB_JOBPAGE_DELETESELECTEDJOBS: 'Delete Selected Jobs',
        DCJOB_JOBPAGE_SELECTALL: 'Select All',
        DCJOB_JOBPAGE_DESELECTALL: 'Deselect All',
    },
    badges: {
        DCJOB_JOBCARD_REVIEWERRORS: 'Review Errors',
        DCJOB_JOBCARD_READMORE: 'Read More',
        DCJOB_JOBCARD_LIMITTEXT: 'License Record Limit Reached.',
        DCJOB_JOBCARD_DELETESELECTED: `{count} job selected | {count} jobs selected`,
    },
    metaData: {
        DCJOB_JOBPAGE_AVERAGESCORE: 'Average Score',
        DCJOB_OVERALLJOBRESULTS_AVERAGESCORE: 'Average Score',
        DCJOB_JOBPAGE_STORAGESPACETAKEN: 'Storage Space Taken',
        DCJOB_JOBPAGE_TOTALGROUPS: 'Total Groups',
        DCJOB_JOBPAGE_TOTALJOBS: 'Total Jobs',
        DCJOB_JOBPAGE_TOTALPAIRS: 'Total Pairs',
        DCJOB_JOBPAGE_TOTALRECORDS: 'Total Records',
        DCJOB_OVERALLJOBRESULTS_RECORDS: 'Records',
        DCJOB_OVERALLJOBRESULTS_GROUPS: 'Groups',
        DCJOB_OVERALLJOBRESULTS_PAIRS: 'Pairs',
        DCJOB_OVERALLJOBRESULTS_OBJECT: 'Object',
    },
    job: {
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDTITLE: 'Audit Log not available in your license',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDSUBTITLE: 'The Audit Log is available in Premium and up',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDBUTTON: 'Upgrade Now',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDRUPGRADEURL: 'https://go.plauti.com/l/640773/2023-03-27/53tydt',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDTITLE: 'Audit Log Disabled',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDSUBTITLE: 'Please ask your Salesforce Administrator to enable the Duplicate Check audit log.',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGETITLE: 'Merge Log is empty',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTTITLE: 'Convert Log is empty',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGESUBTITLE: 'There was no merge activity for this job yet.',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTSUBTITLE: 'There was no convert activity for this job yet.',
        DCJOB_AUDITLOGTABLEHEADER_MASTERRECORD: 'Master Record',
        DCJOB_AUDITLOGTABLEHEADER_MERGEDRECORDS: 'Merged Record(s)',
        DCJOB_AUDITLOGTABLEHEADER_LEADRECORD: 'Lead Record',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOPERSON: 'Convert to Person Account',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOACCOUNT: 'Convert to Account',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOCONTACT: 'Convert to Contact',
        DCJOB_AUDITLOGTABLEHEADER_METHOD: 'Method',
        DCJOB_AUDITLOGTABLEHEADER_DATETIME: 'Date & Time',
        DCJOB_AUDITLOGTABLEHEADER_USER: 'User',
        DCJOB_AUDITLOGTOOLTIP_CONVERTEDRECORD: 'Converted Record',
        DCJOB_AUDITLOGTOOLTIP_MERGEDRECORD: 'Merged Record',
        DCJOB_AUDITLOGTOOLTIP_RECORDID: 'Record ID:',
        DCJOB_AUDITLOGTOOLTIP_AUDITID: 'Audit ID:',
        DCJOB_AUDITLOGSUMMARY_NUMBEROFRECORDS: 'Number of Records {0}',
        DCJOB_JOBCARD_JOBS: 'Jobs',
        DCJOB_JOBCARD_TASK: 'Task',
        DCJOB_JOBCARD_STARTED: 'Started at',
        DCJOB_JOBCARD_FINISHED: 'Finished at',
        DCJOB_JOBCARD_USER: 'Started by',
        DCJOB_JOBCARD_STATUS: 'Status',
        DCJOB_JOBPAGE_STATUS: 'Status',
        DCJOB_JOBCARD_RESULT: 'Result',
        DCJOB_JOBPAGE_JOBNAME: 'Job Name',
        DCJOB_NEWJOB_JOBNAME: 'Job Name',
        DCJOB_JOBCARD_JOBNAME: 'Job Name',
        DCJOB_AUTOMERGE_JOBNAME: 'Job Name',
        DCJOB_AUTOCONVERT_JOBNAME: 'Job Name',
        DCJOB_JOBPAGE_JOBID: 'Job ID',
        DCJOB_JOBCARD_JOBID: 'Job ID',
        DCJOB_JOBPAGE_NOJOBS: 'No jobs.',
        DCJOB_SCHEDULEDJOBPAGE_NOSCHEDULEDJOBS: 'No jobs scheduled.',
        DCJOB_NEWJOB_JOBNAMEPLACEHOLDER: 'Please insert a job name',
        DCJOB_JOBCARD_AUTOMERGE: 'Auto Merge',
        DCJOB_JOBCARD_MANUALMERGE: 'Manual Merge',
        DCJOB_JOBCARD_QUICKMERGE: 'Quick Merge',
        DCJOB_JOBCARD_AUTOCONVERT: 'Auto Convert',
        DCJOB_JOBCARD_MANUALCONVERT: 'Manual Convert',
        DCJOB_JOBCARD_MERGELOG: 'Merge Log',
        DCJOB_JOBCARD_CONVERTLOG: 'Convert Log',
        DCJOB_JOBCARD_QUICKCONVERT: 'Quick Convert',
        DCJOB_JOBCARD_AUTOMERGEDCLOCAL: 'Auto Merge via DC Local',
        DCJOB_JOBCARD_AUTOMERGECLOUD: 'Auto Merge via Plauti Cloud',
        DCJOB_AUTOMERGE_CONFIGUREAUTOMERGE: 'Configure Auto Merge',
        DCJOB_AUTOCONVERT_CONFIGUREAUTOCONVERT: 'Configure Auto Convert',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE: 'I acknowledge that starting this auto merge job wil merge {0} duplicate records and that merging records cannot be undone.',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'I acknowledge that starting this auto merge job wil merge duplicate records and that merging records cannot be undone.',
        DCJOB_EXPORTMODAL_EXPORTRESULTS: 'Export Results',
        DCJOB_JOBCARD_EXPORTRESULTSDCLOCAL: 'Export Results via DC Local',
        DCJOB_JOBCARD_EXPORTRESULTSCLOUD: 'Export Results via Plauti Cloud',
        DCJOB_JOBCARD_NUMBEROFRECORDS: 'Number of Records',
        DCJOB_JOBPAGE_NUMBEROFRECORDS: 'Number of Records',
        DCJOB_JOBCARD_NUMBEROFPAIRS: 'Number of Pairs',
        DCJOB_JOBCARD_RESULTFIELDS: 'Result Fields',
        DCJOB_AUTOMERGE_CONFIRMATION: 'Confirmation',
        DCJOB_AUTOCONVERT_CONFIRMATION: 'Confirmation',
        DCJOB_AUTOMERGE_PROCESSEDBY: 'Processed by',
        DCJOB_AUTOCONVERT_PROCESSEDBY: 'Processed by',
        DCJOB_DELETEMODAL_CURRENTNUMBEROFJOBS: 'Current number of jobs in DC Jobs',
        DCJOB_DELETEMODAL_JOBSCREATEDAT: 'Jobs created at',
        DCJOB_DELETEMODAL_CONTAINSDUPLICATERESULTS: 'Contains duplicate results',
        DCJOB_DELETEMODAL_JOBSSELECTEDFORDELETION: 'Number of jobs selected for deletion',

        infoModal: {
            DCJOB_INFOMODAL_GENERALINFO_STARTEDBYUSER: 'Started by user',
            DCJOB_INFOMODAL_GENERALINFO_STATUS: 'Status',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMESTARTED: 'Date & Time Started',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMEFINISHED: 'Date & time Finished',
            DCJOB_INFOMODAL_GENERALINFO_TOTALTIMETAKEN: 'Total Time Taken',
            DCJOB_INFOMODAL_GENERALINFO_PROCESSEDBY: 'Processed By',
            DCJOB_INFOMODAL_GENERALINFO_LASTDUPLICATEADDED: 'Last Duplicate Added',
            DCJOB_INFOMODAL_GENERALINFO_APPLIEDSCENARIOS: 'Applied Scenarios',
            DCJOB_INFOMODAL_GENERALINFO_JOBID: 'Job ID',
            DCJOB_INFOMODAL_GENERALINFO_APEXJOBID: 'Apex Job ID',
            DCJOB_INFOMODAL_GENERALINFO_CREATEDBYUSER: 'Created By User',
            DCJOB_INFOMODAL_GENERALINFO_FREQUENCY: 'Frequency',
            DCJOB_INFOMODAL_GENERALINFO_LASTRUNAT: 'Last run at',
            DCJOB_INFOMODAL_GENERALINFO_NEXTRUNAT: 'Next run at',
            DCJOB_INFOMODAL_GENERALINFO_NUMBEROFTIMESRUN: 'Number of times run',
            DCJOB_INFOMODAL_GENERALINFO_AUTOPROCESS: 'Auto process',
            DCJOB_INFOMODAL_GENERALINFO_SCHEDULED_LASTMODIFIED: 'Scheduled Job last modified by + Date & Time',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEGROUPS: 'Duplicate Groups',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEPAIRS: 'Duplicate Pairs',
            DCJOB_INFOMODAL_DUPLICATESINFO_RECORDSINVOLVED: 'Records involved',
            DCJOB_INFOMODAL_DUPLICATESINFO_AVERAGESCORE: 'Average Score',
            DCJOB_INFOMODAL_SELECTEDINFO_OBJECT: 'Object',
            DCJOB_INFOMODAL_SELECTEDINFO_NUMBEROFRECORDS: 'Number of Records',
            DCJOB_INFOMODAL_SELECTEDINFO_SOURCE: 'Source',
            DCJOB_INFOMODAL_SELECTEDINFO_MATCH: 'Match'

        },
        sortOptions: {
            DCJOB_JOBPAGE_SORTBY: 'Sort By',
            DCJOB_JOBPAGE_DATETIMESTARTED: 'Started at',
            DCJOB_JOBPAGE_DATETIMEFINISHED: 'Finished at',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEGROUPS: 'Number of Duplicate Groups',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEPAIRS: 'Number of Duplicate Pairs',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATERECORDSINVOLVED: 'Number of Duplicate Records Involved',
            DCJOB_JOBPAGE_LASTDUPLICATEADDED: 'Last Duplicate Added',
            DCJOB_JOBPAGE_ORDER: 'Order',
            DCJOB_JOBPAGE_ASCENDING: 'Ascending',
            DCJOB_JOBPAGE_DESCENDING: 'Descending',
        },
        menuOptions: {
            DCJOB_SCHEDULEDJOBPAGE_TITLE: 'Job Options',
            DCJOB_JOBCARD_TITLE: 'Job Options',
            DCJOB_JOBCARD_OPTION_RESTART: 'Restart',
            DCJOB_JOBCARD_OPTION_STARTAUTOMERGE: 'Start Auto Merge',
            DCJOB_JOBCARD_OPTION_STARTAUTOCONVERT: 'Start Auto Convert',
            DCJOB_JOBCARD_OPTION_EXPORTRESULTS: 'Export Results',
            DCJOB_JOBCARD_OPTION_SHAREJOB: 'Share Job',
            DCJOB_JOBCARD_OPTION_DELETEJOB: 'Delete Job',
        },

        new: {
            DCJOB_NEWJOB_STEP: 'Step',
            DCJOB_AUTOMERGE_STEP: 'Step',
            DCJOB_AUTOCONVERT_STEP: 'Step',
            DCJOB_NEWJOB_SELECTRECORDS: 'Select Records',
            DCJOB_NEWJOB_JOBOPTIONS: 'Job Options',
            DCJOB_NEWJOB_PROCESSOPTIONS: 'Process Options',
            DCJOB_NEWJOB_SELECTOBJECT: 'Select Object',
            DCJOB_NEWJOB_SELECTOBJECTPLACEHOLDER: 'Please select an Object',
            DCJOB_NEWJOB_SELECTOPTIONSPLACEHOLDER: 'Search options...',
            DCJOB_NEWJOB_ADDCROSSOBJECT: 'Add Cross Object',
            DCJOB_NEWJOB_REMOVECROSSOBJECT: 'Remove Cross Object',
            DCJOB_NEWJOB_ADDFILTER: 'Add Filter',
            DCJOB_NEWJOB_MATCHWITH: 'Match with',
        },

        deleteAll: {
            DCJOB_DELETESELECTED_TITLE: 'Delete Selected Jobs',
            DCJOB_DELETESELECTED_MESSAGE: 'Are you sure you want to delete {count} selected job? This action cannot be undone. | Are you sure you want to delete {count} selected jobs? This action cannot be undone.',
        },

        delete: {
            DCJOB_DELETEMODAL_DELETEJOBSMESSAGE: 'Are you sure you want to delete {0} Jobs? Deleting Jobs cannot be undone.',
            DCJOB_JOBCARD_DELETEMESSAGE: 'Are you sure you want to delete {0}?',
            DCJOB_JOBCARD_DELETEUNDONE: 'Deleting {0} cannot be undone.',
            DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOBMESSAGE: 'Are you sure you want to delete the "{0}" scheduled job?',
        },

        options: {
            DCJOB_NEWJOB_SCHEDULE: 'Schedule',
            addScheduler: 'Add Schedule',
            scheduleDescription: 'Decide to schedule this batch to run at a configured frequency and time.',
            autoMergeDescription: 'Decide to add a threshold for automatically merging duplicate records right after the batch completes. Please not that an auto merge can also be started manually at any time.',
            DCJOB_NEWJOB_REMOVESCHEDULER: 'Remove Schedule',
            addAutoMerge: 'Add Auto Merge',
            removeAutoMerge: 'Remove Auto Merge',
            DCJOB_NEWJOB_FREQUENCY: 'Frequency',
            DCJOB_NEWJOB_CRONSTRING: 'Cron String',
            DCJOB_NEWJOB_CRONSTRING_INFO: 'Use the Cron String format (\'* * * * * *\', without quotes) to schedule DC Jobs by specifying seconds, minute, hour, day, month and day of the week.',
            DCJOB_NEWJOB_RECURS: 'Recurs every week on',
            DCJOB_NEWJOB_MONTHRECURS: 'Recurs every month on the',
            DCJOB_NEWJOB_PREFERREDSTARTTIME: 'Preferred Start Time',
            DCJOB_NEWJOB_PREFERREDSTARTTIMEINFO: 'Salesforce schedules the DC Job for execution at the specified time. Actual execution may be delayed based on service availability.',
            DCJOB_AUTOMERGE_AUTOMERGETHRESHOLD: 'Auto Merge Threshold',
            DCJOB_AUTOMERGE_AUTOMERGETEXT: 'After the job completes, all duplicate pairs with a matching percentage that is equal or higher than {0}% are automatically merged.',
            DCJOB_NEWJOB_AUTOMERGETEXT: 'After the job completes, all duplicate pairs with a matching percentage that is equal or higher than {0}% are automatically merged.',
            DCJOB_NEWJOB_AUTOCONVERTEXPLANATION: 'All duplicate pairs with a matching percentage that is equal or higher than {0}% are automatically converted.',
            DCJOB_AUTOCONVERT_AUTOCONVERTEXPLANATION: 'All duplicate pairs with a matching percentage that is equal or higher than {0}% are automatically converted.',
            DCJOB_AUTOMERGE_AUTOMERGEWARNING: 'Merging records cannot be undone.',
            DCJOB_NEWJOB_PROCESSINGOPTIONS: 'Processing Options',
            DCJOB_AUTOMERGE_PROCESSINGOPTIONS: 'Processing Options',
            DCJOB_AUTOCONVERT_PROCESSINGOPTIONS: 'Processing Options',
            DCJOB_NEWJOB_RUNONSF: 'Run on Salesforce Platform',
            DCJOB_AUTOMERGE_RUNONSF: 'Run on Salesforce Platform',
            DCJOB_AUTOCONVERT_RUNONSF: 'Run on Salesforce Platform',
            DCJOB_NEWJOB_RUNONDCLOCAL: 'Run on DC Local',
            DCJOB_AUTOMERGE_RUNONDCLOCAL: 'Run on DC Local',
            DCJOB_AUTOCONVERT_RUNONDCLOCAL: 'Run on DC Local',
            DCJOB_AUTOMERGE_SFINFO: 'Based on the number of duplicate pairs that are selected for the auto merge process, we recommend processing the job on the Salesforce platform.',
            DCJOB_AUTOCONVERT_SFINFO: 'Based on the number of duplicate pairs that are selected for the auto merge process, we recommend processing the job on the Salesforce platform.',
            DCJOB_AUTOMERGE_DCLOCALINFO: 'Based on the number of duplicate pairs that are selected for the auto merge process, we recommend processing the job on DC Local.',
            DCJOB_AUTOCONVERT_DCLOCALINFO: 'Based on the number of duplicate pairs that are selected for the auto merge process, we recommend processing the job on DC Local.',
            DCJOB_AUTOMERGE_SFPLATFORMMESSAGE: 'Run this job on the Salesforce Platform (native).',
            DCJOB_AUTOMERGE_DCLOCALMESSAGE: 'Run this job by using DC Local desktop or DC Local server.',
            DCJOB_AUTOMERGE_ADDOBJECTFILTER: 'Add {0} filter',
            DCJOB_AUTOMERGE_REMOVEOBJECTFILTER: 'Remove {0} filter',
            DCJOB_AUTOMERGE_ADDFILTERLINE: 'Add Filter Line',
            DCJOB_AUTOCONVERT_ADDFILTERLINE: 'Add Filter Line',
            DCJOB_AUTOMERGE_OBJECTFILTER: '{0} Filter',
        },
    },
    scenario: {
        DCJOB_NEWJOB_SCENARIO: 'Scenario',
        DCJOB_NEWJOB_SCENARIOINFO: 'In a cross object job, only scenarios from the matched object are available.',
        DCJOB_SCENARIOCARD_SCENARIONAME: 'Scenario Name',
        DCJOB_SCENARIOCARD_THRESHOLD: 'Threshold',
        DCJOB_SCENARIOCARD_EMPTYFIELDS: 'Empty Fields',
        fields: {
            DCJOB_SCENARIOCARD_FIELD: 'Field',
            DCJOB_SCENARIOCARD_FREQUENTWORDS: 'Frequent Words',
            DCJOB_SCENARIOCARD_MATCHINGMETHOD: 'Matching Method',
            DCJOB_SCENARIOCARD_WEIGHT: 'Weight',
        },
    },
    filter: {
        DCJOB_INFOMODAL_READMOREINFO: 'After adding a filter, the filter is numbered. Your first filter becomes Filter 1 and your second filter becomes Filter 2. You apply filter logic based on these numbered filters. Click the icon to read more.',
        DCJOB_INFOMODAL_FILTER: 'Filter',
        DCJOB_INFOMODAL_SOURCEFILTER: 'Source Filter',
        DCJOB_INFOMODAL_MATCHFILTER: 'Match Filter',
        DCJOB_INFOMODAL_AUTOMERGE_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOMERGE_GROUPFILTER: 'Auto Merge Group Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_GROUPFILTER: 'Auto Convert Group Filter',
        DCJOB_JOBPAGE_FILTERJOBS: 'Filter Jobs',
        DCJOB_JOBPAGE_NOFILTERAPPLIED: 'No filter applied.',
        addFilter: 'Add Filter',
        operators: {
            DCJOB_SCHEDULEDJOBPAGE_OR: 'OR',
            DCJOB_JOBINFO_OR: 'OR',
        },
        removeFilter: 'Remove Filter',
        DCJOB_NEWJOB_SETFILTER: 'Set Filter',
        DCJOB_NEWJOB_ALLRECORDS: 'No Filter, Process all Records',
        DCJOB_NEWJOB_COMPARERECORDSINABOVEFILTERWITH: 'Compare records in above filter with',
        DCJOB_NEWJOB_RECORDSTHATMEETCRITERIA: 'Records that meet above filter criteria',
        jobFilterFields: {
            DCJOB_JOBPAGE_STARTEDBYUSER: 'Started By User',
            DCJOB_JOBPAGE_CONTAINSFILTER: 'Contains Filter',
            DCJOB_JOBPAGE_CONTAINSAUTOMERGE: 'Contains Auto Merge',
            DCJOB_JOBPAGE_CONSTAINSAUTOCONVERT: 'Contains Auto Convert',
        },
        startedScheduledJob: '{0} is now running',
        activeScheduledJob: '{0} is now activated',
        deactivatedScheduledJob: '{0} is now deactivated',
        DCJOB_JOBPAGE_FILTERSAVED: 'Filter Saved Successfully.',
        addFilterlineLabel: 'Add Filterline',
        newFilterlinePlaceholder: 'Add Filterline',
        fieldLabel: 'Field',
        fieldPlaceholder: 'Select an Option...',
        fieldPlaceholderSearch: 'Search options...',
        operatorLabel: 'Operator',
        emptyValueLabel: 'Empty',
        emptyOptionLabel: '- none -',
        addFilterLogicLabel: 'Add Filter Logic',
        removeFilterLogicLabel: 'Remove Filter Logic',
        doneButton: 'Done',
        inputLabels: {
            Value: 'Value',
            Date: 'Date',
            Time: 'Time',
            'Start date': 'Start Date',
            'End date': 'End Date',
            'Start Time': 'Start Time',
            'End Time': 'End Time',
        },
        logic: {
            ErrorUnusedFilters: 'There is an unused filter line',
            ErrorTypo: 'There is a typo',
            ErrorBadNumber: '{0} can\'t be used in the filter logic',
            ErrorMissingRightOperand: 'Missing right hand operator',
            ErrorAmbiguousAndOr: 'Add parenthesis when using the AND + OR',
            ErrorMissingOperand: 'NOT should be followed by an operand',
            ErrorParen: 'Unexpected parenthesis',
        },
    },
    matchingMethods: {
        EQUAL: 'Exact',
        EQUAL_RANDOM: 'Exact (random order)',
        NOT_EQUAL: 'Not Equal',
        EQUAL_NULL: 'Equal to Null',
        FUZZY_PERSON: 'Person Name',
        FUZZY_COMPANY_EXTRA_STRICT: 'Company Name',
        PHONE: 'Phone Number',
        PHONE_ADVANCED: 'Phone Number Advanced',
        EMAIL_EXACT: 'Email Address',
        EMAIL: 'Email',
        DOMAIN_EXACT: 'Domain',
        DOMAIN_FUZZY: 'Domain Fuzzy',
        URL_EXACT: 'Url',
        URL_FUZZY: 'Url Fuzzy',
        PRODUCT: 'Product Number',
        POSTAL_CODE: 'Postal Code',
        PERSON_NAME: 'Fuzzy',
        FUZZY_COMPANY: 'Partial Fuzzy Light',
        FUZZY_COMPANY_STRICT: 'Partial Fuzzy Medium',
        COMPANY_NAME: 'Partial Fuzzy Heavy',
        COMPANY: 'Company',
        TEXT: 'Large Text',
        DATE_DISTANCE_DAYS: 'Date Distance in Days',
        HAS_VALUE: 'Contains Value',
    },
    frequentWords: {
        STREET: 'Street',
        COMPANY: 'Company',
        COMMON: 'Common',
        NAME: 'Person Names',
        EMAIL: 'Email',
        CUSTOM1: 'Custom 1',
        CUSTOM2: 'Custom 2',
    },
    emptyFieldOptions: {
        DEDUP50: 'Score 50%',
        DEDUP: 'Score 100%',
        SEARCH: 'Disregard',
    },
    pageNavigation: {
        PREVIOUSPAGE: 'Previous Page',
        NEXTPAGE: 'Next Page',
    },
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTSVIEW: 'Duplicate Results Overview',
    DCJOB_OVERALLJOBRESULTS_OVERALLJOBRESULTS: 'Overall Job Results',
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTS: 'Duplicate Results',
    DCJOB_OVERALLJOBRESULTS_OPENALLGROUPS: 'Open All Groups',
    DCJOB_OVERALLJOBRESULTS_CLOSEALLGROUPS: 'Close All Groups',
    DCJOB_OVERALLJOBRESULTS_SEARCHUSERS: 'Search users',
    DCJOB_OVERALLJOBRESULTS_APPLYFILTER: 'Apply Filter',
    DCJOB_OVERALLJOBRESULTS_PAIRCOUNT: 'Pair Count',
    DCJOB_OVERALLJOBRESULTS_RECORDCOUNT: 'Record Count',
    DCJOB_OVERALLJOBRESULTS_GROUP: 'Group',
    DCJOB_OVERALLJOBRESULTS_MINSCORE: 'Min. Score',
    DCJOB_OVERALLJOBRESULTS_MAXSCORE: 'Max. Score',
    DCJOB_OVERALLJOBRESULTS_AVGSCORE: 'Avg. Score',
    DCJOB_OVERALLJOBRESULTS_ONEERROR: '1 error',
    DCJOB_OVERALLJOBRESULTS_MERGESELECTEDRECORDS: 'Merge Selected Records',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTION: 'Discard Selection',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTIONFOREVER: 'Discard Selection Forever',
    DCJOB_OVERALLJOBRESULTS_DELETINGRECORDSNOTUNDOABLE: 'Deleting records cannot be undone.',
    DCJOB_OVERALLJOBRESULTS_MERGEPAIR: 'Merge Pair',
    DCJOB_OVERALLJOBRESULTS_QUICKMERGEPAIR: 'Quick Merge Pair',
    DCJOB_OVERALLJOBRESULTS_CONVERTPAIR: 'Convert Pair',
    DCJOB_OVERALLJOBRESULTS_QUICKCONVERTPAIR: 'Quick Convert Pair',
    DCJOB_OVERALLJOBRESULTS_AREYOUSUREYOUWANTTODELETE: 'Are you sure you want to delete [[insertHTMLWithLink]] from Salesforce?',
    DCJOB_OVERALLJOBRESULTS_DELETERECORD: 'Delete Record',
    DCJOB_OVERALLJOBRESULTS_RECORD: 'Record',
    DCJOB_OVERALLJOBRESULTS_SELECTANOPTION: 'Select an Option...',
    DCJOB_OVERALLJOBRESULTS_SEARCHOPTIONS: 'Search options...',
    validation: {
        required: 'This field is required',
        max: 'This field has to be less than {max} characters',
        invalid_cron_format: 'Invalid Cron String. Please check the format.',
        invalid_seconds_or_minutes: 'Invalid Cron String. Please only use numeric values for seconds and minutes.',
        invalid_day_of_week_and_day_of_month_combination: 'Invalid Cron String. Please only specify day of week or day of month.',
    },
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWPAIRVIEW: 'Switch to Pair View',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWGROUPVIEW: 'Switch to Group View',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFROMJOB: 'Discard Group from Job',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPINJOB: 'Discard Group in this Job',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFOREVER: 'Discard Group forever',
    DCJOB_OVERALLJOBRESULTS_FILTER_JOBTYPE: 'Job Type',
    DCJOB_OVERALLJOBRESULTS_FILTER_OWNER: '{objectName} Owner',
    DCJOB_OVERALLJOBRESULTS_FILTER_RECORDTYPE: '{objectName} Record Type',
    DCJOB_OVERALLJOBRESULTS_FILTER_PREDEFINED: '{objectName} Predefined Filter',
    DCJOB_OVERALLJOBRESULTS_FILTER_FIELD: '{objectName} {fieldName}',
    DCENTRY_ERROR_OPTION_MUST_BE_SELECTED: 'An option must be selected.',
    DCENTRY_ERROR_REQUIRED: 'Complete this field.',
    DCENTRY_ERROR_INVALID_NUMERIC_RANGE: '{0}: value outside of valid range on numeric field: {1}',
    DCENTRY_ERROR_INVALID_TEXT_RANGE: '{0}: value outside of valid range on text field: {1}',
    DCENTRY_ENTER_VALID_VALUE: 'Enter a valid value',
    DCENTRY_PICKLIST_NONE: 'None',
    DCENTRY_JANUARY: 'January',
    DCENTRY_FEBRUARY: 'February',
    DCENTRY_MARCH: 'March',
    DCENTRY_APRIL: 'April',
    DCENTRY_MAY: 'May',
    DCENTRY_JUNE: 'June',
    DCENTRY_JULY: 'July',
    DCENTRY_AUGUST: 'August',
    DCENTRY_SEPTEMBER: 'September',
    DCENTRY_OCTOBER: 'October',
    DCENTRY_NOVEMBER: 'November',
    DCENTRY_DECEMBER: 'December',
    DCENTRY_SUNDAY: 'Sunday',
    DCENTRY_MONDAY: 'Monday',
    DCENTRY_TUESDAY: 'Tuesday',
    DCENTRY_WEDNESDAY: 'Wednesday',
    DCENTRY_THURSDAY: 'Thursday',
    DCENTRY_FRIDAY: 'Friday',
    DCENTRY_SATURDAY: 'Saturday',
    DCENTRY_TODAY: 'Today',
    DCENTRY_MULTISELECT_AVAILABLE: 'Available',
    DCENTRY_MULTISELECT_CHOSEN: 'Chosen',
    DCENTRY_LOOKUP_RECENT_OBJECTS: 'Recent {0}',
    DCENTRY_LOOKUP_PLACEHOLDER: 'Search {0}...',
    DCENTRY_LOOKUP_INPUT_SELECT_ERROR: 'Select an option from the picklist or remove the search term.',
    DCENTRY_FORMULA_FIELD_CALCULATE_MESSAGE: 'This field is calculated upon save',
    DCENTRY_HEADER_NEW: 'New {0}',
    DCENTRY_HEADER_EDIT: 'Edit {0}',
    DCENTRY_FOOTER_CANCEL_BUTTON: 'Cancel',
    DCENTRY_FOOTER_SAVE_BUTTON: 'Save',
    DCENTRY_FOOTER_SAVE_ANYWAY_BUTTON: 'Ignore and Save',
    DCENTRY_FOOTER_SAVENEW_BUTTON: 'Save & New',
    DCENTRY_FOOTER_SAVENEW_ANYWAY_BUTTON: 'Ignore and Save & New',
    DCENTRY_FOOTER_ERROR_HEADER: 'We hit a snag.',
    DCENTRY_FOOTER_ERROR_REVIEW_ERRORS: 'Review the errors on this page.',
    DCENTRY_FOOTER_ERROR_REVIEW_FIELDS: 'Review the following fields',
    DCENTRY_ERROR_LAYOUT_LOAD: 'Failed to retrieve the page layout for {0} object.',
    RVENTRY_ERROR_LAYOUT_INCOMPLETE: 'Missing properties in the page layout for {0} object.',
    DCENTRY_ERROR_SETTINGS_LOAD: 'Failed to retrieve the settings for {0} object',
    DCENTRY_HEADER_WARNING_DUPLICATES_FOUND_TABS: 'Search duplicates tabs',
    DCENTRY_HEADER_WARNING_DUPLICATES_FOUND: 'Duplicates Found - Please review them below',
    DCENTRY_HEADER_WARNING_NO_DUPLICATES_FOUND: 'No duplicates found',
    DCENTRY_FOOTER_WARNING_DUPLICATES_FOUND_HEADER: 'Duplicates Found ({0})',
    DCENTRY_FOOTER_WARNING_DUPLICATES_FOUND_BODY: 'Duplicate Check has found potential duplicate records. Review them at the top of the page',
    DCENTRY_FOOTER_ERROR_DUPLICATES_FOUND_HEADER: 'Duplicates Found - Insert Blocked',
    DCENTRY_FOOTER_ERROR_DUPLICATES_FOUND_BODY: 'In this organization, you are not allowed to insert a duplicate record',
    DCENTRY_DUPLICATE_COLUMN_SCORE: 'Score',
    DCENTRY_NOSCENARIO_WARNING: 'Tried to search for duplicates but no scenarios were configured or applied',
    DCENTRY_URLADDRESSABLE_DEFAULT_VALUES_ERROR: 'Could not set default values for this record',
    DCENTRY_SUCCESSFULL_SAVE: '{0} "{1}" was saved.'
};

