export default {
    DCJOB_INFOMODALTAB_GENERALINFO: 'Información General',
    DCJOB_INFOMODALTAB_SELECTEDRECORDS: 'Registros Seleccionados',
    DCJOB_INFOMODALTAB_APPLIEDSCENARIOS: 'Escenarios aplicados',
    DCJOB_INFOMODALTAB_UNPROCESSEDRESULTS: 'Resultados no procesados',
    DCJOB_INFOMODALTAB_DUPLICATERESULTS: 'Duplicados Encontrados',
    DCJOB_INFOMODALTAB_CONVERTLOG: 'Registro de Conversión',
    DCJOB_INFOMODALTAB_MERGELOG: 'Registro de Combinación',
    DCJOB_OBJECT_USERS: 'Usuarios',
    DCJOB_OBJECT_GROUPS: 'Grupos',
    DCJOB_OBJECT_QUEUES: 'Colas',
    DCJOB_BUTTON_CANCEL: 'Cancelar',
    DCJOB_BUTTON_CALCULATING: 'Calculando recuento de registros',
    DCJOB_BUTTON_TAKINGLONGER: 'El cálculo está tardando un poco más...',
    DCJOB_BUTTON_NEXTWITHLIMIT: 'Siguiente con Límite',
    DCJOB_BUTTON_ABORTING: 'Interrumpiendo',
    DCJOB_BUTTON_REFRESH: 'Actualizar',
    DCJOB_LINK_READMORE: 'Más información',
    DCJOB_SHAREMODAL_SHAREMETHOD: 'Compartir método',
    DCJOB_SHAREMODAL_LINK: 'Enlace',
    DCJOB_SHAREMODAL_COPY: 'Copiar al portapapeles',
    DCJOB_SHAREMODAL_COPIED: 'Copiado en el portapapeles',
    DCJOB_SHAREMODAL_SHAREJOB: 'Compartir Trabajo',
    DCJOB_SHAREMODAL_DIRECTLINK: 'Enlace directo',
    DCJOB_SHAREMODAL_TASK: 'Crear una tarea',
    DCJOB_SHAREMODAL_EMAIL: 'Enviar Correo Electrónico',
    DCJOB_SHAREMODAL_RECIPIENTS: 'Destinatarios',
    DCJOB_SHAREMODAL_SUBJECT: 'Asunto',
    DCJOB_SHAREMODAL_TEXT: 'Texto',
    DCJOB_SHAREMODAL_ASSIGNTO: 'Asignar a',
    DCJOB_SHAREMODAL_STATUS: 'Estado',
    DCJOB_SHAREMODAL_DUEDATE: 'Fecha de Vencimiento',
    DCJOB_SHAREMODAL_DESCRIPTION: 'Descripción',
    DCJOB_SHAREMODAL_PRIORITY: 'Prioridad',
    DCJOB_SHAREMODAL_CREATETASK: 'Crear Tarea',
    DCJOB_SHAREMODAL_TASKSUCCESS: 'Tarea creada con éxito',
    DCJOB_SHAREMODAL_EMAILSUCCESS: 'Correo enviado',
    DCJOB_SHAREMODAL_SHAREINFO: 'Para compartir, la variable {0} es necesaria. No la elimine del campo de texto.',
    DCJOB_PLACEHOLDER_SEARCH: 'Buscar',
    DCJOB_PLACEHOLDER_SUBJECT: 'Por favor, introduce un asunto',
    DCJOB_EDITJOB_SCHEDULE: 'Programar',
    DCJOB_NEWJOB_RUNONPLAUTICLOUD: 'Ejecutar en la Nube de Plauti',
    DCJOB_NEWJOB_PLAUTICLOUDPROCESSDESCRIPTION: 'Ejecute este trabajo usando la Nube de Plauti, una nueva opción de procesamiento ofrecida por Plauti.',
    DCJOB_NEWJOB_FILTERLOGIC: 'Lógica de Filtro',
    DCJOB_NEWJOB_FILTERLOGICDESCRIPTION: 'Después de añadir un filtro, el filtro está numerado. El primer filtro será el filtro 1, el segundo será el filtro 2, etc. Aplica la lógica del filtro basada en estos filtros numerados.',
    DCJOB_NEWJOB_ADDSCHEDULE: 'Añadir Programación',
    DCJOB_NEWJOB_AUTOCONVERT: 'Auto convertir',
    DCJOB_NEWJOB_AUTOMERGE: 'Auto Combinar',
    DCJOB_NEWJOB_ADDAUTOCONVERT: 'Añadir Auto Convertir',
    DCJOB_NEWJOB_ADDAUTOMERGE: 'Añadir Auto Combinar',
    DCJOB_NEWJOB_AUTOCONVERTTHRESHOLD: 'Umbral de Auto Convertir',
    DCJOB_NEWJOB_AUTOMERGETHRESHOLD: 'Umbral de Auto Combinar',
    DCJOB_NEWJOB_SCHEDULEDESCRIPTION: 'Programa esta trabajo para que se ejecute con una frecuencia y en un horario específicos.',
    DCJOB_NEWJOB_AUTOMERGEDESCRIPTION: 'Añadir una puntuación mínima para combinar automáticamente los registros duplicados justo después de completar el trabajo.',
    DCJOB_NEWJOB_AUTOCONVERTDESCRIPTION: 'Añadir una puntuación mínima para convertir automáticamente registros duplicados justo después de completar el trabajo.',
    DCJOB_NEWJOB_REMOVEAUTOMERGE: 'Quitar Auto Combinar',
    DCJOB_NEWJOB_REMOVEAUTOCONVERT: 'Eliminar Auto Convertir',
    DCJOB_NEWJOB_AUTOCONVERTWARNING: 'No se puede deshacer la conversión de registros.',
    DCJOB_NEWJOB_AUTOMERGEWARNING: 'No se pueden deshacer los registros combinados.',
    DCJOB_NEWJOB_CONVERTOWNERINFO: 'Los clientes potenciales se convertirán en la cuenta de destino como un nuevo contacto. Decide cuál usuario debe ser el propietario de los nuevos contactos.',
    DCJOB_NEWJOB_CONVERTSTATUS: 'Estado después de la conversión',
    DCJOB_NEWJOB_CONVERTOWNER: 'Propietario de nuevos registros de contacto',
    DCJOB_NEWJOB_LEADOWNER: 'Propietario actual del prospecto',
    DCJOB_NEWJOB_ACCOUNTOWNER: 'Propietario actual de la cuenta',
    DCJOB_NEWJOB_LOOKUPUSER: 'Buscar usuario',
    DCJOB_NEWJOB_SFPROCESSDESCRIPTION: 'Ejecutar este trabajo en la Plataforma de Salesforce sin ninguna transferencia de datos.',
    DCJOB_NEWJOB_DCLOCALPROCESSDESCRIPTION: 'Ejecuta esta trabajo utilizando DC Local desktop o DC Local server.',
    DCJOB_NEWJOB_RECORDLIMITREACHED: 'Límite de registros con licencia alcanzado',
    DCJOB_NEWJOB_RECORDLIMITDESCRIPTION: 'Basándose en el número de registros actualmente seleccionados, este trabajo alcanzará el límite de registros permitidos por la licencia. Como resultado, no todos los registros seleccionados serán analizados en busca de duplicados.',
    DCJOB_NEWJOB_NORECORDSSELECTED: 'No hay registros seleccionados.',
    DCJOB_NEWJOB_SELECTSCENARIO: 'Por favor, selecciona al menos un escenario',
    DCJOB_NEWJOB_NOSCENARIO: 'No se encontraron escenarios para {0}',
    DCJOB_NEWJOB_NOSELECTIONDESCRIPTION: 'Actualmente no hay registros que cumplan con tus criterios de filtro. Considera cambiar tu filtro. Todavía puedes proceder a configurar un trabajo programado.',
    DCJOB_NEWJOB_SFRECOMMENDATION: 'Basándose en el número de registros seleccionados actualmente, recomendamos procesar el trabajo en la Plataforma de Salesforce. A partir de 15.000 registros, se recomienda el uso de DC Local para un mejor rendimiento.',
    DCJOB_NEWJOB_DCLOCALRECOMMENDATION: 'Basándonos en el número de registros seleccionados actualmente (más de 15.000 registros), recomendamos procesar el trabajo usando DC Local para un mejor rendimiento.',
    DCJOB_NEWJOB_FILTERNOTFOUND: 'La opción de filtro {0} seleccionada "{1}" ya no está disponible.',
    DCJOB_AUTOCONVERT_DCLOCALMESSAGE: 'Ejecute este trabajo usando DC Local desktop o DC Local server. Actualmente no está disponible para Auto Convertir.',
    DCJOB_AUTOCONVERT_CONVERTSTATUS: 'Estado después de la conversión',
    DCJOB_AUTOCONVERT_SELECTEDRECORDS: 'Número de registros seleccionados para Auto Convertir',
    DCJOB_AUTOCONVERT_NEWCONTACTOWNER: 'Propietario de nuevos registros de Contacto',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE: 'Reconozco que iniciar este trabajo de Auto Convertir convertirá registros duplicados {0}, y que la conversión de los registros no se podrán deshacer',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'Reconozco que iniciar este trabajo de Auto Convertir convertirá registros duplicados, y que la conversión de los registros no se podrán deshacer',
    DCJOB_AUTOCONVERT_NORECORDSSELECTED: 'Actualmente no hay registros que cumplan con tus criterios de filtro. Considera cambiar tu filtro.',
    DCJOB_AUTOCONVERT_TRIALWARNING: 'Auto Convertir está limitada a 20 registros debido a tu licencia de prueba. Actualiza a una licencia de pago para eliminar esta limitación.',
    DCJOB_AUTOMERGE_FILTERLOGIC: 'Lógica de Filtro',
    DCJOB_AUTOMERGE_FILTERLOGICDESCRIPTION: 'Después de añadir un filtro, éste se numera. El primer filtro será el filtro 1, el segundo será el filtro 2, etc. Aplica la lógica del filtro basada en estos filtros numerados.',
    DCJOB_AUTOMERGE_SELECTEDRECORDS: 'Número de registros seleccionados para Auto Combinar',
    DCJOB_AUTOMERGE_SELECTEDDUPLICATEPAIRS: 'Número de pares duplicados seleccionados para Auto Combinar',
    DCJOB_AUTOMERGE_TRIALWARNING: 'Auto Combinar está limitada a 20 registros debido a tu licencia de prueba. Actualiza a una licencia de pago para eliminar la limitación.',
    DCJOB_OVERVIEW_PROCESSEDBY: 'Procesado por',
    DCJOB_OVERVIEW_DELETINGJOB: 'Eliminando trabajo',
    DCJOB_OVERVIEW_JOBABORTED: 'Trabajo cancelado',
    DCJOB_ACCESS_CURRENTUSERNOACCESS: 'El usuario actual no tiene acceso a las clases requeridas',
    DCJOB_ACCESS_REACHOUTTOADMINISTRATOR: 'Por favor, contacta a tu Administrador de Salesforce',
    DCJOB_ACCESS_DEACTIVATEDCJOBBETA: 'Desactivar DC Job Beta',
    DCJOB_ACCESS_YOUHAVENOACCESS: 'No tienes acceso a la clase Apex mencionada',
    DCJOB_FILTER_JOBTYPE: 'Tipo de trabajo',
    DCJOB_FILTER_DUPCHECKJOB: 'Duplicar Trabajo',
    DCJOB_FILTER_DUPCHECKLOCAL: 'DC Local / Nube de Plauti',
    DCJOB_FILTER_UNIQUEBULKAPIINSERT: 'Insertar API única/importación masiva',
    DCJOB_FILTER_WEBTOLEAD: 'Web a Candidato',
    DCJOB_FILTER_SETFORMERGE: 'Establecer para Combinación',
    DCJOB_FILTER_SINGLEAPIINSERT: 'Insertar API única',
    DCJOB_FILTER_FLOW: 'Flujo',
    DCJOB_FILTER_ABORTED: 'Interrumpido(s)',
    DCJOB_FILTER_FAILED: 'Fallido',
    DCJOB_FILTER_COMPLETED: 'Finalizado',
    DCJOB_FILTER_HOLDING: 'En espera',
    DCJOB_FILTER_PROCESSING: 'En proceso',
    DCJOB_FILTER_INCAMPAIGN: 'En Campaña',
    DCJOB_FILTER_FILTER: 'Filtro',
    DCJOB_JOBCARD_PROCESSEDWITHDCLOCAL: 'Trabajo local de DC',
    DCJOB_JOBCARD_PROCESSEDWITHCLOUD: 'Trabajo en la nube de Plauti',
    DCJOB_JOBPAGE_APEXJOBID: 'ID del Trabajo Apex',
    ONBOARDING_NEXT: 'Siguiente',
    ONBOARDING_BACK: 'Atrás',
    ONBOARDING_FINISH: 'Terminar',
    ONBOARDING_DOCUMENTATION: 'Documentación',
    ONBOARDING_WATCH_VIDEO: 'Ver vídeo',
    ONBOARDING_GETTING_STARTED: 'Comenzando con Duplicate Check',
    ONBOARDING_THANK_YOU_FOR_INSTALLING: 'Gracias por instalar Duplicate Check',
    ONBOARDING_RUNNING_A_DC_JOB: 'Ejecutando un Trabajo de DC',
    ONBOARDING_SETUP_DUPLICATE_PREVENTION: 'Configurar prevención de duplicados',
    ONBOARDING_LEARN_ABOUT_DCLIVE: 'Aprende sobre DC Live',
    ONBOARDING_HOW_TO_CONFIGURE_DC: 'Cómo configurar Duplicate Check',
    ONBOARDING_OPTIONS_FOR_AUTOMATION: 'Opciones para la automatización',
    ONBOARDING_INTEGRATION: 'Integración',
    ONBOARDING_CUSTOMISATION: 'Personalización',
    ONBOARDING_GET_STARTED: '¡Comencemos!',
    ONBOARDING_NOTIFICATION_JOB_STARTED: 'Trabajo de DC iniciado en {0}',
    ONBOARDING_NOTIFICATION_VIEW_PROGRESS: 'Haz clic para ver el progreso en la Vista General del Trabajo de DC',
    ONBOARDING_JOB_INFO_CARD_OPEN_RESULTS: 'Abrir resultados',
    ONBOARDING_JOB_INFO_CARD_STATUS: 'Estado',
    ONBOARDING_JOB_INFO_CARD_RESULT: 'Resultado',
    ONBOARDING_INTRO_THANK_YOU_FOR_INSTALLING: '¡Gracias por instalar Duplicate Check!',
    ONBOARDING_INTRO_OPENING_MESSAGE: '¡Hola Trailblazer! Nos complace ver que has instalado Duplicate Check para Salesforce. Estás a solo unos pasos de tener un entorno de Salesforce libre de duplicados que cuenta con datos precisos y confiables, lo que conduce a una mejor toma de decisiones, mayor productividad y una mayor satisfacción del cliente.',
    ONBOARDING_INTRO_START_LOOKING_FOR_DUPLICATES: 'Nos tomamos la libertad de empezar a buscar algunos duplicados…',
    ONBOARDING_INTRO_LOOKING_FOR_DUPLICATE_MESSAGE: 'Nos tomamos la libertad de empezar un trabajo rápido en mil registros {0} para que podamos mostrarte lo fácil que es encontrar esos registros duplicados en el objeto {0}. Siéntete libre de consultar el resultado en una nueva pestaña haciendo clic en “Abrir resultados”.',
    ONBOARDING_RUN_JOB_OPENING_MESSAGE: 'El "Trabajo de DC" es el punto de partida para todos tus esfuerzos de deduplicación. Para encontrar todos los registros duplicados en cualquier objeto de Salesforce, puedes ejecutar un "Trabajo de Verificación de Duplicados", también conocido como "Trabajo de DC".',
    ONBOARDING_RUN_JOB_START_FIRST_JOB_HELP: '¡Déjanos ayudarte a comenzar tus primeros trabajos!',
    ONBOARDING_RUN_JOB_START_NOW: 'Empezar ahora',
    ONBOARDING_RUN_JOB_STARTED: 'Iniciado',
    ONBOARDING_RUN_JOB_LEAD_TITLE: 'Ejecutar un trabajo con potenciales',
    ONBOARDING_RUN_JOB_LEAD_DESCRIPTION: 'Encuentra duplicados basados en la comparación de Primer Nombre, Apellido, Email, Compañía y Teléfono.',
    ONBOARDING_RUN_JOB_CONTACT_TITLE: 'Ejecutar un trabajo en Contactos',
    ONBOARDING_RUN_JOB_CONTACT_DESCRIPTION: 'Encuentre duplicados basados en la comparación de Primer Nombre, Apellido, Correo Electrónico y Teléfono.',
    ONBOARDING_RUN_JOB_ACCOUNT_TITLE: 'Ejecutar un trabajo en Cuentas',
    ONBOARDING_RUN_JOB_ACCOUNT_DESCRIPTION: 'Encuentra duplicados basados en comparar Nombre, Ciudad de Facturación y Teléfono.',
    ONBOARDING_RUN_JOB_THINGS_TO_KNOW: 'Cosas por saber acerca de los trabajos de DC',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_FEATURE: 'función objeto cruzado',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_MESSAGE: 'Con el {0}, compara registros en cualquier objeto con registros en cualquier otro objeto',
    ONBOARDING_RUN_JOB_PLAUTI_CLOUD: 'Nube de Plauti',
    ONBOARDING_RUN_JOB_LOCAL: 'DC Local',
    ONBOARDING_RUN_JOB_PROCESSING: 'Decide dónde procesar un trabajo de DC - completamente dentro de Salesforce, o externamente a través de {0} o {1}',
    ONBOARDING_RUN_JOB_MANUALLY: 'manualmente',
    ONBOARDING_RUN_JOB_AUTOMATICALLY: 'automáticamente',
    ONBOARDING_RUN_JOB_MERGE_OR_CONVERT: 'Elige combinar o convertir {0} o {1}',
    ONBOARDING_RUN_JOB_SCHEDULE_A_JOB: 'Programar un trabajo',
    ONBOARDING_RUN_JOB_SCHEDULE_MESSAGE: '{0} para ejecutarse con una frecuencia y en un horario que decidas',
    ONBOARDING_PREVENTION_DUPLICATE_PREVENTION: 'Prevención de Duplicados',
    ONBOARDING_PREVENTION_OPENING_MESSAGE: 'A continuación, encuentra las diferentes maneras en las que un registro puede entrar a Salesforce y ve cómo DC puede asegurarse de que sean detectados y manejados los duplicados.',
    ONBOARDING_PREVENTION_MANUAL_INSERT: 'Inserción manual',
    ONBOARDING_PREVENTION_MANUAL_INSERT_DESCRIPTION: 'A pesar de tomar todas las precauciones posibles, aún existe la posibilidad de que se introduzcan registros duplicados en Salesforce por la entrada manual de los usuarios finales. Duplicate Check ofrece una función destacada que puedes optar por implementar, conocida como "DC Entry". Para obtener más información, te invitamos a consultar nuestra documentación.',
    ONBOARDING_PREVENTION_IMPORT: 'Importar',
    ONBOARDING_PREVENTION_IMPORT_DESCRIPTION: 'Al importar registros mediante el Data Loader o el Asistente de Importación de Datos, los duplicados pueden infiltrarse en tu entorno de Salesforce. Utilizando Duplicate Check, un duplicado se marca durante la importación, tras lo cual tienes la opción de combinar los registros. Al no bloquear la entrada del duplicado, tienes la oportunidad de conservar la información más actualizada.',
    ONBOARDING_PREVENTION_INTEGRATIONS: 'Integraciones (Salesforce API)',
    ONBOARDING_PREVENTION_INTEGRATIONS_DESCRIPTION: 'La implementación promedio de Salesforce está conectada a una docena de herramientas externas que se comunican a través de la API de Salesforce, generando una gran cantidad de nuevos registros diariamente. Duplicate Check puede monitorear el canal de la API de Salesforce y detectar cualquier duplicado en el momento de su entrada.',
    ONBOARDING_PREVENTION_WEBFORMS: 'Formularios web',
    ONBOARDING_PREVENTION_WEBFORMS_DESCRIPTION: 'Si tienes formularios web vinculados a tu entorno de Salesforce, probablemente estés familiarizado con el problema de recibir registros duplicados. Al utilizar Duplicate Check, adquieres la capacidad de detectar duplicados procedentes de cualquier formulario web y procesar el duplicado en tiempo real.',
    ONBOARDING_DCLIVE_OPENING_MESSAGE: 'En Plauti, creemos firmemente que la calidad de los datos es una responsabilidad que incumbe a toda la organización. Por este motivo, hemos desarrollado DC Live.',
    ONBOARDING_DCLIVE_DESCRIPTION: 'DC Live es un componente adaptable que se puede integrar en el diseño de página de cualquier objeto en Salesforce, haciéndolo accesible para todos los usuarios. Al abrir un registro, DC Live identifica y muestra de manera inmediata los posibles duplicados asociados a ese registro específico.',
    ONBOARDING_DCLIVE_EMPOWER_END_USERS: 'Empodera a los usuarios finales ofreciéndoles visibilidad sobre la calidad de sus datos y permíteles decidir si desean {0} o solo {1}.',
    ONBOARDING_DCLIVE_MERGE_RECORDS_THEMSELVES: 'combinar los registros por sí mismos',
    ONBOARDING_DCLIVE_FLAG_FOR_ADMIN: 'marcarlos para un administrador',
    ONBOARDING_DCLIVE_HOW_TO_CONFIGURE: 'Cómo configurar DC Live',
    ONBOARDING_CONFIGURE_OPENING_MESSAGE: 'Una de las fortalezas de Duplicate Check reside en su capacidad para configurarse de manera que se ajuste perfectamente a tu implementación única de Salesforce. Para maximizar los beneficios de la herramienta, es crucial que te familiarices con los siguientes aspectos.',
    ONBOARDING_CONFIGURE_SCENARIOS_SEARCH_INDEX: 'Escenarios e índice de búsqueda',
    ONBOARDING_CONFIGURE_SCENARIO_EXPLANATION: 'Un escenario dentro de Duplicate Check actúa de manera análoga a las "reglas de coincidencia" en Salesforce, estableciendo el criterio para la comparación de registros y definiendo qué constituye un duplicado. Para optimizar el uso de esta herramienta, sugerimos explorar en profundidad sus funcionalidades y opciones de configuración.',
    ONBOARDING_CONFIGURE_SEARCH_INDEX_EXPLANATION: 'Para garantizar el máximo rendimiento de un escenario, es crucial activar y establecer el Índice de Búsqueda. Duplicate Check se apoya en este índice para localizar registros duplicados de acuerdo con el escenario establecido. La ausencia de un Índice de Búsqueda adecuado impide la identificación completa de los duplicados.',
    ONBOARDING_CONFIGURE_MERGE_RULES: 'Reglas de Combinación',
    ONBOARDING_CONFIGURE_MERGE_RULES_EXPLANATION: 'Al combinar registros dentro de un objeto, Duplicate Check recurre a las Reglas de Combinación para seleccionar un registro principal y determinar qué campos se conservarán en dicho registro principal. Las Reglas de Combinación también establecen qué campos se preseleccionan en la página de combinación manual y estas reglas se aplican al realizar una combinación automática. Descubre cómo configurar las Reglas de Combinación.',
    ONBOARDING_AUTOMATION_OPENING_MESSAGE: 'Siendo nativo de Salesforce, Duplicate Check ofrece una detección y procesamiento de duplicados en tiempo real de primer nivel.',
    ONBOARDING_AUTOMATION_DC_LEVEL_OFFER: 'Duplicate Check ofrece diferentes niveles de automatización',
    ONBOARDING_AUTOMATION_EXPLANATION: 'Existen distintos niveles de automatización, que van desde procesos operados manualmente hasta procedimientos completamente automatizados. Infórmate más sobre la automatización y elige la opción que mejor se adapte a tus necesidades.',
    ONBOARDING_AUTOMATION_AUDIT_LOG: 'Registro de Auditoría',
    ONBOARDING_AUTOMATION_AUDIT_LOG_DESCRIPTION: 'Todas las actividades de combinación o conversión, ya sea realizadas manual o automáticamente, pueden ser rastreadas en el registro de auditoría. Sin embargo, para que los registros se almacenen, es necesario habilitar previamente el registro de auditoría, lo cual conlleva un consumo adicional de espacio de almacenamiento.',
    ONBOARDING_AUTOMATION_DIRECT_PROCESSING: 'Procesamiento directo',
    ONBOARDING_INTEGRATION_OPENING_MESSAGE: 'Has elegido Salesforce debido a su flexibilidad para integrar todos tus procesos comerciales. Nuestros complementos de Apex, Acciones de Flujo, API y complementos de SFDX aseguran que la deduplicación se integre perfectamente con tus procesos existentes.',
    ONBOARDING_INTEGRATION_APEX_API: 'Duplicate Check API de Apex',
    ONBOARDING_INTEGRATION_APEX_API_DESCRIPTION: 'Duplicate Check proporciona una API de Apex que te permite implementar todas las características de DC en tus propios proyectos de Apex. Esto incluye encontrar registros duplicados utilizando el motor de búsqueda de DC, combinar y convertir, pero también te permite exportar conjuntos de configuración de DC a través de la API.',
    ONBOARDING_INTEGRATION_REST_API: 'API Rest de Duplicate Check',
    ONBOARDING_INTEGRATION_REST_API_DESCRIPTION: 'Duplicate Check ofrece una API REST que se puede utilizar para buscar o insertar/modificar registros en Salesforce a través de la API de Datos. La API de Datos REST te permite crear registros sin generar duplicados. Cuando se agrega un registro a través de la API de Datos, se compara directamente con todos los registros existentes en Salesforce. Si existen duplicados, se actualizará el registro existente en lugar de crear un registro duplicado.',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS: 'Acciones de Flujo de Duplicate Check',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS_DESCRIPTION: 'Duplicate Check ofrece la mayoría de sus funciones en forma de Acciones de Flujo. Gracias a esto, obtienes la capacidad de implementar todas las funciones relacionadas con la prevención de duplicados, combinación, conversión y más, en cualquier Flujo de Salesforce.',
    ONBOARDING_CUSTOMISATION_OPENING_MESSAGE: 'Has elegido Salesforce debido a su flexibilidad para integrar todos tus procesos comerciales. Nuestros complementos de Apex, Acciones de Flujo, API y complementos de SFDX aseguran que la deduplicación se integre perfectamente con tus procesos existentes.',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS: 'Plugins de Duplicate Check',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS_DESCRIPTION: 'Entendemos que cada negocio tiene procesos muy específicos y puede resultar difícil encontrar una herramienta que se adapte a requisitos complicados. Utiliza los plugins que ofrece Duplicate Check si deseas realizar cambios en la funcionalidad predefinida.',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS: 'Plugins SFDX',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS_DESCRIPTION: 'Los complementos de SFDX permiten a los desarrolladores automatizar tareas relacionadas con las licencias de Duplicate Check, así como las configuraciones de Duplicate Check. Por ejemplo, si has creado un pipeline con diferentes entornos de preparación, puedes automatizar la sincronización de la configuración de Duplicate Check para que sea la misma en todos los entornos.',
    ONBOARDING_GET_STARTED_A_LOT_OF_INFO: 'Es mucha información, ¿cierto?',
    ONBOARDING_GET_STARTED_OPENING_MESSAGE: 'Ahora tienes conocimientos básicos sobre lo que Duplicate Check puede hacer. Sabemos que es mucha información para asimilar. Estás listo para comenzar tu camino hacia un entorno de Salesforce libre de duplicados, con todas las increíbles ventajas que proporcionará. ¡Adelante y buena suerte en tu viaje.',
    ONBOARDING_GET_STARTED_FEELING_LOST: '¿Te sientes perdido? Siéntete libre de programar una sesión personalizada con uno de nuestros expertos.',
    ONBOARDING_GET_STARTED_SCHEDULE_CALL: '¡Programa una llamada con uno de nuestros expertos!',
    ONBOARDING_GET_STARTED_FLYING_START: '¿Deseas comenzar rápidamente a implementar Duplicate Check para tu organización? No dudes en programar una llamada con uno de nuestros expertos, ¡totalmente gratuita! Estaremos encantados de guiarte en la exploración y configuración de Duplicate Check.',
    ONBOARDING_GET_STARTED_SCHEDULE_A_CALL: 'Programar una llamada',
    ONBOARDING_GET_STARTED_INTERESTING_LINKS: 'Enlaces interesantes',
    ONBOARDING_GET_STARTED_SCHEDULE_PRODUCT_EXPERT: 'Programar una llamada con un experto',
    ONBOARDING_GET_STARTED_KNOWLEDGEBASE: 'Base de conocimientos',
    ONBOARDING_GET_STARTED_HOWTO_VIDEOS: 'Videotutoriales',
    ONBOARDING_GET_STARTED_GUIDE: 'Guía de inicio',
    ONBOARDING_GET_STARTED_CONTACT_SUPPORT: 'Contactar Soporte',
    general: {
        DCJOB_AUTOCONVERT_LEARNMORE: 'Más Información',
        DCJOB_AUTOMERGE_LEARNMORE: 'Más Información',
        DCJOB_NEWJOB_LEARNMORE: 'Más Información',
        DCJOB_AUTOMERGE_SPEED: 'Velocidad',
        DCJOB_NEWJOB_SPEED: 'Velocidad',
        DCJOB_NEWJOB_MEDIUM: 'medio',
        DCJOB_AUTOMERGE_MEDIUM: 'medio',
        DCJOB_NEWJOB_RECOMMENDED: 'Recomendado',
        DCJOB_AUTOMERGE_RECOMMENDED: 'Recomendado',
        DCJOB_AUTOCONVERT_RECOMMENDED: 'Recomendado',
        DCJOB_DELETEMODAL_ALLTIME: 'En todo momento',
        DCJOB_DELETEMODAL_SETDATE: 'Fijar fecha',
        DCJOB_DELETEMODAL_SETDATERANGE: 'Establecer rango de fecha',
        DCJOB_DELETEMODAL_FROM: 'De',
        DCJOB_DELETEMODAL_UNTIL: 'Hasta',
        DCJOB_DELETEMODAL_TYPE: 'Tipo',
        DCJOB_DELETEMODAL_DATE: 'Fecha',
        DCJOB_JOBPAGE_OBJECT: 'Objeto',
        DCJOB_SCHEDULEDJOBPAGE_OBJECT: 'Objeto',
        DCJOB_SCHEDULEDJOBPAGE_NOTAPPLICABLE: 'N/A',
        DCJOB_SCHEDULEDJOBPAGE_NOME: 'Nombre',
        DCJOB_SCHEDULEDJOBPAGE_FREQUENCYANDTIME: 'Frecuencia y Hora',
        DCJOB_SCHEDULEDJOBPAGE_STATUS: 'Estado',
        DCJOB_SCHEDULEDJOBPAGE_NEXTSTART: 'Próximo Inicio',
        DCJOB_PAGINATIONCOMPONENT_PAGE: 'Página',
        DCJOB_PAGINATIONCOMPONENT_OF: 'de',
    },
    groupObject: {
        GROUPNUMBER: 'Número de grupo',
        GROUPPAIRCOUNT: 'Conteo de Pares de Grupos',
        GROUPRECORDCOUNT: 'Conteo de Registros de Grupos',
        GROUPCONTAINSMERGEERROR: 'El Grupo Contiene un Error de Combinación',
        GROUPCONTAINSCONVERTERROR: 'El grupo Contiene un Error de Conversión',
        GROUPFOUNDJOB: 'Found in Job',
    },
    days: {
        DCJOB_NEWJOB_MONDAY: 'Lunes',
        DCJOB_NEWJOB_TUESDAY: 'Martes',
        DCJOB_NEWJOB_WEDNESDAY: 'Miércoles',
        DCJOB_NEWJOB_THURSDAY: 'Jueves',
        DCJOB_NEWJOB_FRIDAY: 'Viernes',
        DCJOB_NEWJOB_SATURDAY: 'Sábado',
        DCJOB_NEWJOB_SUNDAY: 'Domingo',
    },
    monthly: {
        LAST_DAY: 'Último día',
        LAST_WEEKDAY: 'Último día de la semana',
    },
    frequency: {
        DCJOB_SCHEDULED_FREQUENCY_PLACEHOLDER: 'Selecciona una Opción...',
        DCJOB_SCHEDULED_FREQUENCY_DAILY: 'Una vez al día',
        DCJOB_SCHEDULED_FREQUENCY_WEEKLY: 'Una vez a la semana',
        DCJOB_SCHEDULED_FREQUENCY_MONTHLY: 'Una vez al mes',
        DCJOB_SCHEDULED_FREQUENCY_CUSTOM: 'Personalizado(a)',
    },
    titles: {
        DCJOB_JOBPAGE_JOBOVERVIEW: 'Vista General del Trabajo',
        DCJOB_SCHEDULEDJOBPAGE_SCHEDULEDJOB: 'Vista General del Trabajo Programado',
        DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOB: 'Eliminar Trabajo Programado',
        DCJOB_JOBPAGE_LISTVIEWS: 'VISTAS DE LISTA',
    },
    buttons: {
        DCJOB_JOBCARD_ABORT: 'Interrumpir',
        DCJOB_BACK: 'Atrás',
        DCJOB_NEWJOB_BACK: 'Atrás',
        DCJOB_AUTOMERGE_BACK: 'Atrás',
        DCJOB_AUTOCONVERT_BACK: 'Atrás',
        DCJOB_JOBPAGE_CANCEL: 'Cancelar',
        DCJOB_NEWJOB_CANCEL: 'Cancelar',
        DCJOB_JOBCARD_CANCEL: 'Cancelar',
        DCJOB_EXPORTMODAL_CANCEL: 'Cancelar',
        DCJOB_DELETEMODAL_CANCEL: 'Cancelar',
        DCJOB_AUTOMERGE_CANCEL: 'Cancelar',
        DCJOB_AUTOCONVERT_CANCEL: 'Cancelar',
        DCJOB_SCHEDULEDJOBPAGE_CANCEL: 'Cancelar',
        DCJOB_SCHEDULEDJOBPAGE_DELETEJOBS: 'Eliminar Trabajos',
        DCJOB_JOBPAGE_DELETEJOBS: 'Eliminar Trabajos',
        DCJOB_DELETEMODAL_DELETEJOBS: 'Eliminar Trabajos',
        DCJOB_SCHEDULEDJOBPAGE_DELETE: 'Eliminar',
        DCJOB_JOBCARD_DELETE: 'Eliminar',
        DCJOB_DELETEMODAL_DELETE: 'Eliminar',
        DCJOB_EXPORTMODAL_EXPORTDCLOCAL: 'Exportar vía DC Local',
        DCJOB_EXPORTMODAL_EXPORTCLOUD: 'Exportar vía Nube de Plauti',
        DCJOB_JOBPAGE_FILTER: 'Filtro',
        DCJOB_NEWJOB_FILTER: 'Filtro',
        DCJOB_FILTER: 'Filter',
        DCJOB_SCHEDULEDJOBPAGE_INFO: 'Información',
        DCJOB_JOBCARD_INFO: 'Información',
        DCJOB_SCHEDULEDJOBPAGE_EDIT: 'Editar',
        DCJOB_SCHEDULEDJOBPAGE_JOBOPTIONS: 'Opciones del trabajo',
        DCJOB_JOBCARD_JOBOPTIONS: 'Opciones del trabajo',
        DCJOB_SCHEDULEDJOBPAGE_NEWJOB: 'Trabajo Nuevo',
        DCJOB_JOBPAGE_NEWJOB: 'Trabajo Nuevo',
        DCJOB_NEWJOB_NEXT: 'Siguiente',
        DCJOB_AUTOMERGE_NEXT: 'Siguiente',
        DCJOB_AUTOCONVERT_NEXT: 'Siguiente',
        DCJOB_JOBPAGE_SAVE: 'Guardar',
        DCJOB_NEWJOB_START: 'Iniciar',
        DCJOB_NEWJOB_SCHEDULE: 'Programar',
        DCJOB_AUTOMERGE_START: 'Iniciar',
        DCJOB_AUTOCONVERT_START: 'Iniciar',
        DCJOB_JOBPAGE_SORTJOBS: 'Ordenar Trabajos',
        DCJOB_SCHEDULEDJOBPAGE_RUNNOW: 'Ejecutar Una Vez Ahora',
        DCJOB_SCHEDULEDJOBPAGE_DEACTIVATED: 'Desactivar',
        DCJOB_SCHEDULEDJOBPAGE_ACTIVATE: 'Activar',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS_NUMBER: 'Ver resultados {0}',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS: 'Ver resultados',
        MERGE: 'Combinar',
        QUICKMERGE: 'Combinación Rápida',
        QUICKCONVERT: 'Conversión Rápida',
        MORE: 'Más',
        edit: 'Editar',
        DCJOB_JOBCARD_VIEWRESULTS: 'Ver Resultados {0}',
        DCJOB_JOBPAGE_DELETESELECTEDJOBS: 'Delete Selected Jobs',
        DCJOB_JOBPAGE_SELECTALL: 'Select All',
        DCJOB_JOBPAGE_DESELECTALL: 'Deselect All',
    },
    badges: {
        DCJOB_JOBCARD_REVIEWERRORS: 'Revisar Errores',
        DCJOB_JOBCARD_READMORE: 'Más información',
        DCJOB_JOBCARD_LIMITTEXT: 'Límite de registro de la licencia alcanzado.',
        DCJOB_JOBCARD_DELETESELECTED: `{count} job selected | {count} jobs selected`,
    },
    metaData: {
        DCJOB_JOBPAGE_AVERAGESCORE: 'Puntuación promedio',
        DCJOB_OVERALLJOBRESULTS_AVERAGESCORE: 'Puntuación promedio',
        DCJOB_JOBPAGE_STORAGESPACETAKEN: 'Espacio de almacenamiento tomado',
        DCJOB_JOBPAGE_TOTALGROUPS: 'Total de grupos',
        DCJOB_JOBPAGE_TOTALJOBS: 'Trabajos totales',
        DCJOB_JOBPAGE_TOTALPAIRS: 'Pares Totales',
        DCJOB_JOBPAGE_TOTALRECORDS: 'Número Total de Registros',
        DCJOB_OVERALLJOBRESULTS_RECORDS: 'Registros',
        DCJOB_OVERALLJOBRESULTS_GROUPS: 'Grupos',
        DCJOB_OVERALLJOBRESULTS_PAIRS: 'Pares',
        DCJOB_OVERALLJOBRESULTS_OBJECT: 'Objeto',
    },
    job: {
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDTITLE: 'Registro de auditoría no disponible con su licencia',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDSUBTITLE: 'El registro de auditoría está disponible en las versiones Premium y superiores',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDBUTTON: 'Actualizar ahora',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDRUPGRADEURL: 'https://go.plauti.com/l/640773/2023-03-27/53tydt',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDTITLE: 'Registro de auditoría desactivado',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDSUBTITLE: 'Por favor, solicita a tu Administrador de Salesforce que habilite el registro de auditoría de Duplicate Check.',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGETITLE: 'El Registro de Combinación está vacío',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTTITLE: 'El registro de conversión está vacío',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGESUBTITLE: 'No ha habido actividad de combinación para este trabajo todavía.',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTSUBTITLE: 'No ha habido actividad de conversión para este trabajo todavía.',
        DCJOB_AUDITLOGTABLEHEADER_MASTERRECORD: 'Registro Principal',
        DCJOB_AUDITLOGTABLEHEADER_MERGEDRECORDS: 'Registro(s) combinado(s)',
        DCJOB_AUDITLOGTABLEHEADER_LEADRECORD: 'Registro de prospecto',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOPERSON: 'Convertir a Cuenta Personal',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOACCOUNT: 'Convertir a Cuenta',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOCONTACT: 'Convertir a Contacto',
        DCJOB_AUDITLOGTABLEHEADER_METHOD: 'Método',
        DCJOB_AUDITLOGTABLEHEADER_DATETIME: 'Fecha y hora',
        DCJOB_AUDITLOGTABLEHEADER_USER: 'Usuario',
        DCJOB_AUDITLOGTOOLTIP_CONVERTEDRECORD: 'Registro Convertido',
        DCJOB_AUDITLOGTOOLTIP_MERGEDRECORD: 'Registro combinado',
        DCJOB_AUDITLOGTOOLTIP_RECORDID: 'ID del registro:',
        DCJOB_AUDITLOGTOOLTIP_AUDITID: 'ID de Auditoría:',
        DCJOB_AUDITLOGSUMMARY_NUMBEROFRECORDS: 'Número de registros {0}',
        DCJOB_JOBCARD_JOBS: 'Trabajos',
        DCJOB_JOBCARD_TASK: 'Tarea',
        DCJOB_JOBCARD_STARTED: 'Iniciado el',
        DCJOB_JOBCARD_FINISHED: 'Terminado el',
        DCJOB_JOBCARD_USER: 'Iniciado por',
        DCJOB_JOBCARD_STATUS: 'Estado',
        DCJOB_JOBPAGE_STATUS: 'Estado',
        DCJOB_JOBCARD_RESULT: 'Resultado',
        DCJOB_JOBPAGE_JOBNAME: 'Nombre del Trabajo',
        DCJOB_NEWJOB_JOBNAME: 'Nombre del Trabajo',
        DCJOB_JOBCARD_JOBNAME: 'Nombre del Trabajo',
        DCJOB_AUTOMERGE_JOBNAME: 'Nombre del Trabajo',
        DCJOB_AUTOCONVERT_JOBNAME: 'Nombre del Trabajo',
        DCJOB_JOBPAGE_JOBID: 'ID del trabajo',
        DCJOB_JOBCARD_JOBID: 'ID del trabajo',
        DCJOB_JOBPAGE_NOJOBS: 'No hay trabajos.',
        DCJOB_SCHEDULEDJOBPAGE_NOSCHEDULEDJOBS: 'No hay trabajos programados.',
        DCJOB_NEWJOB_JOBNAMEPLACEHOLDER: 'Por favor, introduzca un nombre de trabajo',
        DCJOB_JOBCARD_AUTOMERGE: 'Auto Combinar',
        DCJOB_JOBCARD_MANUALMERGE: 'Combinación Manual',
        DCJOB_JOBCARD_QUICKMERGE: 'Combinación Rápida',
        DCJOB_JOBCARD_AUTOCONVERT: 'Auto Convertir',
        DCJOB_JOBCARD_MANUALCONVERT: 'Conversión manual',
        DCJOB_JOBCARD_MERGELOG: 'Registro de Combinación',
        DCJOB_JOBCARD_CONVERTLOG: 'Registro de Conversión',
        DCJOB_JOBCARD_QUICKCONVERT: 'Conversión rápida',
        DCJOB_JOBCARD_AUTOMERGEDCLOCAL: 'Auto Combinar vía DC Local',
        DCJOB_JOBCARD_AUTOMERGECLOUD: 'Combinar automáticamente a través de Plauti Cloud',
        DCJOB_AUTOMERGE_CONFIGUREAUTOMERGE: 'Configurar Auto Combinar',
        DCJOB_AUTOCONVERT_CONFIGUREAUTOCONVERT: 'Configurar Auto Convertir',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE: 'Reconozco que al iniciar esta trabajo de Auto Combinar se combinarán registros duplicados {0} y que la combinación de los registros no se podrán deshacer.',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'Reconozco que al iniciar este trabajo de Auto Combinar se combinan registros duplicados y que la combinación de los registros no se podrán deshacer.',
        DCJOB_EXPORTMODAL_EXPORTRESULTS: 'Exportar resultados',
        DCJOB_JOBCARD_EXPORTRESULTSDCLOCAL: 'Exportar resultados vía DC Local',
        DCJOB_JOBCARD_EXPORTRESULTSCLOUD: 'Exportar resultados a través de la Nube de Plauti',
        DCJOB_JOBCARD_NUMBEROFRECORDS: 'Número de registros',
        DCJOB_JOBPAGE_NUMBEROFRECORDS: 'Número de registros',
        DCJOB_JOBCARD_NUMBEROFPAIRS: 'Número de pares',
        DCJOB_JOBCARD_RESULTFIELDS: 'Campos de Resultados',
        DCJOB_AUTOMERGE_CONFIRMATION: 'Confirmación',
        DCJOB_AUTOCONVERT_CONFIRMATION: 'Confirmación',
        DCJOB_AUTOMERGE_PROCESSEDBY: 'Procesado por',
        DCJOB_AUTOCONVERT_PROCESSEDBY: 'Procesado por',
        DCJOB_DELETEMODAL_CURRENTNUMBEROFJOBS: 'Número actual de empleos en Trabajos de DC',
        DCJOB_DELETEMODAL_JOBSCREATEDAT: 'Trabajos creados en',
        DCJOB_DELETEMODAL_CONTAINSDUPLICATERESULTS: 'Contiene resultados duplicados',
        DCJOB_DELETEMODAL_JOBSSELECTEDFORDELETION: 'Número de trabajos seleccionados para su eliminación',

        infoModal: {
            DCJOB_INFOMODAL_GENERALINFO_STARTEDBYUSER: 'Iniciado por el usuario',
            DCJOB_INFOMODAL_GENERALINFO_STATUS: 'Estado',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMESTARTED: 'Fecha y Hora de Inicio',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMEFINISHED: 'Fecha y Hora de Finalización',
            DCJOB_INFOMODAL_GENERALINFO_TOTALTIMETAKEN: 'Tiempo Total Empleado',
            DCJOB_INFOMODAL_GENERALINFO_PROCESSEDBY: 'Procesado por',
            DCJOB_INFOMODAL_GENERALINFO_LASTDUPLICATEADDED: 'Último duplicado agregado',
            DCJOB_INFOMODAL_GENERALINFO_APPLIEDSCENARIOS: 'Escenarios aplicados',
            DCJOB_INFOMODAL_GENERALINFO_JOBID: 'ID de trabajo',
            DCJOB_INFOMODAL_GENERALINFO_APEXJOBID: 'ID de Trabajo Apex',
            DCJOB_INFOMODAL_GENERALINFO_CREATEDBYUSER: 'Creado por usuario',
            DCJOB_INFOMODAL_GENERALINFO_FREQUENCY: 'Frecuencia',
            DCJOB_INFOMODAL_GENERALINFO_LASTRUNAT: 'La última ejecución fue realizada a las',
            DCJOB_INFOMODAL_GENERALINFO_NEXTRUNAT: 'Siguiente ejecución a las',
            DCJOB_INFOMODAL_GENERALINFO_NUMBEROFTIMESRUN: 'Número de veces que se ejecutó',
            DCJOB_INFOMODAL_GENERALINFO_AUTOPROCESS: 'Auto process',
            DCJOB_INFOMODAL_GENERALINFO_SCHEDULED_LASTMODIFIED: 'Última modificación del trabajo programada por + Fecha y hora',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEGROUPS: 'Duplicar grupos',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEPAIRS: 'Duplicate Pares',
            DCJOB_INFOMODAL_DUPLICATESINFO_RECORDSINVOLVED: 'Registros involucrados',
            DCJOB_INFOMODAL_DUPLICATESINFO_AVERAGESCORE: 'Puntuación promedio',
            DCJOB_INFOMODAL_SELECTEDINFO_OBJECT: 'Objeto',
            DCJOB_INFOMODAL_SELECTEDINFO_NUMBEROFRECORDS: 'Número de registros',
            DCJOB_INFOMODAL_SELECTEDINFO_SOURCE: 'Source',
            DCJOB_INFOMODAL_SELECTEDINFO_MATCH: 'Match'
        },
        sortOptions: {
            DCJOB_JOBPAGE_SORTBY: 'Ordenar por',
            DCJOB_JOBPAGE_DATETIMESTARTED: 'Iniciado el',
            DCJOB_JOBPAGE_DATETIMEFINISHED: 'Terminado el',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEGROUPS: 'Número de grupos duplicados',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEPAIRS: 'Número de pares duplicadas',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATERECORDSINVOLVED: 'Número de registros duplicados implicados',
            DCJOB_JOBPAGE_LASTDUPLICATEADDED: 'Último duplicado agregado',
            DCJOB_JOBPAGE_ORDER: 'Orden',
            DCJOB_JOBPAGE_ASCENDING: 'Ascendente',
            DCJOB_JOBPAGE_DESCENDING: 'Descendente',
        },
        menuOptions: {
            DCJOB_SCHEDULEDJOBPAGE_TITLE: 'Opciones del trabajo',
            DCJOB_JOBCARD_TITLE: 'Opciones del trabajo',
            DCJOB_JOBCARD_OPTION_RESTART: 'Reiniciar',
            DCJOB_JOBCARD_OPTION_STARTAUTOMERGE: 'Comenzar Auto Combinar',
            DCJOB_JOBCARD_OPTION_STARTAUTOCONVERT: 'Iniciar Auto Convertir',
            DCJOB_JOBCARD_OPTION_EXPORTRESULTS: 'Exportar resultados',
            DCJOB_JOBCARD_OPTION_SHAREJOB: 'Compartir Trabajo',
            DCJOB_JOBCARD_OPTION_DELETEJOB: 'Eliminar Trabajo',
        },

        new: {
            DCJOB_NEWJOB_STEP: 'Paso',
            DCJOB_AUTOMERGE_STEP: 'Paso',
            DCJOB_AUTOCONVERT_STEP: 'Paso',
            DCJOB_NEWJOB_SELECTRECORDS: 'Seleccionar Registros',
            DCJOB_NEWJOB_JOBOPTIONS: 'Opciones del trabajo',
            DCJOB_NEWJOB_PROCESSOPTIONS: 'Opciones de proceso',
            DCJOB_NEWJOB_SELECTOBJECT: 'Seleccionar Objeto',
            DCJOB_NEWJOB_SELECTOBJECTPLACEHOLDER: 'Por favor, selecciona un objeto',
            DCJOB_NEWJOB_SELECTOPTIONSPLACEHOLDER: 'Opciones de búsqueda...',
            DCJOB_NEWJOB_ADDCROSSOBJECT: 'Añadir Objeto Cruzado',
            DCJOB_NEWJOB_REMOVECROSSOBJECT: 'Remover objeto cruzado',
            DCJOB_NEWJOB_ADDFILTER: 'Agregar Filtro',
            DCJOB_NEWJOB_MATCHWITH: 'Coincidir con',
        },

        deleteAll: {
            DCJOB_DELETESELECTED_TITLE: 'Delete Selected Jobs',
            DCJOB_DELETESELECTED_MESSAGE: 'Are you sure you want to delete {count} selected job? This action cannot be undone. | Are you sure you want to delete {count} selected jobs? This action cannot be undone.',
        },

        delete: {
            DCJOB_DELETEMODAL_DELETEJOBSMESSAGE: '¿Estás seguro de que deseas eliminar los trabajos {0}? No se pueden deshacer los trabajos eliminados.',
            DCJOB_JOBCARD_DELETEMESSAGE: '¿Estás seguro de que deseas eliminar {0}?',
            DCJOB_JOBCARD_DELETEUNDONE: 'La eliminación de {0} no se puede deshacer.',
            DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOBMESSAGE: '¿Estás seguro de que deseas eliminar el programa "{0}"?',
        },

        options: {
            DCJOB_NEWJOB_SCHEDULE: 'Programar',
            addScheduler: 'Añadir Programación',
            scheduleDescription: 'Decide programar esta tanda para que se ejecute con una frecuencia y en un horario configurados.',
            autoMergeDescription: 'Decide establecer un umbral para la combinación automática de registros duplicados inmediatamente después de finalizar el lote. Ten en cuenta que la Auto Combinar también se puede activar manualmente en cualquier momento.',
            DCJOB_NEWJOB_REMOVESCHEDULER: 'Eliminar horario',
            addAutoMerge: 'Añadir Auto Combinar',
            removeAutoMerge: 'Quitar Auto Combinar',
            DCJOB_NEWJOB_FREQUENCY: 'Frecuencia',
            DCJOB_NEWJOB_CRONSTRING: 'Cadena de Cron',
            DCJOB_NEWJOB_CRONSTRING_INFO: 'Usar el formato de cadena Cron \* * * * *\ para programar trabajos DC especificando segundos, minuto, hora, día, mes y día de la semana.',
            DCJOB_NEWJOB_RECURS: 'Se repite todas las semanas los',
            DCJOB_NEWJOB_MONTHRECURS: 'Recurre todos los meses el',
            DCJOB_NEWJOB_PREFERREDSTARTTIME: 'Hora de Inicio Preferida',
            DCJOB_NEWJOB_PREFERREDSTARTTIMEINFO: 'Salesforce programa el trabajo DC para su ejecución a la hora especificada. La ejecución real puede retrasarse según la disponibilidad del servicio.',
            DCJOB_AUTOMERGE_AUTOMERGETHRESHOLD: 'Umbral de Auto Combinar',
            DCJOB_AUTOMERGE_AUTOMERGETEXT: 'Después de completar el trabajo, todos los pares duplicados con un porcentaje de emparejamiento igual o superior al {0}% se combinarán automáticamente.',
            DCJOB_NEWJOB_AUTOMERGETEXT: 'Después de completar el trabajo, todos los pares duplicados con un porcentaje de emparejamiento igual o superior al {0}% se combinarán automáticamente.',
            DCJOB_NEWJOB_AUTOCONVERTEXPLANATION: 'Todos los pares duplicados con un porcentaje que coincide igual o superior al {0}% se convierten automáticamente.',
            DCJOB_AUTOCONVERT_AUTOCONVERTEXPLANATION: 'Todos los pares duplicados con un porcentaje que coincide igual o superior al {0}% se convierten automáticamente.',
            DCJOB_AUTOMERGE_AUTOMERGEWARNING: 'No se pueden deshacer los registros combinados.',
            DCJOB_NEWJOB_PROCESSINGOPTIONS: 'Opciones de procesamiento',
            DCJOB_AUTOMERGE_PROCESSINGOPTIONS: 'Opciones de procesamiento',
            DCJOB_AUTOCONVERT_PROCESSINGOPTIONS: 'Opciones de procesamiento',
            DCJOB_NEWJOB_RUNONSF: 'Ejecutar en la plataforma Salesforce',
            DCJOB_AUTOMERGE_RUNONSF: 'Ejecutar en la plataforma Salesforce',
            DCJOB_AUTOCONVERT_RUNONSF: 'Ejecutar en la plataforma Salesforce',
            DCJOB_NEWJOB_RUNONDCLOCAL: 'Ejecutar en DC Local',
            DCJOB_AUTOMERGE_RUNONDCLOCAL: 'Ejecutar en DC Local',
            DCJOB_AUTOCONVERT_RUNONDCLOCAL: 'Ejecutar en DC Local',
            DCJOB_AUTOMERGE_SFINFO: 'Basándose en el número de pares de duplicados seleccionados para el proceso de combinación automática, recomendamos procesar el trabajo en la plataforma de Salesforce para obtener mejores resultados.',
            DCJOB_AUTOCONVERT_SFINFO: 'Basándose en el número de pares duplicados seleccionados para el proceso de combinación automática, recomendamos procesar el trabajo en la plataforma Salesforce.',
            DCJOB_AUTOMERGE_DCLOCALINFO: 'Basándose en el número de pares duplicados seleccionados para el proceso de combinación automática, recomendamos procesar el trabajo en DC Local.',
            DCJOB_AUTOCONVERT_DCLOCALINFO: 'Basándose en el número de pares duplicados seleccionados para el proceso de conversión automática, recomendamos procesar el trabajo en DC Local.',
            DCJOB_AUTOMERGE_SFPLATFORMMESSAGE: 'Ejecutar este trabajo en la Plataforma de Salesforce (nativa).',
            DCJOB_AUTOMERGE_DCLOCALMESSAGE: 'Ejecuta esta trabajo utilizando DC Local desktop o DC Local server.',
            DCJOB_AUTOMERGE_ADDOBJECTFILTER: 'Añadir filtro {0}',
            DCJOB_AUTOMERGE_REMOVEOBJECTFILTER: 'Eliminar filtro {0}',
            DCJOB_AUTOMERGE_ADDFILTERLINE: 'Añadir línea de filtro',
            DCJOB_AUTOCONVERT_ADDFILTERLINE: 'Añadir línea de filtro',
            DCJOB_AUTOMERGE_OBJECTFILTER: 'Filtro {0}',
        },
    },
    scenario: {
        DCJOB_NEWJOB_SCENARIO: 'Escenario',
        DCJOB_NEWJOB_SCENARIOINFO: 'En un trabajo de objeto cruzado, sólo están disponibles escenarios del objeto coincidente.',
        DCJOB_SCENARIOCARD_SCENARIONAME: 'Nombre del Escenario',
        DCJOB_SCENARIOCARD_THRESHOLD: 'Umbral',
        DCJOB_SCENARIOCARD_EMPTYFIELDS: 'Campos vacíos',
        fields: {
            DCJOB_SCENARIOCARD_FIELD: 'Campo',
            DCJOB_SCENARIOCARD_FREQUENTWORDS: 'Palabras frecuentes',
            DCJOB_SCENARIOCARD_MATCHINGMETHOD: 'Método de Coincidencia',
            DCJOB_SCENARIOCARD_WEIGHT: 'Peso',
        },
    },
    filter: {
        DCJOB_INFOMODAL_READMOREINFO: 'Después de agregar un filtro, este recibe un número. Tu primer filtro se convierte en Filtro 1 y tu segundo filtro se convierte en Filtro 2. Aplicas la lógica del filtro en función de estos filtros numerados. Haz clic en el ícono para obtener más información.',
        DCJOB_INFOMODAL_FILTER: 'Filtro',
        DCJOB_INFOMODAL_SOURCEFILTER: 'Filtro de origen',
        DCJOB_INFOMODAL_MATCHFILTER: 'Filtro de coincidencia',
        DCJOB_INFOMODAL_AUTOMERGE_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOMERGE_GROUPFILTER: 'Auto Merge Group Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_GROUPFILTER: 'Auto Convert Group Filter',
        DCJOB_JOBPAGE_FILTERJOBS: 'Filtrar trabajos',
        DCJOB_JOBPAGE_NOFILTERAPPLIED: 'No se ha aplicado ningún filtro.',
        addFilter: 'Agregar Filtro',
        operators: {
            DCJOB_SCHEDULEDJOBPAGE_OR: 'O',
            DCJOB_JOBINFO_OR: 'O',
        },
        removeFilter: 'Eliminar filtro',
        DCJOB_NEWJOB_SETFILTER: 'Definir filtro',
        DCJOB_NEWJOB_ALLRECORDS: 'Sin filtro, Procesar todos los registros',
        DCJOB_NEWJOB_COMPARERECORDSINABOVEFILTERWITH: 'Comparar registros en el filtro anterior con',
        DCJOB_NEWJOB_RECORDSTHATMEETCRITERIA: 'Registros que cumplen con los criterios del filtro anterior',
        jobFilterFields: {
            DCJOB_JOBPAGE_STARTEDBYUSER: 'Iniciado por Usuario',
            DCJOB_JOBPAGE_CONTAINSFILTER: 'Contiene filtro',
            DCJOB_JOBPAGE_CONTAINSAUTOMERGE: 'Contiene Auto Combinar',
            DCJOB_JOBPAGE_CONSTAINSAUTOCONVERT: 'Contiene Auto Convertir',
        },
        startedScheduledJob: '{0} se está ejecutando',
        activeScheduledJob: '{0} está activado',
        deactivatedScheduledJob: '{0} se ha desactivado',
        DCJOB_JOBPAGE_FILTERSAVED: 'Filtro guardado correctamente.',
        addFilterlineLabel: 'Añadir línea de filtro',
        newFilterlinePlaceholder: 'Añadir línea de filtro',
        fieldLabel: 'Campo',
        fieldPlaceholder: 'Selecciona una Opción...',
        fieldPlaceholderSearch: 'Opciones de búsqueda...',
        operatorLabel: 'Operador',
        emptyValueLabel: 'Vaciar',
        emptyOptionLabel: '- none -',
        addFilterLogicLabel: 'Añadir Lógica de Filtro',
        removeFilterLogicLabel: 'Eliminar Lógica de Filtro',
        doneButton: 'Completado',
        inputLabels: {
            Value: 'Valor',
            Date: 'Fecha',
            Time: 'Hora',
            'Start date': 'Start Date',
            'End date': 'End Date',
            'Start Time': 'Start Time',
            'End Time': 'End Time',
        },
        logic: {
            ErrorUnusedFilters: 'Hay una línea de filtro no utilizada',
            ErrorTypo: 'Hay un error tipográfico',
            ErrorBadNumber: '{0} no se puede utilizar en la lógica del filtro',
            ErrorMissingRightOperand: 'Faltan paréntesis',
            ErrorAmbiguousAndOr: 'Añadir paréntesis al usar el Y + O',
            ErrorMissingOperand: 'NO debe ser seguido por un operando',
            ErrorParen: 'Paréntesis inesperado',
        },
    },
    matchingMethods: {
        EQUAL: 'Exacto',
        EQUAL_RANDOM: 'Exacto (orden aleatoria)',
        NOT_EQUAL: 'No es igual',
        EQUAL_NULL: 'Igual a nula',
        FUZZY_PERSON: 'Nombre de la persona',
        FUZZY_COMPANY_EXTRA_STRICT: 'Nombre de la empresa',
        PHONE: 'Número de teléfono',
        PHONE_ADVANCED: 'Número de teléfono avanzado',
        EMAIL_EXACT: 'Correo electrónico',
        EMAIL: 'Correo Electrónico',
        DOMAIN_EXACT: 'Dominio',
        DOMAIN_FUZZY: 'Dominio difuso',
        URL_EXACT: 'Url',
        URL_FUZZY: 'Url difusa',
        PRODUCT: 'Número de producto',
        POSTAL_CODE: 'Código postal',
        PERSON_NAME: 'Difuso',
        FUZZY_COMPANY: 'Difuso Parcial Ligero',
        FUZZY_COMPANY_STRICT: 'Difuso Parcial Medio',
        COMPANY_NAME: 'Difuso Parcial Intenso',
        COMPANY: 'Empresa',
        TEXT: 'Texto grande',
        DATE_DISTANCE_DAYS: 'Distancia de fecha en días',
        HAS_VALUE: 'Contiene valor',
    },
    frequentWords: {
        STREET: 'Calle',
        COMPANY: 'Empresa',
        COMMON: 'Común',
        NAME: 'Nombres de la persona',
        EMAIL: 'Correo Electrónico',
        CUSTOM1: 'Personalizado 1',
        CUSTOM2: 'Personalizado 2',
    },
    emptyFieldOptions: {
        DEDUP50: 'Puntuación 50%',
        DEDUP: 'Puntuación 100%',
        SEARCH: 'Ignorar',
    },
    pageNavigation: {
        PREVIOUSPAGE: 'Página anterior',
        NEXTPAGE: 'Página siguiente',
    },
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTSVIEW: 'Resumen de resultados duplicados',
    DCJOB_OVERALLJOBRESULTS_OVERALLJOBRESULTS: 'Resultados de los trabajos generales',
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTS: 'Duplicar resultados',
    DCJOB_OVERALLJOBRESULTS_OPENALLGROUPS: 'Abrir Todos los Grupos',
    DCJOB_OVERALLJOBRESULTS_CLOSEALLGROUPS: 'Cerrar Todos los Grupos',
    DCJOB_OVERALLJOBRESULTS_SEARCHUSERS: 'Buscar usuarios',
    DCJOB_OVERALLJOBRESULTS_APPLYFILTER: 'Aplicar filtro',
    DCJOB_OVERALLJOBRESULTS_PAIRCOUNT: 'Conteo de pares',
    DCJOB_OVERALLJOBRESULTS_RECORDCOUNT: 'Número de registros',
    DCJOB_OVERALLJOBRESULTS_GROUP: 'Grupo',
    DCJOB_OVERALLJOBRESULTS_MINSCORE: 'Puntuación mínima',
    DCJOB_OVERALLJOBRESULTS_MAXSCORE: 'Puntuación máxima',
    DCJOB_OVERALLJOBRESULTS_AVGSCORE: 'Puntuación media',
    DCJOB_OVERALLJOBRESULTS_ONEERROR: '1 error',
    DCJOB_OVERALLJOBRESULTS_MERGESELECTEDRECORDS: 'Combinar registros seleccionados',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTION: 'Descartar selección',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTIONFOREVER: 'Descartar selección para siempre',
    DCJOB_OVERALLJOBRESULTS_DELETINGRECORDSNOTUNDOABLE: 'La eliminación de registros no se puede deshacer.',
    DCJOB_OVERALLJOBRESULTS_MERGEPAIR: 'Combinar Par',
    DCJOB_OVERALLJOBRESULTS_QUICKMERGEPAIR: 'Par de Combinación Rápida',
    DCJOB_OVERALLJOBRESULTS_CONVERTPAIR: 'Convertir Par',
    DCJOB_OVERALLJOBRESULTS_QUICKCONVERTPAIR: 'Par de Conversión Rápida',
    DCJOB_OVERALLJOBRESULTS_AREYOUSUREYOUWANTTODELETE: '¿Estás seguro de que deseas eliminar [[insertHTMLWithLink]] de Salesforce',
    DCJOB_OVERALLJOBRESULTS_DELETERECORD: 'Eliminar registro',
    DCJOB_OVERALLJOBRESULTS_RECORD: 'Registro',
    DCJOB_OVERALLJOBRESULTS_SELECTANOPTION: 'Selecciona una Opción...',
    DCJOB_OVERALLJOBRESULTS_SEARCHOPTIONS: 'Opciones de búsqueda...',
    validation: {
        required: 'Este campo es obligatorio',
        max: 'Este campo debe tener menos de {max} caracteres',
        invalid_cron_format: 'Cadena de Cron no válida. Por favor, comprueba el formato.',
        invalid_seconds_or_minutes: 'Cadena de Cron no válida. Por favor, utiliza sólo valores numéricos para segundos y minutos.',
        invalid_day_of_week_and_day_of_month_combination: 'Cadena de Cron no válida. Por favor, especifica sólo el día de la semana o el día del mes.',
    },
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWPAIRVIEW: 'Cambiar a Vista de Pares',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWGROUPVIEW: 'Cambiar a Vista de Grupo',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFROMJOB: 'Descartar Grupo del Trabajo',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPINJOB: 'Descartar grupo en este trabajo',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFOREVER: 'Descartar Grupo para siempre',
    DCJOB_OVERALLJOBRESULTS_FILTER_JOBTYPE: 'Tipo de trabajo',
    DCJOB_OVERALLJOBRESULTS_FILTER_OWNER: '{objectName} Propietario',
    DCJOB_OVERALLJOBRESULTS_FILTER_RECORDTYPE: 'Tipo de registro {objectName}',
    DCJOB_OVERALLJOBRESULTS_FILTER_PREDEFINED: 'Filtro predefinido {objectName}',
    DCJOB_OVERALLJOBRESULTS_FILTER_FIELD: '{objectName} {fieldName}',
};
