export default {
    DCJOB_INFOMODALTAB_GENERALINFO: 'Informations générales',
    DCJOB_INFOMODALTAB_SELECTEDRECORDS: 'Enregistrements sélectionnés',
    DCJOB_INFOMODALTAB_APPLIEDSCENARIOS: 'Scénarios appliqués',
    DCJOB_INFOMODALTAB_UNPROCESSEDRESULTS: 'Résultats non traités',
    DCJOB_INFOMODALTAB_DUPLICATERESULTS: 'Doublons trouvés',
    DCJOB_INFOMODALTAB_CONVERTLOG: 'Journal de Conversion',
    DCJOB_INFOMODALTAB_MERGELOG: 'Journal de Fusion',
    DCJOB_OBJECT_USERS: 'Utilisateurs',
    DCJOB_OBJECT_GROUPS: 'Groupes',
    DCJOB_OBJECT_QUEUES: 'Queues',
    DCJOB_BUTTON_CANCEL: 'Annuler',
    DCJOB_BUTTON_CALCULATING: 'Calcul du nombre d\'enregistrements',
    DCJOB_BUTTON_TAKINGLONGER: 'Le calcul prend un peu plus de temps...',
    DCJOB_BUTTON_NEXTWITHLIMIT: 'Suivant avec limite',
    DCJOB_BUTTON_ABORTING: 'Abandon',
    DCJOB_BUTTON_REFRESH: 'Rafraîchir',
    DCJOB_LINK_READMORE: 'En savoir plus',
    DCJOB_SHAREMODAL_SHAREMETHOD: 'Partager la méthode',
    DCJOB_SHAREMODAL_LINK: 'Lier',
    DCJOB_SHAREMODAL_COPY: 'Copier dans le presse-papier',
    DCJOB_SHAREMODAL_COPIED: 'Copié dans le presse-papiers',
    DCJOB_SHAREMODAL_SHAREJOB: 'Partager le Job',
    DCJOB_SHAREMODAL_DIRECTLINK: 'Lien direct',
    DCJOB_SHAREMODAL_TASK: 'Créer une Tâche',
    DCJOB_SHAREMODAL_EMAIL: 'Envoyer un e-mail',
    DCJOB_SHAREMODAL_RECIPIENTS: 'Destinataires',
    DCJOB_SHAREMODAL_SUBJECT: 'Objet',
    DCJOB_SHAREMODAL_TEXT: 'Texte du texte',
    DCJOB_SHAREMODAL_ASSIGNTO: 'Attribuer à',
    DCJOB_SHAREMODAL_STATUS: 'Statut',
    DCJOB_SHAREMODAL_DUEDATE: 'Échéance',
    DCJOB_SHAREMODAL_DESCRIPTION: 'Libellé',
    DCJOB_SHAREMODAL_PRIORITY: 'Priorité',
    DCJOB_SHAREMODAL_CREATETASK: 'Créer Tâche',
    DCJOB_SHAREMODAL_TASKSUCCESS: 'Tâche créée avec succès',
    DCJOB_SHAREMODAL_EMAILSUCCESS: 'Courriel envoyé',
    DCJOB_SHAREMODAL_SHAREINFO: 'Pour partager, la variable {0} est nécessaire. Ne la supprimez pas du champ texte.',
    DCJOB_PLACEHOLDER_SEARCH: 'Rechercher',
    DCJOB_PLACEHOLDER_SUBJECT: 'Veuillez saisir un objet',
    DCJOB_EDITJOB_SCHEDULE: 'Planification',
    DCJOB_NEWJOB_RUNONPLAUTICLOUD: 'Exécuter sur Plauti Cloud',
    DCJOB_NEWJOB_PLAUTICLOUDPROCESSDESCRIPTION: 'Exécutez ce job en utilisant Plauti Cloud, une nouvelle option de traitement offerte par Plauti.',
    DCJOB_NEWJOB_FILTERLOGIC: 'Logique de Filtrage',
    DCJOB_NEWJOB_FILTERLOGICDESCRIPTION: 'Après avoir ajouté un filtre, le filtre est numéroté. Le premier filtre sera numéroté Filtre 1, le second sera Filtre 2, etc. Vous appliquez une logique de filtre basée sur ces filtres numérotés.',
    DCJOB_NEWJOB_ADDSCHEDULE: 'Ajouter une Planification',
    DCJOB_NEWJOB_AUTOCONVERT: 'Conversion Automatique',
    DCJOB_NEWJOB_AUTOMERGE: 'Fusion Automatique',
    DCJOB_NEWJOB_ADDAUTOCONVERT: 'Ajouter la conversion automatique',
    DCJOB_NEWJOB_ADDAUTOMERGE: 'Ajouter la fusion automatique',
    DCJOB_NEWJOB_AUTOCONVERTTHRESHOLD: 'Seuil de conversion automatique',
    DCJOB_NEWJOB_AUTOMERGETHRESHOLD: 'Seuil de fusion automatique',
    DCJOB_NEWJOB_SCHEDULEDESCRIPTION: 'Planifiez ce job à exécuter à une fréquence et une heure définies.',
    DCJOB_NEWJOB_AUTOMERGEDESCRIPTION: 'Ajouter un score minimum pour fusionner automatiquement les enregistrements en double dès que le job est terminée.',
    DCJOB_NEWJOB_AUTOCONVERTDESCRIPTION: 'Ajouter un score minimum pour convertir automatiquement les enregistrements en doublons dès que le job est terminée.',
    DCJOB_NEWJOB_REMOVEAUTOMERGE: 'Supprimer la fusion automatique',
    DCJOB_NEWJOB_REMOVEAUTOCONVERT: 'Supprimer la conversion automatique',
    DCJOB_NEWJOB_AUTOCONVERTWARNING: 'La conversion des enregistrements ne peut pas être annulée.',
    DCJOB_NEWJOB_AUTOMERGEWARNING: 'La fusion des enregistrements ne peut pas être annulée.',
    DCJOB_NEWJOB_CONVERTOWNERINFO: 'Les Pistes seront converties vers le Compte cible en tant que nouveau Contact. Décidez quel utilisateur doit être le propriétaire des nouveaux Contacts.',
    DCJOB_NEWJOB_CONVERTSTATUS: 'Statut après conversion',
    DCJOB_NEWJOB_CONVERTOWNER: 'Propriétaire des nouveaux enregistrements de Contact',
    DCJOB_NEWJOB_LEADOWNER: 'Propriétaire Actuel de Piste',
    DCJOB_NEWJOB_ACCOUNTOWNER: 'Propriétaire actuel du compte',
    DCJOB_NEWJOB_LOOKUPUSER: 'Utilisateur de recherche',
    DCJOB_NEWJOB_SFPROCESSDESCRIPTION: 'Exécutez ce job sur la Plateforme Salesforce sans aucun transfert de données.',
    DCJOB_NEWJOB_DCLOCALPROCESSDESCRIPTION: 'Exécutez cette job en utilisant DC Local Desktop ou DC Local server.',
    DCJOB_NEWJOB_RECORDLIMITREACHED: 'Limite d\'enregistrements sous licence atteinte',
    DCJOB_NEWJOB_RECORDLIMITDESCRIPTION: 'En fonction du nombre d\'enregistrements qui sont actuellement sélectionnés, ce job atteindra la limite d\'enregistrement sous licence. Par conséquent, seule une partie des enregistrements sélectionnés sera analysée pour détecter les doublons.',
    DCJOB_NEWJOB_NORECORDSSELECTED: 'Aucun enregistrement sélectionné.',
    DCJOB_NEWJOB_SELECTSCENARIO: 'Veuillez sélectionner au moins un scénario',
    DCJOB_NEWJOB_NOSCENARIO: 'Aucun scénario trouvé pour {0}',
    DCJOB_NEWJOB_NOSELECTIONDESCRIPTION: 'Il n\'y a actuellement aucun enregistrement correspondant à vos critères de filtre. Pensez à modifier votre filtre. Vous pouvez toujours procéder à la configuration d\'un job planifié.',
    DCJOB_NEWJOB_SFRECOMMENDATION: 'En fonction du nombre d’enregistrements actuellement sélectionnés, nous vous recommandons de traiter le job sur le Plateforme Salesforce. À partir de 15 000 enregistrements et plus, l’utilisation de DC Local serait recommandée pour de meilleures performances.',
    DCJOB_NEWJOB_DCLOCALRECOMMENDATION: 'En fonction du nombre d’enregistrements qui sont actuellement sélectionnés (plus de 15 000 enregistrements), nous vous recommandons de traiter le job en utilisant DC Local pour de meilleures performances.',
    DCJOB_NEWJOB_FILTERNOTFOUND: 'L\'option de filtre {0} sélectionnée «{1}» n\'est plus disponible.',
    DCJOB_AUTOCONVERT_DCLOCALMESSAGE: 'Exécutez cette job en utilisant DC Local Desktop ou DC Local Server. Actuellement pas encore disponible pour la conversion automatique.',
    DCJOB_AUTOCONVERT_CONVERTSTATUS: 'Statut après conversion',
    DCJOB_AUTOCONVERT_SELECTEDRECORDS: 'Nombre d\'enregistrements sélectionnés pour la conversion automatique',
    DCJOB_AUTOCONVERT_NEWCONTACTOWNER: 'Propriétaire des nouveaux enregistrements de Contact',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE: 'Je reconnais que le démarrage de ce job de conversion automatique convertira les enregistrements en double {0} et que la conversion des enregistrements ne peut pas être annulée',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'Je reconnais que le démarrage de ce job de conversion automatique convertira les enregistrements en double, et que la conversion des enregistrements ne peut pas être annulée',
    DCJOB_AUTOCONVERT_NORECORDSSELECTED: 'Il n\'y a actuellement aucun enregistrement correspondant à vos critères de filtre. Pensez à modifier votre filtre.',
    DCJOB_AUTOCONVERT_TRIALWARNING: 'La conversion automatique est limitée à 20 enregistrements en raison de votre licence d\'essai. Passez à une licence payante pour supprimer la limitation.',
    DCJOB_AUTOMERGE_FILTERLOGIC: 'Logique de Filtrage',
    DCJOB_AUTOMERGE_FILTERLOGICDESCRIPTION: 'Après avoir ajouté un filtre, le filtre est numéroté. Le premier filtre sera numéroté Filtre 1, le second sera Filtre 2, etc. Vous appliquez une logique de filtre basée sur ces filtres numérotés.',
    DCJOB_AUTOMERGE_SELECTEDRECORDS: 'Nombre d\'enregistrements sélectionnés pour la fusion automatique',
    DCJOB_AUTOMERGE_SELECTEDDUPLICATEPAIRS: 'Nombre de paires de doublons sélectionnées pour la fusion automatique',
    DCJOB_AUTOMERGE_TRIALWARNING: 'La fusion automatique est limitée à 20 enregistrements en raison de votre licence d\'essai. Passez à une licence payante pour supprimer la limitation.',
    DCJOB_OVERVIEW_PROCESSEDBY: 'Traité par',
    DCJOB_OVERVIEW_DELETINGJOB: 'Job en cours de suppression',
    DCJOB_OVERVIEW_JOBABORTED: 'Job annulé',
    DCJOB_ACCESS_CURRENTUSERNOACCESS: 'L\'utilisateur actuel n\'a pas accès aux classes requises',
    DCJOB_ACCESS_REACHOUTTOADMINISTRATOR: 'Veuillez contacter votre administrateur Salesforce',
    DCJOB_ACCESS_DEACTIVATEDCJOBBETA: 'Désactiver la Bêta de DC Job',
    DCJOB_ACCESS_YOUHAVENOACCESS: 'Vous n\'avez pas accès à la classe Apex nommée',
    DCJOB_FILTER_JOBTYPE: 'Type de Job',
    DCJOB_FILTER_DUPCHECKJOB: 'Job de doublons',
    DCJOB_FILTER_DUPCHECKLOCAL: 'DC Local / Plauti Cloud',
    DCJOB_FILTER_UNIQUEBULKAPIINSERT: 'Insertion d\'API d\'importation unique / en bloc',
    DCJOB_FILTER_WEBTOLEAD: 'Web vers Piste',
    DCJOB_FILTER_SETFORMERGE: 'Définir pour Fusion',
    DCJOB_FILTER_SINGLEAPIINSERT: 'Insertion API Unique',
    DCJOB_FILTER_FLOW: 'Flux',
    DCJOB_FILTER_ABORTED: 'Avorté',
    DCJOB_FILTER_FAILED: 'Échoué',
    DCJOB_FILTER_COMPLETED: 'Terminé',
    DCJOB_FILTER_HOLDING: 'Attendre',
    DCJOB_FILTER_PROCESSING: 'Traitement',
    DCJOB_FILTER_INCAMPAIGN: 'Dans la campagne',
    DCJOB_FILTER_FILTER: 'Filtre',
    DCJOB_JOBCARD_PROCESSEDWITHDCLOCAL: 'Job DC Local',
    DCJOB_JOBCARD_PROCESSEDWITHCLOUD: 'Job Plauti Cloud',
    DCJOB_JOBPAGE_APEXJOBID: 'ID Job Apex',
    ONBOARDING_NEXT: 'Suivant',
    ONBOARDING_BACK: 'Retour',
    ONBOARDING_FINISH: 'Terminer',
    ONBOARDING_DOCUMENTATION: 'Documentation',
    ONBOARDING_WATCH_VIDEO: 'Regarder la vidéo',
    ONBOARDING_GETTING_STARTED: 'Commencer avec Duplicate Check',
    ONBOARDING_THANK_YOU_FOR_INSTALLING: 'Merci d\'avoir installé Duplicate Check',
    ONBOARDING_RUNNING_A_DC_JOB: 'Exécuter un job DC',
    ONBOARDING_SETUP_DUPLICATE_PREVENTION: 'Mettre en place la prévention des doublons',
    ONBOARDING_LEARN_ABOUT_DCLIVE: 'En savoir plus sur DC en Direct',
    ONBOARDING_HOW_TO_CONFIGURE_DC: 'Comment configurer Duplicate Check',
    ONBOARDING_OPTIONS_FOR_AUTOMATION: 'Options pour l\'automatisation',
    ONBOARDING_INTEGRATION: 'Intégration',
    ONBOARDING_CUSTOMISATION: 'Personnalisation',
    ONBOARDING_GET_STARTED: 'Commençons !',
    ONBOARDING_NOTIFICATION_JOB_STARTED: 'Le job DC a commencé à {0}',
    ONBOARDING_NOTIFICATION_VIEW_PROGRESS: 'Cliquez pour voir la progression en l\'Aperçu DC Job',
    ONBOARDING_JOB_INFO_CARD_OPEN_RESULTS: 'Résultats ouverts',
    ONBOARDING_JOB_INFO_CARD_STATUS: 'Statut',
    ONBOARDING_JOB_INFO_CARD_RESULT: 'Résultat',
    ONBOARDING_INTRO_THANK_YOU_FOR_INSTALLING: 'Merci d\'avoir installé Duplicate Check !',
    ONBOARDING_INTRO_OPENING_MESSAGE: 'Bonjour Trailblazer ! Nous sommes ravis de voir que vous avez installé Duplicate Check pour Salesforce. Vous êtes à quelques pas d\'un environnement Salesforce libre de doublons qui a des données précises et fiables, en améliorant la prise de décision, la productivité et la satisfaction de la clientèle.',
    ONBOARDING_INTRO_START_LOOKING_FOR_DUPLICATES: 'Nous avons pris la liberté de commencer à chercher quelques doublons…',
    ONBOARDING_INTRO_LOOKING_FOR_DUPLICATE_MESSAGE: 'Nous avons pris la liberté de commencer un travail rapide sur un millier d\'enregistrements {0} afin de pouvoir vous montrer combien il est facile de trouver ces doublons dans l\'objet {0} . N’hésitez pas à consulter le résultat dans un nouvel onglet en cliquant sur « Ouvrir les résultats ».',
    ONBOARDING_RUN_JOB_OPENING_MESSAGE: 'DC Job est le point de départ de tous vos efforts de dédoublement. Pour trouver tous les enregistrements en double dans n\'importe quel objet Salesforce, vous pouvez exécuter un « Duplicate Check Job », également appelé « DC Job ».',
    ONBOARDING_RUN_JOB_START_FIRST_JOB_HELP: 'Laissez-nous vous aider à commencer vos premiers emplois!',
    ONBOARDING_RUN_JOB_START_NOW: 'Démarrer Maintenant',
    ONBOARDING_RUN_JOB_STARTED: 'Démarré',
    ONBOARDING_RUN_JOB_LEAD_TITLE: 'Exécuter un job sur des Pistes',
    ONBOARDING_RUN_JOB_LEAD_DESCRIPTION: 'Trouver des doublons basés sur la comparaison de prénom, de nom, de courriel, de société et de téléphone.',
    ONBOARDING_RUN_JOB_CONTACT_TITLE: 'Exécuter un job sur des Contacts',
    ONBOARDING_RUN_JOB_CONTACT_DESCRIPTION: 'Trouver des doublons basés sur la comparaison de prénom, de nom, de courriel et de téléphone.',
    ONBOARDING_RUN_JOB_ACCOUNT_TITLE: 'Exécuter un job sur des Comptes',
    ONBOARDING_RUN_JOB_ACCOUNT_DESCRIPTION: 'Trouver des doublons en fonction de la comparaison du nom de la société, de la ville de facturation et du téléphone.',
    ONBOARDING_RUN_JOB_THINGS_TO_KNOW: 'Choses à savoir sur DC Job',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_FEATURE: 'fonctionnalité objet croisé',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_MESSAGE: 'Avec l\' {0}, comparer les enregistrements dans n\'importe quel objet avec des enregistrements dans n\'importe quel autre objet',
    ONBOARDING_RUN_JOB_PLAUTI_CLOUD: 'Plauti Cloud',
    ONBOARDING_RUN_JOB_LOCAL: 'DC Local',
    ONBOARDING_RUN_JOB_PROCESSING: 'Décidez où traiter un job DC - complètement dans Salesforce, ou à l\'extérieur via {0} ou {1}',
    ONBOARDING_RUN_JOB_MANUALLY: 'manuellement',
    ONBOARDING_RUN_JOB_AUTOMATICALLY: 'automatiquement',
    ONBOARDING_RUN_JOB_MERGE_OR_CONVERT: 'Choisissez de fusionner ou de convertir {0} ou {1}',
    ONBOARDING_RUN_JOB_SCHEDULE_A_JOB: 'Planifier un job',
    ONBOARDING_RUN_JOB_SCHEDULE_MESSAGE: '{0} pour fonctionner à la fréquence et à l\'heure que vous décidez',
    ONBOARDING_PREVENTION_DUPLICATE_PREVENTION: 'Prévention des Doublons',
    ONBOARDING_PREVENTION_OPENING_MESSAGE: 'Ci-dessous, trouvez les différentes façons qu\'un enregistrement peut entrer en Salesforce, et voyez comment DC peut s\'assurer que les doublons sont détectés et pris en charge.',
    ONBOARDING_PREVENTION_MANUAL_INSERT: 'Insertion manuelle',
    ONBOARDING_PREVENTION_MANUAL_INSERT_DESCRIPTION: 'Même en cas de précaution supplémentaire, les doublons peuvent entrer en Salesforce à travers les utilisateurs finaux en les entrant manuellement. Duplicate Check possède une excellente fonctionnalité que vous pouvez décider d\'implémenter, que nous appelons "DC Entry". En savoir plus en visitant la documentation.',
    ONBOARDING_PREVENTION_IMPORT: 'Importer',
    ONBOARDING_PREVENTION_IMPORT_DESCRIPTION: 'Lors de l\'importation d\'enregistrements via Data Loader ou l\'assistant d\'importation de données, les doublons trouveront leur chemin vers votre environnement Salesforce. En utilisant Duplicate Check, un doublon est signalé lors d\'une importation, après quoi vous avez la possibilité de fusionner les enregistrements. En n\'empêchant pas le doublon d\'entrer dans votre compte, vous avez la possibilité de conserver les informations les plus à jour.',
    ONBOARDING_PREVENTION_INTEGRATIONS: 'Intégrations (Salesforce API)',
    ONBOARDING_PREVENTION_INTEGRATIONS_DESCRIPTION: 'L\'implémentation moyenne de Salesforce est liée à une douzaine d\'outils externes qui communiquent tous via l\'API Salesforce, créant ainsi de nombreux nouveaux enregistrements quotidiennement. Duplicate Check permet de surveiller le canal API Salesforce et de détecter tout doublon au point d\'entrée.',
    ONBOARDING_PREVENTION_WEBFORMS: 'Formulaires web',
    ONBOARDING_PREVENTION_WEBFORMS_DESCRIPTION: 'Si vous avez des formulaires web liés à votre environnement Salesforce, vous êtes probablement familier avec la question d\'obtenir des doublons. En utilisant Duplicate Check, vous obtenez la possibilité de détecter les doublons depuis n\'importe quel formulaire web et de traiter le doublon en temps réel.',
    ONBOARDING_DCLIVE_OPENING_MESSAGE: 'Chez Plauti, nous pensons que la qualité des données est une responsabilité partagée dans l’ensemble de l’organisation, raison pour laquelle nous avons créé DC en Direct.',
    ONBOARDING_DCLIVE_DESCRIPTION: 'DC en Direct est un composant que vous pouvez ajouter à n\'importe quelle mise en page d\'objets et est accessible à n\'importe quel utilisateur dans Salesforce. Lorsqu\'un enregistrement est ouvert, DC en Direct affiche les doublons pour l\'enregistrement qui est ouvert.',
    ONBOARDING_DCLIVE_EMPOWER_END_USERS: 'Renforcez les utilisateurs finaux en leur donnant un aperçu de la qualité de leurs données et décidez de les autoriser à {0}, ou à juste {1}.',
    ONBOARDING_DCLIVE_MERGE_RECORDS_THEMSELVES: 'fusionner les enregistrements eux-mêmes',
    ONBOARDING_DCLIVE_FLAG_FOR_ADMIN: 'les signaler à un administrateur',
    ONBOARDING_DCLIVE_HOW_TO_CONFIGURE: 'Comment configurer DC en Direct',
    ONBOARDING_CONFIGURE_OPENING_MESSAGE: 'L\'une des choses auxquelles Duplicate Check est bonne, c\'est de configurer l\'outil pour qu\'il s\'adapte à votre implémentation Salesforce unique. Pour tirer le meilleur parti de l\'outil, assurez-vous de lire sur les sujets suivants.',
    ONBOARDING_CONFIGURE_SCENARIOS_SEARCH_INDEX: 'Scénarios & Index de recherche',
    ONBOARDING_CONFIGURE_SCENARIO_EXPLANATION: 'Un scénario dans Duplicate Check est comme les "règles de correspondance" dans Salesforce - il décide comment comparer les enregistrements et décide quel est le doublon. Pour tirer le meilleur parti de l\'outil, nous vous recommandons de lire ce qu\'il peut faire et comment il peut être configuré.',
    ONBOARDING_CONFIGURE_SEARCH_INDEX_EXPLANATION: 'Pour qu\'un scénario fonctionne de manière optimale, nous vous demandons d\'activer et de créer l\'index de recherche. Duplicate Check utilise l\'index de recherche pour trouver des enregistrements en double en utilisant le scénario appliqué. Sans index de recherche, Duplicate Check n\'est pas en mesure de trouver tous les doublons.',
    ONBOARDING_CONFIGURE_MERGE_RULES: 'Règles de fusion',
    ONBOARDING_CONFIGURE_MERGE_RULES_EXPLANATION: 'Lors de la fusion des enregistrements dans un objet, Duplicate Check appelle les règles de fusion pour choisir un enregistrement principal et déterminer quels champs doivent être stockés dans cet enregistrement principal. Les règles de fusion déterminent également les champs présélectionnés sur la page de fusion manuelle et les règles sont exécutées lors d\'une fusion automatisée. Apprenez à configurer les règles de fusion.',
    ONBOARDING_AUTOMATION_OPENING_MESSAGE: 'En tant que natif de Salesforce, Duplicate Check offre le meilleur en classe de détection et de traitement de doublons en temps réel.',
    ONBOARDING_AUTOMATION_DC_LEVEL_OFFER: 'Duplicate Check offre différents niveaux d\'automatisation',
    ONBOARDING_AUTOMATION_EXPLANATION: 'Il existe différents niveaux d’automatisation, allant de l’exploitation humaine aux processus entièrement automatisés. Apprenez-en plus sur l’automatisation et choisissez ce qui vous convient.',
    ONBOARDING_AUTOMATION_AUDIT_LOG: 'Journal d\'Audit',
    ONBOARDING_AUTOMATION_AUDIT_LOG_DESCRIPTION: 'Toute activité de fusion ou de conversion, exécutée manuellement ou automatiquement, peut être suivie dans le journal d\'audit. Le journal d\'audit doit être activé avant que les journaux ne soient stockés, car cela prend de l\'espace de stockage.',
    ONBOARDING_AUTOMATION_DIRECT_PROCESSING: 'Traitement Direct',
    ONBOARDING_INTEGRATION_OPENING_MESSAGE: 'Vous avez choisi Salesforce en raison de sa flexibilité pour intégrer tous vos processus d’affaires. Nos plugins Apex, Actions Flux, Plugins Api et SFDX assurent une intégration transparente de la déduplication avec vos processus existants.',
    ONBOARDING_INTEGRATION_APEX_API: 'Duplicate Check API Apex',
    ONBOARDING_INTEGRATION_APEX_API_DESCRIPTION: 'Duplicate Check fournit une API Apex qui vous permet d\'implémenter toutes les fonctionnalités DC dans vos propres projets Apex. Cela inclut la recherche d\'enregistrements en double à l\'aide du moteur de recherche DC, la fusion et la conversion, mais cela vous permet également d\'exporter des ensembles de configuration DC via l\'API.',
    ONBOARDING_INTEGRATION_REST_API: 'Duplicate Check API REST',
    ONBOARDING_INTEGRATION_REST_API_DESCRIPTION: 'Duplicate Check offre une API REST qui peut être utilisée pour rechercher ou insérer/mettre à jour des enregistrements dans Salesforce via l\'API de données. L\'API REST Data vous permet de créer des enregistrements sans créer de doublons. Lorsqu\'un enregistrement est ajouté via l\'API de données, il est directement comparé à tous les enregistrements existants dans Salesforce. Si des doublons sont présents, cela mettra à jour l\'enregistrement existant au lieu de créer un enregistrement en double.',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS: 'Actions Flux de Duplicate Check',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS_DESCRIPTION: 'Duplicate Check offre la plupart de ses fonctionnalités sous la forme d\'une action de flux. Pour cette raison, vous gagnez la capacité d\'implémenter toutes les fonctionnalités liées à la prévention des doublons, à la fusion, à la conversion et plus encore dans n\'importe quel flux de Salesforce.',
    ONBOARDING_CUSTOMISATION_OPENING_MESSAGE: 'Vous avez choisi Salesforce en raison de sa flexibilité pour intégrer tous vos processus d’affaires. Nos plugins Apex, Actions Flux, Api et SFDX assurent une intégration transparente de la déduplication avec vos processus existants.',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS: 'Plugins de Duplicate Check',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS_DESCRIPTION: 'Nous comprenons qu\'une entreprise a des processus très spécifiques et qu\'il est difficile de trouver un outil capable de s\'adapter aux exigences difficiles. Utilisez les plugins que Duplicate Check offre si vous souhaitez apporter des modifications à la fonctionnalité "Out-of-the-box".',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS: 'Plugins SFDX',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS_DESCRIPTION: 'Les plugins SFDX permettent aux développeurs d\'automatiser les tâches liées aux licences de Duplicate Check ainsi que les configurations de Duplicate Check. Par exemple, si vous avez un pipeline construit avec des environnements de pré-production différents, vous pouvez automatiser la synchronisation de la configuration de Duplicate Check de sorte qu\'il soit le même dans tous les environnements.',
    ONBOARDING_GET_STARTED_A_LOT_OF_INFO: 'C’est beaucoup d’informations, n’est-ce pas?',
    ONBOARDING_GET_STARTED_OPENING_MESSAGE: 'Vous connaissez maintenant les bases de ce que Duplicate Check peut faire. Nous savons qu\'il y a beaucoup à faire. Vous êtes maintenant prêt à commencer votre voyage vers un environnement Salesforce sans duplication, avec tous les avantages incroyables qu\'il procurera.',
    ONBOARDING_GET_STARTED_FEELING_LOST: 'Vous vous sentez perdu ? N\'hésitez pas à planifier une session en personne avec l\'un de nos experts en produits.',
    ONBOARDING_GET_STARTED_SCHEDULE_CALL: 'Planifiez un appel avec l\'un de nos Experts en Produits !',
    ONBOARDING_GET_STARTED_FLYING_START: 'Vous voulez avoir un vol de commencer à implémenter Duplicate Check pour votre organisation ? N\'hésitez pas à planifier un appel avec l\'un de nos experts en produits gratuitement. Nous serions ravis de vous guider dans l\'exploration et la configuration de Duplicate Check.',
    ONBOARDING_GET_STARTED_SCHEDULE_A_CALL: 'Planifier un appel',
    ONBOARDING_GET_STARTED_INTERESTING_LINKS: 'Liens intéressants',
    ONBOARDING_GET_STARTED_SCHEDULE_PRODUCT_EXPERT: 'Planifier un appel avec un Expert Produit',
    ONBOARDING_GET_STARTED_KNOWLEDGEBASE: 'Base de connaissances',
    ONBOARDING_GET_STARTED_HOWTO_VIDEOS: 'Tutoriels en vidéo',
    ONBOARDING_GET_STARTED_GUIDE: 'Guide de démarrage',
    ONBOARDING_GET_STARTED_CONTACT_SUPPORT: 'Contacter le Service Client',
    general: {
        DCJOB_AUTOCONVERT_LEARNMORE: 'En Savoir Plus',
        DCJOB_AUTOMERGE_LEARNMORE: 'En Savoir Plus',
        DCJOB_NEWJOB_LEARNMORE: 'En Savoir Plus',
        DCJOB_AUTOMERGE_SPEED: 'Rapidité',
        DCJOB_NEWJOB_SPEED: 'Rapidité',
        DCJOB_NEWJOB_MEDIUM: 'Moyen',
        DCJOB_AUTOMERGE_MEDIUM: 'Moyen',
        DCJOB_NEWJOB_RECOMMENDED: 'Recommandé',
        DCJOB_AUTOMERGE_RECOMMENDED: 'Recommandé',
        DCJOB_AUTOCONVERT_RECOMMENDED: 'Recommandé',
        DCJOB_DELETEMODAL_ALLTIME: 'Depuis toujours',
        DCJOB_DELETEMODAL_SETDATE: 'Définir la date',
        DCJOB_DELETEMODAL_SETDATERANGE: 'Définir la plage de dates',
        DCJOB_DELETEMODAL_FROM: 'A partir de',
        DCJOB_DELETEMODAL_UNTIL: 'Jusqu\'au',
        DCJOB_DELETEMODAL_TYPE: 'Type de texte',
        DCJOB_DELETEMODAL_DATE: 'Date',
        DCJOB_JOBPAGE_OBJECT: 'Objet',
        DCJOB_SCHEDULEDJOBPAGE_OBJECT: 'Objet',
        DCJOB_SCHEDULEDJOBPAGE_NOTAPPLICABLE: 'N / A',
        DCJOB_SCHEDULEDJOBPAGE_NOME: 'Nom',
        DCJOB_SCHEDULEDJOBPAGE_FREQUENCYANDTIME: 'Fréquence & Heure',
        DCJOB_SCHEDULEDJOBPAGE_STATUS: 'Statut',
        DCJOB_SCHEDULEDJOBPAGE_NEXTSTART: 'Prochain début',
        DCJOB_PAGINATIONCOMPONENT_PAGE: 'Page',
        DCJOB_PAGINATIONCOMPONENT_OF: 'de',
    },
    groupObject: {
        GROUPNUMBER: 'Numéro du Groupe',
        GROUPPAIRCOUNT: 'Nombre de Paires de Groupe',
        GROUPRECORDCOUNT: 'Nombre d\'enregistrements de groupe',
        GROUPCONTAINSMERGEERROR: 'Le groupe contient une erreur de fusion',
        GROUPCONTAINSCONVERTERROR: 'Le groupe contient une erreur de conversion',
        GROUPFOUNDJOB: 'Found in Job',
    },
    days: {
        DCJOB_NEWJOB_MONDAY: 'Lundi',
        DCJOB_NEWJOB_TUESDAY: 'Mardi',
        DCJOB_NEWJOB_WEDNESDAY: 'Mercredi',
        DCJOB_NEWJOB_THURSDAY: 'Jeudi',
        DCJOB_NEWJOB_FRIDAY: 'Vendredi',
        DCJOB_NEWJOB_SATURDAY: 'Samedi',
        DCJOB_NEWJOB_SUNDAY: 'Dimanche',
    },
    monthly: {
        LAST_DAY: 'Dernier jour',
        LAST_WEEKDAY: 'Jour de la semaine dernière',
    },
    frequency: {
        DCJOB_SCHEDULED_FREQUENCY_PLACEHOLDER: 'Sélectionnez une option...',
        DCJOB_SCHEDULED_FREQUENCY_DAILY: 'Journalière',
        DCJOB_SCHEDULED_FREQUENCY_WEEKLY: 'Hebdomadaire',
        DCJOB_SCHEDULED_FREQUENCY_MONTHLY: 'Mensuelle',
        DCJOB_SCHEDULED_FREQUENCY_CUSTOM: 'Personnalisé',
    },
    titles: {
        DCJOB_JOBPAGE_JOBOVERVIEW: 'Aperçu des Jobs',
        DCJOB_SCHEDULEDJOBPAGE_SCHEDULEDJOB: 'Aperçu des Jobs Planifiés',
        DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOB: 'Supprimer les Jobs Planifiées',
        DCJOB_JOBPAGE_LISTVIEWS: 'VUES DE LISTE',
    },
    buttons: {
        DCJOB_JOBCARD_ABORT: 'Abandonner',
        DCJOB_BACK: 'Retour',
        DCJOB_NEWJOB_BACK: 'Retour',
        DCJOB_AUTOMERGE_BACK: 'Retour',
        DCJOB_AUTOCONVERT_BACK: 'Retour',
        DCJOB_JOBPAGE_CANCEL: 'Annuler',
        DCJOB_NEWJOB_CANCEL: 'Annuler',
        DCJOB_JOBCARD_CANCEL: 'Annuler',
        DCJOB_EXPORTMODAL_CANCEL: 'Annuler',
        DCJOB_DELETEMODAL_CANCEL: 'Annuler',
        DCJOB_AUTOMERGE_CANCEL: 'Annuler',
        DCJOB_AUTOCONVERT_CANCEL: 'Annuler',
        DCJOB_SCHEDULEDJOBPAGE_CANCEL: 'Annuler',
        DCJOB_SCHEDULEDJOBPAGE_DELETEJOBS: 'Supprimer les Jobs',
        DCJOB_JOBPAGE_DELETEJOBS: 'Supprimer les Jobs',
        DCJOB_DELETEMODAL_DELETEJOBS: 'Supprimer les Jobs',
        DCJOB_SCHEDULEDJOBPAGE_DELETE: 'Supprimer',
        DCJOB_JOBCARD_DELETE: 'Supprimer',
        DCJOB_DELETEMODAL_DELETE: 'Supprimer',
        DCJOB_EXPORTMODAL_EXPORTDCLOCAL: 'Exporter via DC Local',
        DCJOB_EXPORTMODAL_EXPORTCLOUD: 'Exporter via Plauti Cloud',
        DCJOB_JOBPAGE_FILTER: 'Filtre',
        DCJOB_NEWJOB_FILTER: 'Filtre',
        DCJOB_FILTER: 'Filter',
        DCJOB_SCHEDULEDJOBPAGE_INFO: 'Informations',
        DCJOB_JOBCARD_INFO: 'Informations',
        DCJOB_SCHEDULEDJOBPAGE_EDIT: 'Modifier',
        DCJOB_SCHEDULEDJOBPAGE_JOBOPTIONS: 'Options des Jobs',
        DCJOB_JOBCARD_JOBOPTIONS: 'Options des Jobs',
        DCJOB_SCHEDULEDJOBPAGE_NEWJOB: 'Nouveau Job',
        DCJOB_JOBPAGE_NEWJOB: 'Nouveau Job',
        DCJOB_NEWJOB_NEXT: 'Suivant',
        DCJOB_AUTOMERGE_NEXT: 'Suivant',
        DCJOB_AUTOCONVERT_NEXT: 'Suivant',
        DCJOB_JOBPAGE_SAVE: 'Enregistrer',
        DCJOB_NEWJOB_START: 'Démarrer',
        DCJOB_NEWJOB_SCHEDULE: 'Planification',
        DCJOB_AUTOMERGE_START: 'Démarrer',
        DCJOB_AUTOCONVERT_START: 'Démarrer',
        DCJOB_JOBPAGE_SORTJOBS: 'Trier les Jobs',
        DCJOB_SCHEDULEDJOBPAGE_RUNNOW: 'Exécuter une fois maintenant',
        DCJOB_SCHEDULEDJOBPAGE_DEACTIVATED: 'Désactiver',
        DCJOB_SCHEDULEDJOBPAGE_ACTIVATE: 'Activer',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS_NUMBER: 'Voir les résultats {0}',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS: 'Afficher les Résultats',
        MERGE: 'Fusionner',
        QUICKMERGE: 'Fusion Rapide',
        QUICKCONVERT: 'Conversion Rapide',
        MORE: 'En savoir plus',
        edit: 'Modifier',
        DCJOB_JOBCARD_VIEWRESULTS: 'Voir les résultats {0}',
        DCJOB_JOBPAGE_DELETESELECTEDJOBS: 'Delete Selected Jobs',
        DCJOB_JOBPAGE_SELECTALL: 'Select All',
        DCJOB_JOBPAGE_DESELECTALL: 'Deselect All',
    },
    badges: {
        DCJOB_JOBCARD_REVIEWERRORS: 'Revoir les erreurs',
        DCJOB_JOBCARD_READMORE: 'En savoir plus',
        DCJOB_JOBCARD_LIMITTEXT: 'Limite d\'enregistrement de la licence atteinte',
        DCJOB_JOBCARD_DELETESELECTED: `{count} job selected | {count} jobs selected`,
    },
    metaData: {
        DCJOB_JOBPAGE_AVERAGESCORE: 'Score Moyen',
        DCJOB_OVERALLJOBRESULTS_AVERAGESCORE: 'Score Moyen',
        DCJOB_JOBPAGE_STORAGESPACETAKEN: 'Espace de stockage pris',
        DCJOB_JOBPAGE_TOTALGROUPS: 'Nombre total de groupes',
        DCJOB_JOBPAGE_TOTALJOBS: 'Jobs totales',
        DCJOB_JOBPAGE_TOTALPAIRS: 'Total Pairs',
        DCJOB_JOBPAGE_TOTALRECORDS: 'Nombre total d\'enregistrements',
        DCJOB_OVERALLJOBRESULTS_RECORDS: 'Enregistrements',
        DCJOB_OVERALLJOBRESULTS_GROUPS: 'Groupes',
        DCJOB_OVERALLJOBRESULTS_PAIRS: 'Paires',
        DCJOB_OVERALLJOBRESULTS_OBJECT: 'Objet',
    },
    job: {
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDTITLE: 'Le journal d\'audit n\'est pas disponible dans votre licence',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDSUBTITLE: 'Le Journal d\'Audit est disponible en Premium et supérieur',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDBUTTON: 'Mettre à niveau maintenant',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDRUPGRADEURL: 'https://go.plauti.com/l/640773/2023-03-27/53tydt',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDTITLE: 'Journal d\'audit désactivé',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDSUBTITLE: 'Veuillez demander à votre administrateur Salesforce d\'activer le Journal d\'Audit de Duplicate Check.',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGETITLE: 'Le Journal de Fusion est vide',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTTITLE: 'Le Journal de Conversion est vide',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGESUBTITLE: 'Il n\'y avait pas encore d\'activité de fusion pour ce job.',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTSUBTITLE: 'Il n\'y avait pas encore d\'activité de conversion pour ce job.',
        DCJOB_AUDITLOGTABLEHEADER_MASTERRECORD: 'Enregistrement Principal',
        DCJOB_AUDITLOGTABLEHEADER_MERGEDRECORDS: 'Enregistrement(s) fusionné(s)',
        DCJOB_AUDITLOGTABLEHEADER_LEADRECORD: 'Enregistrement de Piste',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOPERSON: 'Convertir en Compte Personnel',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOACCOUNT: 'Convertir en Compte',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOCONTACT: 'Convertir en Contact',
        DCJOB_AUDITLOGTABLEHEADER_METHOD: 'Méthode',
        DCJOB_AUDITLOGTABLEHEADER_DATETIME: 'Date et heure',
        DCJOB_AUDITLOGTABLEHEADER_USER: 'Utilisateur',
        DCJOB_AUDITLOGTOOLTIP_CONVERTEDRECORD: 'Enregistrement converti',
        DCJOB_AUDITLOGTOOLTIP_MERGEDRECORD: 'Enregistrement fusionné',
        DCJOB_AUDITLOGTOOLTIP_RECORDID: 'ID de l\'enregistrement:',
        DCJOB_AUDITLOGTOOLTIP_AUDITID: 'ID de l\'audit :',
        DCJOB_AUDITLOGSUMMARY_NUMBEROFRECORDS: 'Nombre d\'enregistrements {0}',
        DCJOB_JOBCARD_JOBS: 'Jobs',
        DCJOB_JOBCARD_TASK: 'Tâche',
        DCJOB_JOBCARD_STARTED: 'Démarré en',
        DCJOB_JOBCARD_FINISHED: 'Terminé à',
        DCJOB_JOBCARD_USER: 'Démarré par',
        DCJOB_JOBCARD_STATUS: 'Statut',
        DCJOB_JOBPAGE_STATUS: 'Statut',
        DCJOB_JOBCARD_RESULT: 'Résultat',
        DCJOB_JOBPAGE_JOBNAME: 'Nom du Job',
        DCJOB_NEWJOB_JOBNAME: 'Nom du Job',
        DCJOB_JOBCARD_JOBNAME: 'Nom du Job',
        DCJOB_AUTOMERGE_JOBNAME: 'Nom du Job',
        DCJOB_AUTOCONVERT_JOBNAME: 'Nom du Job',
        DCJOB_JOBPAGE_JOBID: 'ID de job',
        DCJOB_JOBCARD_JOBID: 'ID de job',
        DCJOB_JOBPAGE_NOJOBS: 'Aucun emploi.',
        DCJOB_SCHEDULEDJOBPAGE_NOSCHEDULEDJOBS: 'Aucun job planifié.',
        DCJOB_NEWJOB_JOBNAMEPLACEHOLDER: 'Veuillez insérer un nom de job',
        DCJOB_JOBCARD_AUTOMERGE: 'Fusion Automatique',
        DCJOB_JOBCARD_MANUALMERGE: 'Fusion manuelle',
        DCJOB_JOBCARD_QUICKMERGE: 'Fusion Rapide',
        DCJOB_JOBCARD_AUTOCONVERT: 'Conversion Automatique',
        DCJOB_JOBCARD_MANUALCONVERT: 'Conversion manuelle',
        DCJOB_JOBCARD_MERGELOG: 'Journal de Fusion',
        DCJOB_JOBCARD_CONVERTLOG: 'Journal de Conversion',
        DCJOB_JOBCARD_QUICKCONVERT: 'Conversion Rapide',
        DCJOB_JOBCARD_AUTOMERGEDCLOCAL: 'Fusion automatique via DC Local',
        DCJOB_JOBCARD_AUTOMERGECLOUD: 'Fusion automatique via Plauti Cloud',
        DCJOB_AUTOMERGE_CONFIGUREAUTOMERGE: 'Configurer la fusion automatique',
        DCJOB_AUTOCONVERT_CONFIGUREAUTOCONVERT: 'Configurer la conversion automatique',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE: 'Je reconnais que le démarrage de ce job de fusion automatique va fusionner les enregistrements en double {0} et que la fusion des enregistrements ne peut pas être annulée.',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'Je reconnais que le démarrage de ce job de fusion automatique va fusionner les enregistrements en double et que la fusion des enregistrements ne peut pas être annulée.',
        DCJOB_EXPORTMODAL_EXPORTRESULTS: 'Exporter les Résultats',
        DCJOB_JOBCARD_EXPORTRESULTSDCLOCAL: 'Exporter les résultats via DC Local',
        DCJOB_JOBCARD_EXPORTRESULTSCLOUD: 'Exporter les résultats via Plauti Cloud',
        DCJOB_JOBCARD_NUMBEROFRECORDS: 'Nombre d\'enregistrements',
        DCJOB_JOBPAGE_NUMBEROFRECORDS: 'Nombre d\'enregistrements',
        DCJOB_JOBCARD_NUMBEROFPAIRS: 'Nombre de paires',
        DCJOB_JOBCARD_RESULTFIELDS: 'Champs de Résultat',
        DCJOB_AUTOMERGE_CONFIRMATION: 'Valider',
        DCJOB_AUTOCONVERT_CONFIRMATION: 'Valider',
        DCJOB_AUTOMERGE_PROCESSEDBY: 'Transformé par',
        DCJOB_AUTOCONVERT_PROCESSEDBY: 'Transformé par',
        DCJOB_DELETEMODAL_CURRENTNUMBEROFJOBS: 'Nombre actuel des jobs en DC Job',
        DCJOB_DELETEMODAL_JOBSCREATEDAT: 'Jobs créés à',
        DCJOB_DELETEMODAL_CONTAINSDUPLICATERESULTS: 'Contient les résultats en double',
        DCJOB_DELETEMODAL_JOBSSELECTEDFORDELETION: 'Nombre de jobs sélectionnés pour la suppression',

        infoModal: {
            DCJOB_INFOMODAL_GENERALINFO_STARTEDBYUSER: 'Démarré par l\'utilisateur',
            DCJOB_INFOMODAL_GENERALINFO_STATUS: 'Statut',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMESTARTED: 'Date et heure de démarrage',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMEFINISHED: 'Date et heure de fin',
            DCJOB_INFOMODAL_GENERALINFO_TOTALTIMETAKEN: 'Duré totale',
            DCJOB_INFOMODAL_GENERALINFO_PROCESSEDBY: 'Transformé par',
            DCJOB_INFOMODAL_GENERALINFO_LASTDUPLICATEADDED: 'Dernier doublon ajouté',
            DCJOB_INFOMODAL_GENERALINFO_APPLIEDSCENARIOS: 'Scénarios appliqués',
            DCJOB_INFOMODAL_GENERALINFO_JOBID: 'ID de job',
            DCJOB_INFOMODAL_GENERALINFO_APEXJOBID: 'ID Job Apex',
            DCJOB_INFOMODAL_GENERALINFO_CREATEDBYUSER: 'Créé par l\'utilisateur',
            DCJOB_INFOMODAL_GENERALINFO_FREQUENCY: 'Fréquence',
            DCJOB_INFOMODAL_GENERALINFO_LASTRUNAT: 'Dernière exécution à',
            DCJOB_INFOMODAL_GENERALINFO_NEXTRUNAT: 'Prochaine exécution à',
            DCJOB_INFOMODAL_GENERALINFO_NUMBEROFTIMESRUN: 'Nombre d\'exécutions',
            DCJOB_INFOMODAL_GENERALINFO_AUTOPROCESS: 'Auto process',
            DCJOB_INFOMODAL_GENERALINFO_SCHEDULED_LASTMODIFIED: 'Dernière modification du Job Planifié par + Date & Heure',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEGROUPS: 'Groupes de Doublons',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEPAIRS: 'Paires de Doublons',
            DCJOB_INFOMODAL_DUPLICATESINFO_RECORDSINVOLVED: 'Enregistrements en cours',
            DCJOB_INFOMODAL_DUPLICATESINFO_AVERAGESCORE: 'Score Moyen',
            DCJOB_INFOMODAL_SELECTEDINFO_OBJECT: 'Objet',
            DCJOB_INFOMODAL_SELECTEDINFO_NUMBEROFRECORDS: 'Nombre d\'enregistrements',
            DCJOB_INFOMODAL_SELECTEDINFO_SOURCE: 'Source',
            DCJOB_INFOMODAL_SELECTEDINFO_MATCH: 'Match'
        },
        sortOptions: {
            DCJOB_JOBPAGE_SORTBY: 'Trier par',
            DCJOB_JOBPAGE_DATETIMESTARTED: 'Démarré en',
            DCJOB_JOBPAGE_DATETIMEFINISHED: 'Terminé à',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEGROUPS: 'Nombre de Groupes de Doublons',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEPAIRS: 'Nombre de paires de doublons',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATERECORDSINVOLVED: 'Nombre d\'enregistrements en double impliqués',
            DCJOB_JOBPAGE_LASTDUPLICATEADDED: 'Dernier doublon ajouté',
            DCJOB_JOBPAGE_ORDER: 'Ordre',
            DCJOB_JOBPAGE_ASCENDING: 'Croissant',
            DCJOB_JOBPAGE_DESCENDING: 'Descendant',
        },
        menuOptions: {
            DCJOB_SCHEDULEDJOBPAGE_TITLE: 'Options des Jobs',
            DCJOB_JOBCARD_TITLE: 'Options des Jobs',
            DCJOB_JOBCARD_OPTION_RESTART: 'Redémarrer',
            DCJOB_JOBCARD_OPTION_STARTAUTOMERGE: 'Démarrer la fusion automatique',
            DCJOB_JOBCARD_OPTION_STARTAUTOCONVERT: 'Démarrer la conversion automatique',
            DCJOB_JOBCARD_OPTION_EXPORTRESULTS: 'Exporter les Résultats',
            DCJOB_JOBCARD_OPTION_SHAREJOB: 'Partager le Job',
            DCJOB_JOBCARD_OPTION_DELETEJOB: 'Supprimer le Job',
        },

        new: {
            DCJOB_NEWJOB_STEP: 'Étape',
            DCJOB_AUTOMERGE_STEP: 'Étape',
            DCJOB_AUTOCONVERT_STEP: 'Étape',
            DCJOB_NEWJOB_SELECTRECORDS: 'Sélectionnez les Enregistrements',
            DCJOB_NEWJOB_JOBOPTIONS: 'Options des Jobs',
            DCJOB_NEWJOB_PROCESSOPTIONS: 'Options du processus',
            DCJOB_NEWJOB_SELECTOBJECT: 'Sélectionner un Objet',
            DCJOB_NEWJOB_SELECTOBJECTPLACEHOLDER: 'Veuillez sélectionner un objet',
            DCJOB_NEWJOB_SELECTOPTIONSPLACEHOLDER: 'Options de recherche...',
            DCJOB_NEWJOB_ADDCROSSOBJECT: 'Ajouter un objet croisé',
            DCJOB_NEWJOB_REMOVECROSSOBJECT: 'Supprimer l\'objet croisé',
            DCJOB_NEWJOB_ADDFILTER: 'Ajouter un Filtre',
            DCJOB_NEWJOB_MATCHWITH: 'Comparer avec',
        },

        deleteAll: {
            DCJOB_DELETESELECTED_TITLE: 'Delete Selected Jobs',
            DCJOB_DELETESELECTED_MESSAGE: 'Are you sure you want to delete {count} selected job? This action cannot be undone. | Are you sure you want to delete {count} selected jobs? This action cannot be undone.',
        },

        delete: {
            DCJOB_DELETEMODAL_DELETEJOBSMESSAGE: 'Êtes-vous sûr de vouloir supprimer les Jobs {0} ? La suppression des Jobs ne peut pas être annulée.',
            DCJOB_JOBCARD_DELETEMESSAGE: 'Êtes-vous sûr de vouloir supprimer {0}?',
            DCJOB_JOBCARD_DELETEUNDONE: 'La suppression de {0} ne peut pas être annulée.',
            DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOBMESSAGE: 'Êtes-vous sûr de vouloir supprimer le job de planification «{0}» ?',
        },

        options: {
            DCJOB_NEWJOB_SCHEDULE: 'Planification',
            addScheduler: 'Ajouter un planificateur',
            scheduleDescription: 'Décidez de planifier ce lot pour qu\'il s\'exécute à une fréquence et une heure configurées.',
            autoMergeDescription: 'Décider d\'ajouter un seuil pour automatiquement fusionner les enregistrements en double dès que le lot est terminé. Veuillez ne pas qu\'une fusion automatique puisse également être démarrée manuellement à tout moment.',
            DCJOB_NEWJOB_REMOVESCHEDULER: 'Supprimer le calendrier',
            addAutoMerge: 'Ajouter la fusion automatique',
            removeAutoMerge: 'Supprimer la fusion automatique',
            DCJOB_NEWJOB_FREQUENCY: 'Fréquence',
            DCJOB_NEWJOB_CRONSTRING: 'Chaîne de caractères Cron',
            DCJOB_NEWJOB_CRONSTRING_INFO: 'Utilisez le format de chaîne Cron \* * * * * * *\ pour planifier les jobs DC en spécifiant des secondes, minute, heure, jour, mois et jour de la semaine.',
            DCJOB_NEWJOB_RECURS: 'Se reproduit chaque semaine le',
            DCJOB_NEWJOB_MONTHRECURS: 'Se reproduit chaque mois le',
            DCJOB_NEWJOB_PREFERREDSTARTTIME: 'Heure de Démarrage Préférée',
            DCJOB_NEWJOB_PREFERREDSTARTTIMEINFO: 'Salesforce planifie le job DC pour un démarrage à l\'heure spécifiée. Le démarrage réel peut être retardée en fonction de la disponibilité du service.',
            DCJOB_AUTOMERGE_AUTOMERGETHRESHOLD: 'Seuil de fusion automatique',
            DCJOB_AUTOMERGE_AUTOMERGETEXT: 'Une fois le job terminé, toutes les paires de doublons avec un pourcentage correspondant égal ou supérieur à {0}% sont automatiquement fusionnées.',
            DCJOB_NEWJOB_AUTOMERGETEXT: 'Une fois le job terminé, toutes les paires de doublons avec un pourcentage correspondant égal ou supérieur à {0}% sont automatiquement fusionnées.',
            DCJOB_NEWJOB_AUTOCONVERTEXPLANATION: 'Toutes les paires de doublons avec un pourcentage correspondant égal ou supérieur à {0}% sont automatiquement converties.',
            DCJOB_AUTOCONVERT_AUTOCONVERTEXPLANATION: 'Toutes les paires de doublons avec un pourcentage correspondant égal ou supérieur à {0}% sont automatiquement converties.',
            DCJOB_AUTOMERGE_AUTOMERGEWARNING: 'La fusion des enregistrements ne peut pas être annulée.',
            DCJOB_NEWJOB_PROCESSINGOPTIONS: 'Options de traitement',
            DCJOB_AUTOMERGE_PROCESSINGOPTIONS: 'Options de traitement',
            DCJOB_AUTOCONVERT_PROCESSINGOPTIONS: 'Options de traitement',
            DCJOB_NEWJOB_RUNONSF: 'Exécuter sur la Plateforme Salesforce',
            DCJOB_AUTOMERGE_RUNONSF: 'Exécuter sur la Plateforme Salesforce',
            DCJOB_AUTOCONVERT_RUNONSF: 'Exécuter sur la Plateforme Salesforce',
            DCJOB_NEWJOB_RUNONDCLOCAL: 'Exécuter sur DC Local',
            DCJOB_AUTOMERGE_RUNONDCLOCAL: 'Exécuter sur DC Local',
            DCJOB_AUTOCONVERT_RUNONDCLOCAL: 'Exécuter sur DC Local',
            DCJOB_AUTOMERGE_SFINFO: 'En fonction du nombre de paires de doublons sélectionnées pour le processus de fusion automatique, nous vous recommandons de traiter le job sur la plateforme Salesforce.',
            DCJOB_AUTOCONVERT_SFINFO: 'En fonction du nombre de paires de doublons sélectionnées pour le processus de fusion automatique, nous vous recommandons de traiter le job sur la plateforme Salesforce.',
            DCJOB_AUTOMERGE_DCLOCALINFO: 'En fonction du nombre de paires de doublons sélectionnées pour le processus de fusion automatique, nous vous recommandons de traiter le job sur DC Local.',
            DCJOB_AUTOCONVERT_DCLOCALINFO: 'En fonction du nombre de paires de doublons sélectionnées pour le processus de conversion automatique, nous vous recommandons de traiter le job sur DC Local.',
            DCJOB_AUTOMERGE_SFPLATFORMMESSAGE: 'Exécutez ce job sur la Plateforme Salesforce (native).',
            DCJOB_AUTOMERGE_DCLOCALMESSAGE: 'Exécutez ce job en utilisant DC Local Desktop ou DC Local server.',
            DCJOB_AUTOMERGE_ADDOBJECTFILTER: 'Ajouter un filtre {0}',
            DCJOB_AUTOMERGE_REMOVEOBJECTFILTER: 'Supprimer le filtre {0}',
            DCJOB_AUTOMERGE_ADDFILTERLINE: 'Ajouter une ligne de filtre',
            DCJOB_AUTOCONVERT_ADDFILTERLINE: 'Ajouter une ligne de filtre',
            DCJOB_AUTOMERGE_OBJECTFILTER: 'Filtre {0}',
        },
    },
    scenario: {
        DCJOB_NEWJOB_SCENARIO: 'Scénario',
        DCJOB_NEWJOB_SCENARIOINFO: 'Dans un job objet croisé, seuls les scénarios de l\'objet correspondant sont disponibles.',
        DCJOB_SCENARIOCARD_SCENARIONAME: 'Nom du Scénario',
        DCJOB_SCENARIOCARD_THRESHOLD: 'Seuil',
        DCJOB_SCENARIOCARD_EMPTYFIELDS: 'Champs vides',
        fields: {
            DCJOB_SCENARIOCARD_FIELD: 'Champ',
            DCJOB_SCENARIOCARD_FREQUENTWORDS: 'Mots Fréquents',
            DCJOB_SCENARIOCARD_MATCHINGMETHOD: 'Méthode de Correspondance',
            DCJOB_SCENARIOCARD_WEIGHT: 'Poids',
        },
    },
    filter: {
        DCJOB_INFOMODAL_READMOREINFO: 'Après l\'ajout d\'un filtre, le filtre est numéroté. Votre premier filtre devient Filtre 1 et votre deuxième filtre devient Filtre 2. Vous appliquez une logique de filtre basée sur ces filtres numérotés. Cliquez sur l\'icône pour en savoir plus.',
        DCJOB_INFOMODAL_FILTER: 'Filtre',
        DCJOB_INFOMODAL_SOURCEFILTER: 'Filtre source',
        DCJOB_INFOMODAL_MATCHFILTER: 'Filtre de correspondance',
        DCJOB_INFOMODAL_AUTOMERGE_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOMERGE_GROUPFILTER: 'Auto Merge Group Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_GROUPFILTER: 'Auto Convert Group Filter',
        DCJOB_JOBPAGE_FILTERJOBS: 'Filtrer les Jobs',
        DCJOB_JOBPAGE_NOFILTERAPPLIED: 'Aucun filtre appliqué.',
        addFilter: 'Ajouter un Filtre',
        operators: {
            DCJOB_SCHEDULEDJOBPAGE_OR: 'OU',
            DCJOB_JOBINFO_OR: 'OU',
        },
        removeFilter: 'Supprimer le filtre',
        DCJOB_NEWJOB_SETFILTER: 'Définir le filtre',
        DCJOB_NEWJOB_ALLRECORDS: 'Aucun filtre, traiter tous les enregistrements',
        DCJOB_NEWJOB_COMPARERECORDSINABOVEFILTERWITH: 'Comparer les enregistrements dans le filtre ci-dessus avec',
        DCJOB_NEWJOB_RECORDSTHATMEETCRITERIA: 'Enregistrements qui répondent aux critères de filtre ci-dessus',
        jobFilterFields: {
            DCJOB_JOBPAGE_STARTEDBYUSER: 'Démarré à l\'Utilisateur',
            DCJOB_JOBPAGE_CONTAINSFILTER: 'Contient un filtre',
            DCJOB_JOBPAGE_CONTAINSAUTOMERGE: 'Contient la fusion automatique',
            DCJOB_JOBPAGE_CONSTAINSAUTOCONVERT: 'Contient la conversion automatique',
        },
        startedScheduledJob: '{0} est maintenant en cours d\'exécution',
        activeScheduledJob: '{0} est maintenant activé',
        deactivatedScheduledJob: '{0} est maintenant désactivé',
        DCJOB_JOBPAGE_FILTERSAVED: 'Filtre enregistré avec succès.',
        addFilterlineLabel: 'Ajouter une ligne de filtre',
        newFilterlinePlaceholder: 'Ajouter une ligne de filtre',
        fieldLabel: 'Champ',
        fieldPlaceholder: 'Sélectionnez une option...',
        fieldPlaceholderSearch: 'Options de recherche...',
        operatorLabel: 'Opérateur',
        emptyValueLabel: 'Vide',
        emptyOptionLabel: '- none -',
        addFilterLogicLabel: 'Ajouter une logique de filtre',
        removeFilterLogicLabel: 'Supprimer la logique du filtre',
        doneButton: 'Fait',
        inputLabels: {
            Value: 'Valeur',
            Date: 'Date',
            Time: 'Date et heure',
            'Start date': 'Start Date',
            'End date': 'End Date',
            'Start Time': 'Start Time',
            'End Time': 'End Time',
        },
        logic: {
            ErrorUnusedFilters: 'Il y a une ligne de filtre inutilisée',
            ErrorTypo: 'Il y a une faute de frappe',
            ErrorBadNumber: '{0} peut\t être utilisé dans la logique du filtre',
            ErrorMissingRightOperand: 'Parenthèses manquantes',
            ErrorAmbiguousAndOr: 'Ajouter des parenthèses lors de l\'utilisation d\'AND + OR',
            ErrorMissingOperand: 'NOT devrait être suivi par un opérande',
            ErrorParen: 'Parenthèse inattendue',
        },
    },
    matchingMethods: {
        EQUAL: 'Exactement',
        EQUAL_RANDOM: 'Exactement (ordre aléatoire)',
        NOT_EQUAL: 'Inégal',
        EQUAL_NULL: 'Égale à Null',
        FUZZY_PERSON: 'Nom de la personne',
        FUZZY_COMPANY_EXTRA_STRICT: 'Nom de la société',
        PHONE: 'Numéro de téléphone',
        PHONE_ADVANCED: 'Numéro de téléphone avancé',
        EMAIL_EXACT: 'Adresse e-mail',
        EMAIL: 'E-mail',
        DOMAIN_EXACT: 'Domaine',
        DOMAIN_FUZZY: 'Domaine Partiel',
        URL_EXACT: 'Url',
        URL_FUZZY: 'URL Partiel',
        PRODUCT: 'Numéro de produit',
        POSTAL_CODE: 'Code postal',
        PERSON_NAME: 'Partiel',
        FUZZY_COMPANY: 'Lumière bruyante partielle',
        FUZZY_COMPANY_STRICT: 'Moyen flou partiel',
        COMPANY_NAME: 'Partiellement bruyante',
        COMPANY: 'Société',
        TEXT: 'Texte volumineux',
        DATE_DISTANCE_DAYS: 'Distance de la date en jours',
        HAS_VALUE: 'Contient la valeur',
    },
    frequentWords: {
        STREET: 'Rue',
        COMPANY: 'Société',
        COMMON: 'Commun',
        NAME: 'Noms de personne',
        EMAIL: 'E-mail',
        CUSTOM1: 'Personnalisé 1',
        CUSTOM2: 'Personnalisé 2',
    },
    emptyFieldOptions: {
        DEDUP50: 'Score de 50%',
        DEDUP: 'Score de 100%',
        SEARCH: 'Ignorer',
    },
    pageNavigation: {
        PREVIOUSPAGE: 'Page précédente',
        NEXTPAGE: 'Page suivante',
    },
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTSVIEW: 'Aperçu des résultats en double',
    DCJOB_OVERALLJOBRESULTS_OVERALLJOBRESULTS: 'Résultats globaux du Job',
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTS: 'Résultats en double',
    DCJOB_OVERALLJOBRESULTS_OPENALLGROUPS: 'Ouvrir tous les groupes',
    DCJOB_OVERALLJOBRESULTS_CLOSEALLGROUPS: 'Fermer tous les groupes',
    DCJOB_OVERALLJOBRESULTS_SEARCHUSERS: 'Rechercher des utilisateurs',
    DCJOB_OVERALLJOBRESULTS_APPLYFILTER: 'Appliquer le filtre',
    DCJOB_OVERALLJOBRESULTS_PAIRCOUNT: 'Le nombre de paires',
    DCJOB_OVERALLJOBRESULTS_RECORDCOUNT: 'Le nombre d\'enregistrements',
    DCJOB_OVERALLJOBRESULTS_GROUP: 'Groupe',
    DCJOB_OVERALLJOBRESULTS_MINSCORE: 'Score minimum',
    DCJOB_OVERALLJOBRESULTS_MAXSCORE: 'Score Max.',
    DCJOB_OVERALLJOBRESULTS_AVGSCORE: 'Score moyen',
    DCJOB_OVERALLJOBRESULTS_ONEERROR: '1 erreur',
    DCJOB_OVERALLJOBRESULTS_MERGESELECTEDRECORDS: 'Fusionner les enregistrements sélectionnés',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTION: 'Rejeter la sélection',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTIONFOREVER: 'Rejeter la sélection pour toujours',
    DCJOB_OVERALLJOBRESULTS_DELETINGRECORDSNOTUNDOABLE: 'La suppression des enregistrements ne peut pas être annulée.',
    DCJOB_OVERALLJOBRESULTS_MERGEPAIR: 'Fusionner Paire',
    DCJOB_OVERALLJOBRESULTS_QUICKMERGEPAIR: 'Paire Fusion Rapide',
    DCJOB_OVERALLJOBRESULTS_CONVERTPAIR: 'Convertir Pair',
    DCJOB_OVERALLJOBRESULTS_QUICKCONVERTPAIR: 'Paire de Conversion Rapide',
    DCJOB_OVERALLJOBRESULTS_AREYOUSUREYOUWANTTODELETE: 'Êtes-vous sûr de vouloir supprimer [[insertHTMLWithLink]] de Salesforce',
    DCJOB_OVERALLJOBRESULTS_DELETERECORD: 'Supprimer l\'Enregistrement',
    DCJOB_OVERALLJOBRESULTS_RECORD: 'Enregistrement',
    DCJOB_OVERALLJOBRESULTS_SELECTANOPTION: 'Sélectionnez une option...',
    DCJOB_OVERALLJOBRESULTS_SEARCHOPTIONS: 'Options de recherche...',
    validation: {
        required: 'Ce champ est obligatoire',
        max: 'Ce champ doit contenir moins de {max} caractères',
        invalid_cron_format: 'Chaîne Cron invalide. Veuillez vérifier le format.',
        invalid_seconds_or_minutes: 'Chaîne Cron invalide. Veuillez utiliser uniquement des valeurs numériques pour les secondes et les minutes.',
        invalid_day_of_week_and_day_of_month_combination: 'Chaîne Cron invalide. Veuillez spécifier uniquement le jour de la semaine ou le jour du mois.',
    },
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWPAIRVIEW: 'Basculer vers la vue binaire',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWGROUPVIEW: 'Basculer vers la vue groupe',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFROMJOB: 'Rejeter le groupe du job',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPINJOB: 'Rejeter le groupe dans ce job',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFOREVER: 'Rejeter le groupe pour toujours',
    DCJOB_OVERALLJOBRESULTS_FILTER_JOBTYPE: 'Type de Job',
    DCJOB_OVERALLJOBRESULTS_FILTER_OWNER: 'Propriétaire de {objectName}',
    DCJOB_OVERALLJOBRESULTS_FILTER_RECORDTYPE: 'Type d\'enregistrement {objectName}',
    DCJOB_OVERALLJOBRESULTS_FILTER_PREDEFINED: 'Filtre {objectName} prédéfini',
    DCJOB_OVERALLJOBRESULTS_FILTER_FIELD: '{objectName} {fieldName}',
};
