export default {
    DCJOB_INFOMODALTAB_GENERALINFO: 'Algemene Info',
    DCJOB_INFOMODALTAB_SELECTEDRECORDS: 'Geselecteerde Records',
    DCJOB_INFOMODALTAB_APPLIEDSCENARIOS: 'Toegepaste Scenario\'s',
    DCJOB_INFOMODALTAB_UNPROCESSEDRESULTS: 'Onverwerkte resultaten',
    DCJOB_INFOMODALTAB_DUPLICATERESULTS: 'Duplicaten Gevonden',
    DCJOB_INFOMODALTAB_CONVERTLOG: 'Logboek Conversies',
    DCJOB_INFOMODALTAB_MERGELOG: 'Logboek Samenvoegingen',
    DCJOB_OBJECT_USERS: 'Gebruikers',
    DCJOB_OBJECT_GROUPS: 'Groepen',
    DCJOB_OBJECT_QUEUES: 'Wachtrijen',
    DCJOB_BUTTON_CANCEL: 'Annuleren',
    DCJOB_BUTTON_CALCULATING: 'Recordaantal berekenen',
    DCJOB_BUTTON_TAKINGLONGER: 'Berekening duurt iets langer...',
    DCJOB_BUTTON_NEXTWITHLIMIT: 'Volgende met Limiet',
    DCJOB_BUTTON_ABORTING: 'Afbreken',
    DCJOB_BUTTON_REFRESH: 'Vernieuwen',
    DCJOB_LINK_READMORE: 'Lees meer',
    DCJOB_SHAREMODAL_SHAREMETHOD: 'Manier van Delen',
    DCJOB_SHAREMODAL_LINK: 'Link',
    DCJOB_SHAREMODAL_COPY: 'Kopiëren naar Klembord',
    DCJOB_SHAREMODAL_COPIED: 'Gekopieerd naar Klembord',
    DCJOB_SHAREMODAL_SHAREJOB: 'Job Delen',
    DCJOB_SHAREMODAL_DIRECTLINK: 'Directe Link',
    DCJOB_SHAREMODAL_TASK: 'Taak Aanmaken',
    DCJOB_SHAREMODAL_EMAIL: 'E-mail Sturen',
    DCJOB_SHAREMODAL_RECIPIENTS: 'Ontvangers',
    DCJOB_SHAREMODAL_SUBJECT: 'Onderwerp',
    DCJOB_SHAREMODAL_TEXT: 'Tekst',
    DCJOB_SHAREMODAL_ASSIGNTO: 'Toewijzen aan',
    DCJOB_SHAREMODAL_STATUS: 'Status',
    DCJOB_SHAREMODAL_DUEDATE: 'Vervaldatum',
    DCJOB_SHAREMODAL_DESCRIPTION: 'Beschrijving',
    DCJOB_SHAREMODAL_PRIORITY: 'Prioriteit',
    DCJOB_SHAREMODAL_CREATETASK: 'Taak Aanmaken',
    DCJOB_SHAREMODAL_TASKSUCCESS: 'Taak succesvol aangemaakt',
    DCJOB_SHAREMODAL_EMAILSUCCESS: 'E-mail is verzonden',
    DCJOB_SHAREMODAL_SHAREINFO: 'Om te delen is de {0} variabele nodig. Verwijder deze niet uit het tekstveld.',
    DCJOB_PLACEHOLDER_SEARCH: 'Zoeken',
    DCJOB_PLACEHOLDER_SUBJECT: 'Voer een onderwerp in',
    DCJOB_EDITJOB_SCHEDULE: 'Plannen',
    DCJOB_NEWJOB_RUNONPLAUTICLOUD: 'Uitvoeren op Plauti Cloud',
    DCJOB_NEWJOB_PLAUTICLOUDPROCESSDESCRIPTION: 'Voer deze job uit op Plauti Cloud, een nieuwe verwerkingsoptie aangeboden door Plauti.',
    DCJOB_NEWJOB_FILTERLOGIC: 'Filterlogica',
    DCJOB_NEWJOB_FILTERLOGICDESCRIPTION: 'Na het toevoegen van een filter is het filter genummerd. Het eerste filter wordt filter 1 genummerd, het tweede wordt filter 2, etc. U past filterlogica toe op basis van deze genummerde filters.',
    DCJOB_NEWJOB_ADDSCHEDULE: 'Planning Toevoegen',
    DCJOB_NEWJOB_AUTOCONVERT: 'Automatisch Converteren',
    DCJOB_NEWJOB_AUTOMERGE: 'Automatisch Samenvoegen',
    DCJOB_NEWJOB_ADDAUTOCONVERT: 'Automatisch Converteren Toevoegen',
    DCJOB_NEWJOB_ADDAUTOMERGE: 'Automatisch Samenvoegen Toevoegen',
    DCJOB_NEWJOB_AUTOCONVERTTHRESHOLD: 'Drempel voor Automatisch Converteren',
    DCJOB_NEWJOB_AUTOMERGETHRESHOLD: 'Drempel voor Automatisch Samenvoegen',
    DCJOB_NEWJOB_SCHEDULEDESCRIPTION: 'Plan deze Job om te draaien op een ingestelde frequentie en tijd.',
    DCJOB_NEWJOB_AUTOMERGEDESCRIPTION: 'Voeg een minimale score toe voor het automatisch samenvoegen van dubbele records direct nadat de job is voltooid.',
    DCJOB_NEWJOB_AUTOCONVERTDESCRIPTION: 'Voeg een minimale score toe voor het automatisch converteren van duplicate records direct nadat de job is voltooid.',
    DCJOB_NEWJOB_REMOVEAUTOMERGE: 'Automatisch Samenvoegen verwijderen',
    DCJOB_NEWJOB_REMOVEAUTOCONVERT: 'Automatisch Converteren verwijderen',
    DCJOB_NEWJOB_AUTOCONVERTWARNING: 'Het converteren van records kan niet ongedaan worden gemaakt.',
    DCJOB_NEWJOB_AUTOMERGEWARNING: 'Het samenvoegen van records kan niet ongedaan worden gemaakt.',
    DCJOB_NEWJOB_CONVERTOWNERINFO: 'Leads worden geconverteerd naar het doel-account als een nieuwe Contactpersoon. Bepaal welke gebruiker de eigenaar van de nieuwe Contactpersonen moet zijn.',
    DCJOB_NEWJOB_CONVERTSTATUS: 'Status na conversie',
    DCJOB_NEWJOB_CONVERTOWNER: 'Eigenaar van nieuwe Contactpersoon records',
    DCJOB_NEWJOB_LEADOWNER: 'Huidige Lead-eigenaar',
    DCJOB_NEWJOB_ACCOUNTOWNER: 'Huidige Account-eigenaar',
    DCJOB_NEWJOB_LOOKUPUSER: 'Gebruiker opzoeken',
    DCJOB_NEWJOB_SFPROCESSDESCRIPTION: 'Voer deze job uit op het Salesforce Platform zonder enige gegevensoverdracht.',
    DCJOB_NEWJOB_DCLOCALPROCESSDESCRIPTION: 'Voer deze job uit met DC Local of DC Local server.',
    DCJOB_NEWJOB_RECORDLIMITREACHED: 'Gelicentieerde Recordlimiet bereikt',
    DCJOB_NEWJOB_RECORDLIMITDESCRIPTION: 'Gezien het aantal records dat momenteel is geselecteerd, zal deze job de gelicentieerde recordlimiet bereiken. Als gevolg daarvan zullen niet alle geselecteerde records worden geanalyseerd op duplicaten.',
    DCJOB_NEWJOB_NORECORDSSELECTED: 'Geen records geselecteerd.',
    DCJOB_NEWJOB_SELECTSCENARIO: 'Selecteer ten minste één scenario',
    DCJOB_NEWJOB_NOSCENARIO: 'Geen scenario\'s gevonden voor {0}',
    DCJOB_NEWJOB_NOSELECTIONDESCRIPTION: 'Er zijn momenteel geen records die aan uw filtercriteria voldoen. Overweeg om uw filter te veranderen. U kunt nog steeds doorgaan met het configureren van een geplande job.',
    DCJOB_NEWJOB_SFRECOMMENDATION: 'Op basis van het aantal records dat momenteel is geselecteerd, raden we aan de job op het Salesforce-platform te verwerken. Vanaf 15,000 records en meer wordt het gebruik van DC Local aanbevolen voor betere prestaties.',
    DCJOB_NEWJOB_DCLOCALRECOMMENDATION: 'Op basis van het aantal records dat momenteel is geselecteerd (meer dan 15,000 records), raden we aan de job te verwerken met behulp van DC Local voor betere prestaties.',
    DCJOB_NEWJOB_FILTERNOTFOUND: 'Geselecteerde {0} filter optie "{1}" is niet meer beschikbaar.',
    DCJOB_AUTOCONVERT_DCLOCALMESSAGE: 'Voer deze job uit door gebruik te maken van DC Local of DC Local Server. Momenteel nog niet beschikbaar voor Automatisch Converteren.',
    DCJOB_AUTOCONVERT_CONVERTSTATUS: 'Status na conversie',
    DCJOB_AUTOCONVERT_SELECTEDRECORDS: 'Aantal records geselecteerd voor Automatisch Converteren',
    DCJOB_AUTOCONVERT_NEWCONTACTOWNER: 'Eigenaar van nieuwe Contactpersoon-records',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE: 'Ik erken dat het starten van deze Automatisch Converteren-job {0} dubbele records zal converteren, en dat het converteren van records niet ongedaan kan worden gemaakt',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'Ik erken dat het starten van deze Automatisch Converteren job, dubbele records zal converteren en dat het converteren van records niet ongedaan kan worden gemaakt',
    DCJOB_AUTOCONVERT_NORECORDSSELECTED: 'Er zijn momenteel geen records die aan uw filtercriteria voldoen. Overweeg om uw filter te wijzigen.',
    DCJOB_AUTOCONVERT_TRIALWARNING: 'Automatisch Converteren is beperkt tot 20 records als gevolg van uw proefperiode. Upgrade naar een betaalde licentie om de beperking te verwijderen.',
    DCJOB_AUTOMERGE_FILTERLOGIC: 'Filterlogica',
    DCJOB_AUTOMERGE_FILTERLOGICDESCRIPTION: 'Na het toevoegen van een filter wordt het filter genummerd. Het eerste filter wordt filter 1 genummerd, het tweede wordt filter 2, etc. U past filterlogica toe op basis van deze genummerde filters.',
    DCJOB_AUTOMERGE_SELECTEDRECORDS: 'Aantal records geselecteerd voor Automatisch Samenvoegen',
    DCJOB_AUTOMERGE_SELECTEDDUPLICATEPAIRS: 'Aantal duplicaatparen geselecteerd voor Automatisch Samenvoegen',
    DCJOB_AUTOMERGE_TRIALWARNING: 'Automatisch Samenvoegen is beperkt tot 20 records als gevolg van uw proefperiode. Upgrade naar een betaalde licentie om de beperking te verwijderen.',
    DCJOB_OVERVIEW_PROCESSEDBY: 'Verwerkt door',
    DCJOB_OVERVIEW_DELETINGJOB: 'Job verwijderen',
    DCJOB_OVERVIEW_JOBABORTED: 'Job afgebroken',
    DCJOB_ACCESS_CURRENTUSERNOACCESS: 'Huidige gebruiker heeft geen toegang tot de vereiste klassen',
    DCJOB_ACCESS_REACHOUTTOADMINISTRATOR: 'Neem contact op met uw Salesforce-beheerder',
    DCJOB_ACCESS_DEACTIVATEDCJOBBETA: 'DC Job bèta deactiveren',
    DCJOB_ACCESS_YOUHAVENOACCESS: 'Je hebt geen toegang tot de Apex-klasse genaamd',
    DCJOB_FILTER_JOBTYPE: 'Type Job',
    DCJOB_FILTER_DUPCHECKJOB: 'Duplicaten-Job',
    DCJOB_FILTER_DUPCHECKLOCAL: 'DC Local / Plauti Cloud',
    DCJOB_FILTER_UNIQUEBULKAPIINSERT: 'Unieke Import / Bulk API Insert',
    DCJOB_FILTER_WEBTOLEAD: 'Web-to-Lead',
    DCJOB_FILTER_SETFORMERGE: 'Klaarzetten voor Samenvoegen',
    DCJOB_FILTER_SINGLEAPIINSERT: 'Single API Insert',
    DCJOB_FILTER_FLOW: 'Stroom',
    DCJOB_FILTER_ABORTED: 'Afgebroken',
    DCJOB_FILTER_FAILED: 'Mislukt',
    DCJOB_FILTER_COMPLETED: 'Voltooid',
    DCJOB_FILTER_HOLDING: 'Wachtend',
    DCJOB_FILTER_PROCESSING: 'Bezig',
    DCJOB_FILTER_INCAMPAIGN: 'In Campagne',
    DCJOB_FILTER_FILTER: 'Filter',
    DCJOB_JOBCARD_PROCESSEDWITHDCLOCAL: 'DC Local Job',
    DCJOB_JOBCARD_PROCESSEDWITHCLOUD: 'Plauti Cloud Job',
    DCJOB_JOBPAGE_APEXJOBID: 'Apex Job ID',
    ONBOARDING_NEXT: 'Volgende',
    ONBOARDING_BACK: 'Terug',
    ONBOARDING_FINISH: 'Afronden',
    ONBOARDING_DOCUMENTATION: 'Documentatie',
    ONBOARDING_WATCH_VIDEO: 'Bekijk de video',
    ONBOARDING_GETTING_STARTED: 'Aan de slag met Duplicate Check',
    ONBOARDING_THANK_YOU_FOR_INSTALLING: 'Dank u voor het installeren van Duplicate Check',
    ONBOARDING_RUNNING_A_DC_JOB: 'Een DC-Job uitvoeren',
    ONBOARDING_SETUP_DUPLICATE_PREVENTION: 'Duplicaat-preventie instellen',
    ONBOARDING_LEARN_ABOUT_DCLIVE: 'Meer informatie over DC Live',
    ONBOARDING_HOW_TO_CONFIGURE_DC: 'Hoe configureer ik Duplicate Check',
    ONBOARDING_OPTIONS_FOR_AUTOMATION: 'Opties voor automatisering',
    ONBOARDING_INTEGRATION: 'Integratie',
    ONBOARDING_CUSTOMISATION: 'Aanpassen',
    ONBOARDING_GET_STARTED: 'Laten we beginnen!',
    ONBOARDING_NOTIFICATION_JOB_STARTED: 'DC Job gestart op {0}',
    ONBOARDING_NOTIFICATION_VIEW_PROGRESS: 'Klik om de voortgang in het DC Job Overzicht te bekijken',
    ONBOARDING_JOB_INFO_CARD_OPEN_RESULTS: 'Resultaten Openen',
    ONBOARDING_JOB_INFO_CARD_STATUS: 'status',
    ONBOARDING_JOB_INFO_CARD_RESULT: 'Resultaat',
    ONBOARDING_INTRO_THANK_YOU_FOR_INSTALLING: 'Bedankt voor het installeren van Duplicate Check!',
    ONBOARDING_INTRO_OPENING_MESSAGE: 'Hallo Trailblazer! We zijn blij te zien dat u Duplicate Check for Salesforce heeft geïnstalleerd. U bent nog maar een paar stappen verwijderd van een duplicaatvrije Salesforce-omgeving met nauwkeurige en betrouwbare gegevens. Dit leidt tot betere besluitvorming, een hogere productiviteit en een grotere klanttevredenheid.',
    ONBOARDING_INTRO_START_LOOKING_FOR_DUPLICATES: 'We hebben de vrijheid genomen om op zoek te gaan naar wat duplicaten…',
    ONBOARDING_INTRO_LOOKING_FOR_DUPLICATE_MESSAGE: 'We hebben de vrijheid genomen om snel met duizend {0} records een job te starten, zodat we u kunnen laten zien hoe gemakkelijk het is om duplicate records te vinden in het {0} object. Bekijk het resultaat op een nieuw tabblad door op "Resultaten Openen" te klikken.',
    ONBOARDING_RUN_JOB_OPENING_MESSAGE: 'DC Job is het startpunt voor al uw deduplicatie-inspanningen. Om alle duplicate records in een Salesforce Object te vinden, kunt u een "Duplicate Check Job" uitvoeren, ook wel aangeduid als "DC Job".',
    ONBOARDING_RUN_JOB_START_FIRST_JOB_HELP: 'Laat ons u helpen om uw eerste jobs te starten!',
    ONBOARDING_RUN_JOB_START_NOW: 'Start Nu',
    ONBOARDING_RUN_JOB_STARTED: 'Gestart',
    ONBOARDING_RUN_JOB_LEAD_TITLE: 'Voer een job uit op Leads',
    ONBOARDING_RUN_JOB_LEAD_DESCRIPTION: 'Zoek duplicaten op basis van het vergelijken van Voornaam, Achternaam, E-mail, Bedrijf en Telefoon.',
    ONBOARDING_RUN_JOB_CONTACT_TITLE: 'Voer een job uit op Contacten',
    ONBOARDING_RUN_JOB_CONTACT_DESCRIPTION: 'Zoek duplicaten door het vergelijken van Voornaam, Achternaam, E-mail en Telefoon.',
    ONBOARDING_RUN_JOB_ACCOUNT_TITLE: 'Voer een job uit op Accounts',
    ONBOARDING_RUN_JOB_ACCOUNT_DESCRIPTION: 'Vind duplicaten door het vergelijken van Bedrijfsnaam, Factuurstad en Telefoon.',
    ONBOARDING_RUN_JOB_THINGS_TO_KNOW: 'Dingen die u moet weten over DC-Jobs',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_FEATURE: 'cross-object functie',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_MESSAGE: 'Met de {0}, vergelijk records in elk object met records in elk ander object',
    ONBOARDING_RUN_JOB_PLAUTI_CLOUD: 'Plauti Cloud',
    ONBOARDING_RUN_JOB_LOCAL: 'DC Local',
    ONBOARDING_RUN_JOB_PROCESSING: 'Bepaal waar een DC Job verwerkt moet worden - volledig binnen Salesforce, of extern via {0} of {1}',
    ONBOARDING_RUN_JOB_MANUALLY: 'handmatig',
    ONBOARDING_RUN_JOB_AUTOMATICALLY: 'automatisch',
    ONBOARDING_RUN_JOB_MERGE_OR_CONVERT: 'Kies ervoor om {0} of {1} samen te voegen of te converteren',
    ONBOARDING_RUN_JOB_SCHEDULE_A_JOB: 'Plan een job',
    ONBOARDING_RUN_JOB_SCHEDULE_MESSAGE: '{0} om uit te voeren op een frequentie en tijd naar keuze',
    ONBOARDING_PREVENTION_DUPLICATE_PREVENTION: 'Duplicaat-preventie',
    ONBOARDING_PREVENTION_OPENING_MESSAGE: 'Hieronder vindt u de verschillende manieren waarop een record Salesforce kan binnenkomen, en ziet u hoe DC ervoor kan zorgen dat duplicaten worden gedetecteerd en verwerkt.',
    ONBOARDING_PREVENTION_MANUAL_INSERT: 'Handmatig Invoegen',
    ONBOARDING_PREVENTION_MANUAL_INSERT_DESCRIPTION: 'Zelfs wanneer u extra voorzichtig bent kunnen duplicaten in Salesforce ontstaan door eindgebruikers die ze handmatig invoeren. Duplicate Check heeft een geweldige functie, "DC Entry", die u kunt implementeren. Lees meer in de documentatie.',
    ONBOARDING_PREVENTION_IMPORT: 'Importeren',
    ONBOARDING_PREVENTION_IMPORT_DESCRIPTION: 'Bij het importeren van records via Data Loader of de Data Import Wizard, zullen duplicaten hun weg vinden naar uw Salesforce-omgeving. Bij gebruik van Duplicate Check worden duplicaten tijdens het importeren gemarkeerd, waarna u de optie heeft om de records samen te voegen. Door een duplicaat niet te blokkeren bij binnenkomst heeft u de mogelijkheid om de meest recente informatie op te slaan.',
    ONBOARDING_PREVENTION_INTEGRATIONS: 'Integraties (Salesforce API)',
    ONBOARDING_PREVENTION_INTEGRATIONS_DESCRIPTION: 'De gemiddelde Salesforce-implementatie is gekoppeld aan een tiental externe tools die allemaal via de Salesforce-API communiceren, waarbij dagelijks veel nieuwe records worden gemaakt. Duplicate Check kan het Salesforce-API-kanaal controleren en elk duplicaat op het punt van invoer detecteren.',
    ONBOARDING_PREVENTION_WEBFORMS: 'Webformulieren',
    ONBOARDING_PREVENTION_WEBFORMS_DESCRIPTION: 'Als u webformulieren heeft gekoppeld aan uw Salesforce-omgeving, bent u waarschijnlijk op de hoogte van het probleem met duplicaten. Door Duplicate Check te gebruiken, krijgt u de mogelijkheid om duplicaten van een webformulier te detecteren en deze in realtime te verwerken.',
    ONBOARDING_DCLIVE_OPENING_MESSAGE: 'Bij Plauti zijn we van mening dat de kwaliteit van gegevens een gedeelde verantwoordelijkheid is voor de hele organisatie. Dat is de reden dat we DC Live hebben gecreëerd.',
    ONBOARDING_DCLIVE_DESCRIPTION: 'DC Live is een component die u aan elke object page layout kunt toevoegen, en die toegankelijk is voor elke gebruiker in Salesforce. Wanneer een record wordt geopend, toont DC Live duplicaten van het record dat wordt geopend.',
    ONBOARDING_DCLIVE_EMPOWER_END_USERS: 'Geef eindgebruikers inzicht in te geven in de kwaliteit van hun gegevens, en besluit om hen {0} toe te staan, of alleen {1}.',
    ONBOARDING_DCLIVE_MERGE_RECORDS_THEMSELVES: 'records zelf samen te voegen',
    ONBOARDING_DCLIVE_FLAG_FOR_ADMIN: 'ze te markeren voor een beheerder',
    ONBOARDING_DCLIVE_HOW_TO_CONFIGURE: 'Hoe configureer ik DC Live',
    ONBOARDING_CONFIGURE_OPENING_MESSAGE: 'Een van de dingen waarin Duplicate Check goed is, is het configureren van de tool zodat deze zich aanpast aan uw unieke Salesforce-implementatie. Lees meer over de volgende onderwerpen om het meeste uit de tool te halen.',
    ONBOARDING_CONFIGURE_SCENARIOS_SEARCH_INDEX: 'Scenario\'s & Zoekindex',
    ONBOARDING_CONFIGURE_SCENARIO_EXPLANATION: 'Een scenario in Duplicate Check lijkt op de "Vergelijkingsregels" in Salesforce - het bepaalt hoe records worden vergeleken en het beslist wat een duplicaat record is. Om het meeste uit de tool te halen, raden we aan om te lezen wat het kan doen en hoe het kan worden geconfigureerd.',
    ONBOARDING_CONFIGURE_SEARCH_INDEX_EXPLANATION: 'Om een scenario optimaal te laten werken, vragen we u om de zoekindex in te schakelen en aan te maken. Duplicate Check gebruikt de Zoekindex om duplicate records te vinden op basis van het toegepaste scenario. Zonder zoekindex kan Duplicate Check niet alle duplicaten vinden.',
    ONBOARDING_CONFIGURE_MERGE_RULES: 'Samenvoegregels',
    ONBOARDING_CONFIGURE_MERGE_RULES_EXPLANATION: 'Bij het samenvoegen van records binnen een object gebruikt Duplicate Check de Samenvoegregels om te bepalen wat het hoofdrecord is, en welke velden op het hoofdrecord moeten worden opgeslagen. De Samenvoegregels bepalen ook welke velden vooraf worden geselecteerd op de pagina voor handmatig samenvoegen, en de regels worden toegepast bij het uitvoeren van een geautomatiseerde samenvoeging. Leer hoe u de Samenvoegregels kunt instellen.',
    ONBOARDING_AUTOMATION_OPENING_MESSAGE: 'Duplicate Check is native in Salesforce, en biedt daarom de beste real-time duplicaatdetectie en -verwerking.',
    ONBOARDING_AUTOMATION_DC_LEVEL_OFFER: 'Duplicate Check biedt verschillende niveaus van automatisering',
    ONBOARDING_AUTOMATION_EXPLANATION: 'Er zijn verschillende niveaus van automatisering, variërend van door mensen uitgevoerde tot volledig geautomatiseerde processen. Leer meer over automatisering en kies wat bij uw situatie past.',
    ONBOARDING_AUTOMATION_AUDIT_LOG: 'Auditlogboek',
    ONBOARDING_AUTOMATION_AUDIT_LOG_DESCRIPTION: 'Eventuele samenvoeging of converteer activiteit, handmatig of automatisch uitgevoerd, kan worden bijgehouden in het auditlogboek. Het auditlogboek moet worden ingeschakeld voordat de logs worden opgeslagen, omdat dit wat opslagruimte in beslag neemt.',
    ONBOARDING_AUTOMATION_DIRECT_PROCESSING: 'Direct Verwerken',
    ONBOARDING_INTEGRATION_OPENING_MESSAGE: 'U hebt Salesforce gekozen vanwege de flexibiliteit om al uw bedrijfsprocessen te integreren. Onze Apex plugins, Stroom acties, API and SFDX-plugins zorgen ervoor dat deduplicatie naadloos integreert met uw bestaande processen.',
    ONBOARDING_INTEGRATION_APEX_API: 'Duplicate Check Apex API',
    ONBOARDING_INTEGRATION_APEX_API_DESCRIPTION: 'Duplicate Check biedt een Apex API waarmee u alle DC-functies in uw eigen Apex projecten kunt implementeren. Dit omvat het vinden van duplicate records met behulp van de DC-zoekmachine, samenvoegen en converteren, maar het stelt u ook in staat om DC-configuraties te exporteren via API.',
    ONBOARDING_INTEGRATION_REST_API: 'Duplicate Check REST API',
    ONBOARDING_INTEGRATION_REST_API_DESCRIPTION: 'Duplicate Check biedt een REST-API die kan worden gebruikt om records in Salesforce te zoeken of toe te voegen/bij te werken via de Data API. Met de REST Data API kunt u records aanmaken zonder duplicaten te creëren. Wanneer een record wordt toegevoegd via de Data API, wordt deze direct vergeleken met alle bestaande records in Salesforce. Als er duplicaten aanwezig zijn, zal DC het bestaande record bijwerken in plaats van een duplicaat record te creëren.',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS: 'Duplicate Check Stroom-Acties',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS_DESCRIPTION: 'Duplicate Check heeft voor de meeste functies een Stroom-actie beschikbaar. Hierdoor krijgt u de mogelijkheid om alle features met betrekking tot duplicaatpreventie, samenvoegen, converteren en meer, te implementeren in elke Salesforce-stroom.',
    ONBOARDING_CUSTOMISATION_OPENING_MESSAGE: 'U heeft Salesforce gekozen vanwege de flexibiliteit om al uw bedrijfsprocessen te integreren. Onze Apex plug-ins, Stroom-acties, API and SFDX-plugins zorgen ervoor dat deduplicatie naadloos integreert in uw bestaande processen.',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS: 'Duplicate Check Plug-ins',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS_DESCRIPTION: 'We begrijpen dat een bedrijf zeer specifieke processen heeft en dat het moeilijk is een tool te vinden die zich kan aanpassen aan moeilijke eisen. Gebruik de plug-ins die Duplicate Check aanbiedt als u aanpassingen wil maken aan de out-of-the-box functionaliteit.',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS: 'SFDX Plug-ins',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS_DESCRIPTION: 'Met de SFDX plug-ins kunnen ontwikkelaars taken automatiseren die gerelateerd zijn aan Duplicate Check licenties en configuraties. Bijvoorbeeld, als u een pipeline met verschillende staging-omgevingen heeft gebouwd, dan kunt u de synchronisatie van Duplicate Check-configuraties automatiseren, zodat deze hetzelfde zijn voor alle omgevingen.',
    ONBOARDING_GET_STARTED_A_LOT_OF_INFO: 'Dat is veel informatie, of niet?',
    ONBOARDING_GET_STARTED_OPENING_MESSAGE: 'U kent nu de basis van Duplicate Check. We weten dat het veel in één keer is. U bent nu klaar om uw reis naar een duplicaat-vrije Salesforce-omgeving te beginnen met alle geweldige voordelen die Duplicate Check biedt.',
    ONBOARDING_GET_STARTED_FEELING_LOST: 'De weg kwijt? Voel u vrij om een 1-op-1 sessie te plannen met één van onze product-experts.',
    ONBOARDING_GET_STARTED_SCHEDULE_CALL: 'Plan een gesprek met één van onze Product Experts!',
    ONBOARDING_GET_STARTED_FLYING_START: 'Wilt u een vliegende start bij het implementeren van Duplicate Check voor uw organisatie? Voel u vrij om gratis een gesprek te plannen met één van onze product-experts. We helpen u graag bij het verkennen en configureren van Duplicate Check.',
    ONBOARDING_GET_STARTED_SCHEDULE_A_CALL: 'Plan een gesprek',
    ONBOARDING_GET_STARTED_INTERESTING_LINKS: 'Interessante links',
    ONBOARDING_GET_STARTED_SCHEDULE_PRODUCT_EXPERT: 'Plan een gesprek met een Product Expert',
    ONBOARDING_GET_STARTED_KNOWLEDGEBASE: 'Kennissysteem',
    ONBOARDING_GET_STARTED_HOWTO_VIDEOS: 'How-to video\'s',
    ONBOARDING_GET_STARTED_GUIDE: 'Startersgids',
    ONBOARDING_GET_STARTED_CONTACT_SUPPORT: 'Neem contact op met Support',
    general: {
        DCJOB_AUTOCONVERT_LEARNMORE: 'Lees meer',
        DCJOB_AUTOMERGE_LEARNMORE: 'Lees meer',
        DCJOB_NEWJOB_LEARNMORE: 'Lees meer',
        DCJOB_AUTOMERGE_SPEED: 'Snelheid',
        DCJOB_NEWJOB_SPEED: 'Snelheid',
        DCJOB_NEWJOB_MEDIUM: 'gemiddeld',
        DCJOB_AUTOMERGE_MEDIUM: 'gemiddeld',
        DCJOB_NEWJOB_RECOMMENDED: 'Aanbevolen',
        DCJOB_AUTOMERGE_RECOMMENDED: 'Aanbevolen',
        DCJOB_AUTOCONVERT_RECOMMENDED: 'Aanbevolen',
        DCJOB_DELETEMODAL_ALLTIME: 'Sinds het begin',
        DCJOB_DELETEMODAL_SETDATE: 'Datum opgeven',
        DCJOB_DELETEMODAL_SETDATERANGE: 'Datumbereik opgeven',
        DCJOB_DELETEMODAL_FROM: 'Van',
        DCJOB_DELETEMODAL_UNTIL: 'Tot',
        DCJOB_DELETEMODAL_TYPE: 'Type',
        DCJOB_DELETEMODAL_DATE: 'Datum',
        DCJOB_JOBPAGE_OBJECT: 'Object',
        DCJOB_SCHEDULEDJOBPAGE_OBJECT: 'Object',
        DCJOB_SCHEDULEDJOBPAGE_NOTAPPLICABLE: 'N.v.t.',
        DCJOB_SCHEDULEDJOBPAGE_NOME: 'Naam',
        DCJOB_SCHEDULEDJOBPAGE_FREQUENCYANDTIME: 'Frequentie & Tijd',
        DCJOB_SCHEDULEDJOBPAGE_STATUS: 'Status',
        DCJOB_SCHEDULEDJOBPAGE_NEXTSTART: 'Volgende Start',
        DCJOB_PAGINATIONCOMPONENT_PAGE: 'Pagina',
        DCJOB_PAGINATIONCOMPONENT_OF: 'van',
    },
    groupObject: {
        GROUPNUMBER: 'Groepnummer',
        GROUPPAIRCOUNT: 'Aantal Paren in Groep',
        GROUPRECORDCOUNT: 'Aantal Records in Groep',
        GROUPCONTAINSMERGEERROR: 'Groep Bevat Samenvoegfout',
        GROUPCONTAINSCONVERTERROR: 'Groep Bevat Converteerfout',
        GROUPFOUNDJOB: 'Found in Job',
    },
    days: {
        DCJOB_NEWJOB_MONDAY: 'maandag',
        DCJOB_NEWJOB_TUESDAY: 'dinsdag',
        DCJOB_NEWJOB_WEDNESDAY: 'woensdag',
        DCJOB_NEWJOB_THURSDAY: 'donderdag',
        DCJOB_NEWJOB_FRIDAY: 'vrijdag',
        DCJOB_NEWJOB_SATURDAY: 'zaterdag',
        DCJOB_NEWJOB_SUNDAY: 'zondag',
    },
    monthly: {
        LAST_DAY: 'Laatste dag',
        LAST_WEEKDAY: 'Laatste weekdag',
    },
    frequency: {
        DCJOB_SCHEDULED_FREQUENCY_PLACEHOLDER: 'Optie Selecteren...',
        DCJOB_SCHEDULED_FREQUENCY_DAILY: 'Dagelijks',
        DCJOB_SCHEDULED_FREQUENCY_WEEKLY: 'Wekelijks',
        DCJOB_SCHEDULED_FREQUENCY_MONTHLY: 'Maandelijks',
        DCJOB_SCHEDULED_FREQUENCY_CUSTOM: 'Aangepast',
    },
    titles: {
        DCJOB_JOBPAGE_JOBOVERVIEW: 'Job-Overzicht',
        DCJOB_SCHEDULEDJOBPAGE_SCHEDULEDJOB: 'Overzicht Geplande Jobs',
        DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOB: 'Verwijder Geplande Job',
        DCJOB_JOBPAGE_LISTVIEWS: 'LIJSTWEERGAVEN',
    },
    buttons: {
        DCJOB_JOBCARD_ABORT: 'Afbreken',
        DCJOB_BACK: 'Terug',
        DCJOB_NEWJOB_BACK: 'Terug',
        DCJOB_AUTOMERGE_BACK: 'Terug',
        DCJOB_AUTOCONVERT_BACK: 'Terug',
        DCJOB_JOBPAGE_CANCEL: 'Annuleren',
        DCJOB_NEWJOB_CANCEL: 'Annuleren',
        DCJOB_JOBCARD_CANCEL: 'Annuleren',
        DCJOB_EXPORTMODAL_CANCEL: 'Annuleren',
        DCJOB_DELETEMODAL_CANCEL: 'Annuleren',
        DCJOB_AUTOMERGE_CANCEL: 'Annuleren',
        DCJOB_AUTOCONVERT_CANCEL: 'Annuleren',
        DCJOB_SCHEDULEDJOBPAGE_CANCEL: 'Annuleren',
        DCJOB_SCHEDULEDJOBPAGE_DELETEJOBS: 'Verwijder Jobs',
        DCJOB_JOBPAGE_DELETEJOBS: 'Verwijder Jobs',
        DCJOB_DELETEMODAL_DELETEJOBS: 'Verwijder Jobs',
        DCJOB_SCHEDULEDJOBPAGE_DELETE: 'Verwijderen',
        DCJOB_JOBCARD_DELETE: 'Verwijderen',
        DCJOB_DELETEMODAL_DELETE: 'Verwijderen',
        DCJOB_EXPORTMODAL_EXPORTDCLOCAL: 'Exporteren via DC Local',
        DCJOB_EXPORTMODAL_EXPORTCLOUD: 'Exporteren via Plauti Cloud',
        DCJOB_JOBPAGE_FILTER: 'Filter',
        DCJOB_NEWJOB_FILTER: 'Filter',
        DCJOB_FILTER: 'Filter',
        DCJOB_SCHEDULEDJOBPAGE_INFO: 'Info',
        DCJOB_JOBCARD_INFO: 'Info',
        DCJOB_SCHEDULEDJOBPAGE_EDIT: 'Bewerken',
        DCJOB_SCHEDULEDJOBPAGE_JOBOPTIONS: 'Job-opties',
        DCJOB_JOBCARD_JOBOPTIONS: 'Job-opties',
        DCJOB_SCHEDULEDJOBPAGE_NEWJOB: 'Nieuwe Job',
        DCJOB_JOBPAGE_NEWJOB: 'Nieuwe Job',
        DCJOB_NEWJOB_NEXT: 'Volgende',
        DCJOB_AUTOMERGE_NEXT: 'Volgende',
        DCJOB_AUTOCONVERT_NEXT: 'Volgende',
        DCJOB_JOBPAGE_SAVE: 'Opslaan',
        DCJOB_NEWJOB_START: 'Starten',
        DCJOB_NEWJOB_SCHEDULE: 'Plannen',
        DCJOB_AUTOMERGE_START: 'Starten',
        DCJOB_AUTOCONVERT_START: 'Starten',
        DCJOB_JOBPAGE_SORTJOBS: 'Sorteer Jobs',
        DCJOB_SCHEDULEDJOBPAGE_RUNNOW: 'Nu Eenmalig Uitvoeren',
        DCJOB_SCHEDULEDJOBPAGE_DEACTIVATED: 'Deactiveren',
        DCJOB_SCHEDULEDJOBPAGE_ACTIVATE: 'Activeren',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS_NUMBER: 'Resultaten weergeven {0}',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS: 'Bekijk Resultaten',
        MERGE: 'Samenvoegen',
        QUICKMERGE: 'Snel Samenvoegen',
        QUICKCONVERT: 'Snel Converteren',
        MORE: 'Meer',
        edit: 'Bewerken',
        DCJOB_JOBCARD_VIEWRESULTS: 'Resultaten weergeven {0}',
        DCJOB_JOBPAGE_DELETESELECTEDJOBS: 'Delete Selected Jobs',
        DCJOB_JOBPAGE_SELECTALL: 'Select All',
        DCJOB_JOBPAGE_DESELECTALL: 'Deselect All',
    },
    badges: {
        DCJOB_JOBCARD_REVIEWERRORS: 'Controleer fouten',
        DCJOB_JOBCARD_READMORE: 'Lees meer',
        DCJOB_JOBCARD_LIMITTEXT: 'Gelicentieerde Record Limiet bereikt.',
        DCJOB_JOBCARD_DELETESELECTED: `{count} job selected | {count} jobs selected`,
    },
    metaData: {
        DCJOB_JOBPAGE_AVERAGESCORE: 'Gemiddelde Score',
        DCJOB_OVERALLJOBRESULTS_AVERAGESCORE: 'Gemiddelde Score',
        DCJOB_JOBPAGE_STORAGESPACETAKEN: 'Opslagruimte in gebruik',
        DCJOB_JOBPAGE_TOTALGROUPS: 'Totaal Groepen',
        DCJOB_JOBPAGE_TOTALJOBS: 'Totaal Jobs',
        DCJOB_JOBPAGE_TOTALPAIRS: 'Totaal Paren',
        DCJOB_JOBPAGE_TOTALRECORDS: 'Totaal Records',
        DCJOB_OVERALLJOBRESULTS_RECORDS: 'Records',
        DCJOB_OVERALLJOBRESULTS_GROUPS: 'Groepen',
        DCJOB_OVERALLJOBRESULTS_PAIRS: 'Paren',
        DCJOB_OVERALLJOBRESULTS_OBJECT: 'Object',
    },
    job: {
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDTITLE: 'Auditlogboek niet beschikbaar in uw licentie',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDSUBTITLE: 'Auditlogboek is beschikbaar in Premium en hoger',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDBUTTON: 'Nu Upgraden',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDRUPGRADEURL: 'https://go.plauti.com/l/640773/2023-03-27/53tydt',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDTITLE: 'Auditlogboek Uitgeschakeld',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDSUBTITLE: 'Vraag uw Salesforce-beheerder om het Duplicate Check Auditlogboek te activeren.',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGETITLE: 'Logboek Samenvoegingen is leeg',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTTITLE: 'Logboek Conversies is leeg',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGESUBTITLE: 'Er zijn nog geen samenvoeg-activiteiten geweest voor deze job.',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTSUBTITLE: 'Er zijn nog geen converteer-activiteiten geweest voor deze job.',
        DCJOB_AUDITLOGTABLEHEADER_MASTERRECORD: 'Hoofdrecord',
        DCJOB_AUDITLOGTABLEHEADER_MERGEDRECORDS: 'Samengevoegde Record(s)',
        DCJOB_AUDITLOGTABLEHEADER_LEADRECORD: 'Lead Record',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOPERSON: 'Naar Persoonsaccount Converteren',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOACCOUNT: 'Naar Account Converteren',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOCONTACT: 'Naar Contactpersoon Converteren',
        DCJOB_AUDITLOGTABLEHEADER_METHOD: 'Methode',
        DCJOB_AUDITLOGTABLEHEADER_DATETIME: 'Datum & Tijd',
        DCJOB_AUDITLOGTABLEHEADER_USER: 'Gebruiker',
        DCJOB_AUDITLOGTOOLTIP_CONVERTEDRECORD: 'Geconverteerde Record',
        DCJOB_AUDITLOGTOOLTIP_MERGEDRECORD: 'Samengevoegde Record',
        DCJOB_AUDITLOGTOOLTIP_RECORDID: 'Record-ID:',
        DCJOB_AUDITLOGTOOLTIP_AUDITID: 'Audit ID:',
        DCJOB_AUDITLOGSUMMARY_NUMBEROFRECORDS: 'Aantal Records {0}',
        DCJOB_JOBCARD_JOBS: 'Jobs',
        DCJOB_JOBCARD_TASK: 'Taak',
        DCJOB_JOBCARD_STARTED: 'Gestart op',
        DCJOB_JOBCARD_FINISHED: 'Afgerond op',
        DCJOB_JOBCARD_USER: 'Gestart door',
        DCJOB_JOBCARD_STATUS: 'Status',
        DCJOB_JOBPAGE_STATUS: 'Status',
        DCJOB_JOBCARD_RESULT: 'Resultaat',
        DCJOB_JOBPAGE_JOBNAME: 'Jobnaam',
        DCJOB_NEWJOB_JOBNAME: 'Jobnaam',
        DCJOB_JOBCARD_JOBNAME: 'Jobnaam',
        DCJOB_AUTOMERGE_JOBNAME: 'Jobnaam',
        DCJOB_AUTOCONVERT_JOBNAME: 'Jobnaam',
        DCJOB_JOBPAGE_JOBID: 'Job-ID',
        DCJOB_JOBCARD_JOBID: 'Job-ID',
        DCJOB_JOBPAGE_NOJOBS: 'Geen jobs.',
        DCJOB_SCHEDULEDJOBPAGE_NOSCHEDULEDJOBS: 'Geen jobs gepland.',
        DCJOB_NEWJOB_JOBNAMEPLACEHOLDER: 'Voer een jobnaam in',
        DCJOB_JOBCARD_AUTOMERGE: 'Automatisch Samenvoegen',
        DCJOB_JOBCARD_MANUALMERGE: 'Handmatig Samenvoegen',
        DCJOB_JOBCARD_QUICKMERGE: 'Snel Samenvoegen',
        DCJOB_JOBCARD_AUTOCONVERT: 'Automatisch Converteren',
        DCJOB_JOBCARD_MANUALCONVERT: 'Handmatig Converteren',
        DCJOB_JOBCARD_MERGELOG: 'Logboek Samenvoegingen',
        DCJOB_JOBCARD_CONVERTLOG: 'Logboek Conversies',
        DCJOB_JOBCARD_QUICKCONVERT: 'Snel Converteren',
        DCJOB_JOBCARD_AUTOMERGEDCLOCAL: 'Automatisch Samenvoegen via DC Local',
        DCJOB_JOBCARD_AUTOMERGECLOUD: 'Automatisch Samenvoegen via Plauti Cloud',
        DCJOB_AUTOMERGE_CONFIGUREAUTOMERGE: 'Configureer Automatisch Samenvoegen',
        DCJOB_AUTOCONVERT_CONFIGUREAUTOCONVERT: 'Configureer Automatisch Converteren',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE: 'Ik erken dat het starten van deze Automatisch Samenvoegen-job {0} duplicate records zal samenvoegen, en dat het samenvoegen van records niet ongedaan kan worden gemaakt.',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE_WITHOUT_RECORDCOUNT: 'Ik erken dat het starten van deze Automatisch Samenvoegen-job duplicate records zal samenvoegen, en dat het samenvoegen van records niet ongedaan kan worden gemaakt.',
        DCJOB_EXPORTMODAL_EXPORTRESULTS: 'Resultaten Exporteren',
        DCJOB_JOBCARD_EXPORTRESULTSDCLOCAL: 'Resultaten Exporteren via DC Local',
        DCJOB_JOBCARD_EXPORTRESULTSCLOUD: 'Resultaten Exporteren via Plauti Cloud',
        DCJOB_JOBCARD_NUMBEROFRECORDS: 'Aantal Records',
        DCJOB_JOBPAGE_NUMBEROFRECORDS: 'Aantal Records',
        DCJOB_JOBCARD_NUMBEROFPAIRS: 'Aantal Paren',
        DCJOB_JOBCARD_RESULTFIELDS: 'Resultaatvelden',
        DCJOB_AUTOMERGE_CONFIRMATION: 'Bevestiging',
        DCJOB_AUTOCONVERT_CONFIRMATION: 'Bevestiging',
        DCJOB_AUTOMERGE_PROCESSEDBY: 'Verwerkt door',
        DCJOB_AUTOCONVERT_PROCESSEDBY: 'Verwerkt door',
        DCJOB_DELETEMODAL_CURRENTNUMBEROFJOBS: 'Huidig aantal jobs in DC Jobs',
        DCJOB_DELETEMODAL_JOBSCREATEDAT: 'Jobs aangemaakt op',
        DCJOB_DELETEMODAL_CONTAINSDUPLICATERESULTS: 'Bevat duplicaat-resultaten',
        DCJOB_DELETEMODAL_JOBSSELECTEDFORDELETION: 'Aantal geselecteerde jobs om te verwijderen',

        infoModal: {
            DCJOB_INFOMODAL_GENERALINFO_STARTEDBYUSER: 'Gestart door gebruiker',
            DCJOB_INFOMODAL_GENERALINFO_STATUS: 'Status',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMESTARTED: 'Startdatum en -tijd',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMEFINISHED: 'Einddatum en -tijd',
            DCJOB_INFOMODAL_GENERALINFO_TOTALTIMETAKEN: 'Totale Tijd',
            DCJOB_INFOMODAL_GENERALINFO_PROCESSEDBY: 'Verwerkt door',
            DCJOB_INFOMODAL_GENERALINFO_LASTDUPLICATEADDED: 'Laatste Duplicaat Toegevoegd',
            DCJOB_INFOMODAL_GENERALINFO_APPLIEDSCENARIOS: 'Toegepaste Scenario\'s',
            DCJOB_INFOMODAL_GENERALINFO_JOBID: 'Job-ID',
            DCJOB_INFOMODAL_GENERALINFO_APEXJOBID: 'Apex Job ID',
            DCJOB_INFOMODAL_GENERALINFO_CREATEDBYUSER: 'Aangemaakt door Gebruiker',
            DCJOB_INFOMODAL_GENERALINFO_FREQUENCY: 'Frequentie',
            DCJOB_INFOMODAL_GENERALINFO_LASTRUNAT: 'Laatst uitgevoerd op',
            DCJOB_INFOMODAL_GENERALINFO_NEXTRUNAT: 'Volgende uitvoering op',
            DCJOB_INFOMODAL_GENERALINFO_NUMBEROFTIMESRUN: 'Aantal keren uitgevoerd',
            DCJOB_INFOMODAL_GENERALINFO_AUTOPROCESS: 'Auto process',
            DCJOB_INFOMODAL_GENERALINFO_SCHEDULED_LASTMODIFIED: 'Geplande Job laatst gewijzigd door + Datum & Tijd',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEGROUPS: 'Duplicaatgroepen',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEPAIRS: 'Duplicaatparen',
            DCJOB_INFOMODAL_DUPLICATESINFO_RECORDSINVOLVED: 'Betrokken records',
            DCJOB_INFOMODAL_DUPLICATESINFO_AVERAGESCORE: 'Gemiddelde Score',
            DCJOB_INFOMODAL_SELECTEDINFO_OBJECT: 'Object',
            DCJOB_INFOMODAL_SELECTEDINFO_NUMBEROFRECORDS: 'Aantal Records',
            DCJOB_INFOMODAL_SELECTEDINFO_SOURCE: 'Source',
            DCJOB_INFOMODAL_SELECTEDINFO_MATCH: 'Match'
        },
        sortOptions: {
            DCJOB_JOBPAGE_SORTBY: 'Sorteren op',
            DCJOB_JOBPAGE_DATETIMESTARTED: 'Gestart op',
            DCJOB_JOBPAGE_DATETIMEFINISHED: 'Afgerond op',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEGROUPS: 'Aantal Duplicaatgroepen',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEPAIRS: 'Aantal Duplicaatparen',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATERECORDSINVOLVED: 'Aantal betrokken duplicate records',
            DCJOB_JOBPAGE_LASTDUPLICATEADDED: 'Laatste Duplicaat Toegevoegd',
            DCJOB_JOBPAGE_ORDER: 'Volgorde',
            DCJOB_JOBPAGE_ASCENDING: 'Oplopend',
            DCJOB_JOBPAGE_DESCENDING: 'Aflopend',
        },
        menuOptions: {
            DCJOB_SCHEDULEDJOBPAGE_TITLE: 'Job-opties',
            DCJOB_JOBCARD_TITLE: 'Job-opties',
            DCJOB_JOBCARD_OPTION_RESTART: 'Herstarten',
            DCJOB_JOBCARD_OPTION_STARTAUTOMERGE: 'Automatisch Samenvoegen Starten',
            DCJOB_JOBCARD_OPTION_STARTAUTOCONVERT: 'Automatisch Converteren Starten',
            DCJOB_JOBCARD_OPTION_EXPORTRESULTS: 'Exporteer Resultaten',
            DCJOB_JOBCARD_OPTION_SHAREJOB: 'Job Delen',
            DCJOB_JOBCARD_OPTION_DELETEJOB: 'Job verwijderen',
        },

        new: {
            DCJOB_NEWJOB_STEP: 'Stap',
            DCJOB_AUTOMERGE_STEP: 'Stap',
            DCJOB_AUTOCONVERT_STEP: 'Stap',
            DCJOB_NEWJOB_SELECTRECORDS: 'Records Selecteren',
            DCJOB_NEWJOB_JOBOPTIONS: 'Job-opties',
            DCJOB_NEWJOB_PROCESSOPTIONS: 'Proces Opties',
            DCJOB_NEWJOB_SELECTOBJECT: 'Object Selecteren',
            DCJOB_NEWJOB_SELECTOBJECTPLACEHOLDER: 'Selecteer een Object',
            DCJOB_NEWJOB_SELECTOPTIONSPLACEHOLDER: 'Zoek opties...',
            DCJOB_NEWJOB_ADDCROSSOBJECT: 'Cross-Object toevoegen',
            DCJOB_NEWJOB_REMOVECROSSOBJECT: 'Cross-Object verwijderen',
            DCJOB_NEWJOB_ADDFILTER: 'Filter Toevoegen',
            DCJOB_NEWJOB_MATCHWITH: 'Vergelijk met',
        },

        deleteAll: {
            DCJOB_DELETESELECTED_TITLE: 'Delete Selected Jobs',
            DCJOB_DELETESELECTED_MESSAGE: 'Are you sure you want to delete {count} selected job? This action cannot be undone. | Are you sure you want to delete {count} selected jobs? This action cannot be undone.',
        },

        delete: {
            DCJOB_DELETEMODAL_DELETEJOBSMESSAGE: 'Weet u zeker dat u {0} jobs wilt verwijderen? Het verwijderen van jobs kan niet ongedaan worden gemaakt.',
            DCJOB_JOBCARD_DELETEMESSAGE: 'Weet u zeker dat u {0} wilt verwijderen?',
            DCJOB_JOBCARD_DELETEUNDONE: 'Verwijderen van {0} kan niet ongedaan worden gemaakt.',
            DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOBMESSAGE: 'Weet u zeker dat u de geplande job "{0}" wilt verwijderen?',
        },

        options: {
            DCJOB_NEWJOB_SCHEDULE: 'Plannen',
            addScheduler: 'Planning toevoegen',
            scheduleDescription: 'Plan de job in om deze op een ingestelde frequentie en tijd te verwerken.',
            autoMergeDescription: 'Voeg een drempel toe voor het automatisch samenvoegen van duplicate records direct nadat de job is voltooid. Let erop dat Automatisch Samenvoegen op elk moment ook handmatig kan worden gestart.',
            DCJOB_NEWJOB_REMOVESCHEDULER: 'Planning Verwijderen',
            addAutoMerge: 'Automatisch Samenvoegen toevoegen',
            removeAutoMerge: 'Automatisch Samenvoegen verwijderen',
            DCJOB_NEWJOB_FREQUENCY: 'Frequentie',
            DCJOB_NEWJOB_CRONSTRING: 'Cron-string',
            DCJOB_NEWJOB_CRONSTRING_INFO: 'Gebruik het Cron-string formaat \* * * * * *\ om DC Jobs te plannen door het opgeven van seconden, minuut, uur, dag, maand en dag van de week.',
            DCJOB_NEWJOB_RECURS: 'Herhaalt elke week op',
            DCJOB_NEWJOB_MONTHRECURS: 'Herhaalt elke maand op de',
            DCJOB_NEWJOB_PREFERREDSTARTTIME: 'Gewenste Starttijd',
            DCJOB_NEWJOB_PREFERREDSTARTTIMEINFO: 'Salesforce plant de DC-job voor uitvoering op het opgegeven tijdstip. De daadwerkelijke uitvoering kan worden vertraagd afhankelijk van de beschikbaarheid van de service.',
            DCJOB_AUTOMERGE_AUTOMERGETHRESHOLD: 'Drempel voor Automatisch Samenvoegen',
            DCJOB_AUTOMERGE_AUTOMERGETEXT: 'Nadat de job is voltooid, worden alle duplicaatparen met een overeenstemmingspercentage dat gelijk is aan of hoger dan {0}% automatisch samengevoegd.',
            DCJOB_NEWJOB_AUTOMERGETEXT: 'Nadat de job is voltooid, worden alle duplicaatparen met een overeenstemmingspercentage dat gelijk is aan of hoger dan {0}% automatisch samengevoegd.',
            DCJOB_NEWJOB_AUTOCONVERTEXPLANATION: 'Alle duplicaatparen met een overeenstemmingspercentage dat gelijk is aan of hoger dan {0}% worden automatisch geconverteerd.',
            DCJOB_AUTOCONVERT_AUTOCONVERTEXPLANATION: 'Alle duplicaatparen met een overeenstemmingspercentage dat gelijk is aan of hoger dan {0}% worden automatisch geconverteerd.',
            DCJOB_AUTOMERGE_AUTOMERGEWARNING: 'Het samenvoegen van records kan niet ongedaan worden gemaakt.',
            DCJOB_NEWJOB_PROCESSINGOPTIONS: 'Opties voor verwerking',
            DCJOB_AUTOMERGE_PROCESSINGOPTIONS: 'Opties voor verwerking',
            DCJOB_AUTOCONVERT_PROCESSINGOPTIONS: 'Opties voor verwerking',
            DCJOB_NEWJOB_RUNONSF: 'Uitvoeren op Salesforce Platform',
            DCJOB_AUTOMERGE_RUNONSF: 'Uitvoeren op Salesforce Platform',
            DCJOB_AUTOCONVERT_RUNONSF: 'Uitvoeren op Salesforce Platform',
            DCJOB_NEWJOB_RUNONDCLOCAL: 'Uitvoeren op DC Local',
            DCJOB_AUTOMERGE_RUNONDCLOCAL: 'Uitvoeren op DC Local',
            DCJOB_AUTOCONVERT_RUNONDCLOCAL: 'Uitvoeren op DC Local',
            DCJOB_AUTOMERGE_SFINFO: 'Gebaseerd op het aantal duplicaatparen die zijn geselecteerd voor het Automatisch Samenvoegen-proces, raden we aan om de job op het Salesforce-platform uit te voeren.',
            DCJOB_AUTOCONVERT_SFINFO: 'Gebaseerd op het aantal duplicaatparen die zijn geselecteerd voor het Automatisch Samenvoegen-proces, raden we aan om de job op het Salesforce-platform uit te voeren.',
            DCJOB_AUTOMERGE_DCLOCALINFO: 'Gebaseerd op het aantal duplicaatparen die zijn geselecteerd voor het Automatisch Samenvoegen-proces, raden we aan de job op DC Local uit te voeren.',
            DCJOB_AUTOCONVERT_DCLOCALINFO: 'Gebaseerd op het aantal duplicaatparen die zijn geselecteerd voor het Automatisch Converteren-proces, raden we aan de job op DC Local uit te voeren.',
            DCJOB_AUTOMERGE_SFPLATFORMMESSAGE: 'Voer deze taak uit op het Salesforce Platform (native).',
            DCJOB_AUTOMERGE_DCLOCALMESSAGE: 'Voer deze job uit met DC Local of DC Local server.',
            DCJOB_AUTOMERGE_ADDOBJECTFILTER: 'Voeg {0} filter toe',
            DCJOB_AUTOMERGE_REMOVEOBJECTFILTER: 'Verwijder {0} filter',
            DCJOB_AUTOMERGE_ADDFILTERLINE: 'Filterregel toevoegen',
            DCJOB_AUTOCONVERT_ADDFILTERLINE: 'Filterregel toevoegen',
            DCJOB_AUTOMERGE_OBJECTFILTER: '{0} Filter',
        },
    },
    scenario: {
        DCJOB_NEWJOB_SCENARIO: 'Scenario',
        DCJOB_NEWJOB_SCENARIOINFO: 'In een cross-object job zijn alleen scenario\'s van het vergeleken object beschikbaar.',
        DCJOB_SCENARIOCARD_SCENARIONAME: 'Scenarionaam',
        DCJOB_SCENARIOCARD_THRESHOLD: 'Drempelwaarde',
        DCJOB_SCENARIOCARD_EMPTYFIELDS: 'Lege velden',
        fields: {
            DCJOB_SCENARIOCARD_FIELD: 'Veld',
            DCJOB_SCENARIOCARD_FREQUENTWORDS: 'Veelvoorkomende Woorden',
            DCJOB_SCENARIOCARD_MATCHINGMETHOD: 'Vergelijkingsmethode',
            DCJOB_SCENARIOCARD_WEIGHT: 'Gewicht',
        },
    },
    filter: {
        DCJOB_INFOMODAL_READMOREINFO: 'Na het toevoegen van een filter wordt het filter genummerd. Uw eerste filter wordt filter 1 en uw tweede filter wordt filter 2. U past filterlogica toe op basis van deze genummerde filters. Klik op het icoontje om meer te lezen.',
        DCJOB_INFOMODAL_FILTER: 'Filter',
        DCJOB_INFOMODAL_SOURCEFILTER: 'Bron Filter',
        DCJOB_INFOMODAL_MATCHFILTER: 'Vergelijkfilter',
        DCJOB_INFOMODAL_AUTOMERGE_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOMERGE_GROUPFILTER: 'Auto Merge Group Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_GROUPFILTER: 'Auto Convert Group Filter',
        DCJOB_JOBPAGE_FILTERJOBS: 'Filter Jobs',
        DCJOB_JOBPAGE_NOFILTERAPPLIED: 'Geen filter toegepast.',
        addFilter: 'Filter Toevoegen',
        operators: {
            DCJOB_SCHEDULEDJOBPAGE_OR: 'OR',
            DCJOB_JOBINFO_OR: 'OR',
        },
        removeFilter: 'Filter verwijderen',
        DCJOB_NEWJOB_SETFILTER: 'Filter instellen',
        DCJOB_NEWJOB_ALLRECORDS: 'Geen Filter, Verwerk alle Records',
        DCJOB_NEWJOB_COMPARERECORDSINABOVEFILTERWITH: 'Vergelijk records in het bovenstaande filter met',
        DCJOB_NEWJOB_RECORDSTHATMEETCRITERIA: 'Records die voldoen aan bovenstaande filtercriteria',
        jobFilterFields: {
            DCJOB_JOBPAGE_STARTEDBYUSER: 'Gestart Door Gebruiker',
            DCJOB_JOBPAGE_CONTAINSFILTER: 'Bevat Filter',
            DCJOB_JOBPAGE_CONTAINSAUTOMERGE: 'Bevat Automatisch Samenvoegen',
            DCJOB_JOBPAGE_CONSTAINSAUTOCONVERT: 'Bevat Automatisch Converteren',
        },
        startedScheduledJob: '{0} wordt nu uitgevoerd',
        activeScheduledJob: '{0} is nu geactiveerd',
        deactivatedScheduledJob: '{0} is nu gedeactiveerd',
        DCJOB_JOBPAGE_FILTERSAVED: 'Filter succesvol opgeslagen.',
        addFilterlineLabel: 'Filterregel Toevoegen',
        newFilterlinePlaceholder: 'Filterregel Toevoegen',
        fieldLabel: 'Veld',
        fieldPlaceholder: 'Optie Selecteren...',
        fieldPlaceholderSearch: 'Zoek opties...',
        operatorLabel: 'Operator',
        emptyValueLabel: 'Leeg',
        emptyOptionLabel: '- none -',
        addFilterLogicLabel: 'Voeg Filterlogica toe',
        removeFilterLogicLabel: 'Verwijder Filterlogica',
        doneButton: 'Klaar',
        inputLabels: {
            Value: 'Waarde',
            Date: 'Datum',
            Time: 'Tijd',
            'Start date': 'Start Date',
            'End date': 'End Date',
            'Start Time': 'Start Time',
            'End Time': 'End Time',
        },
        logic: {
            ErrorUnusedFilters: 'Er is een ongebruikte filterregel',
            ErrorTypo: 'Er is een typfout',
            ErrorBadNumber: '{0} kan niet gebruikt worden in de filterlogica',
            ErrorMissingRightOperand: 'Er ontbreekt een haakje',
            ErrorAmbiguousAndOr: 'Voeg haakjes toe bij gebruik van de AND + OR',
            ErrorMissingOperand: 'NOT moet gevolgd worden door een operand',
            ErrorParen: 'Onverwacht haakje',
        },
    },
    matchingMethods: {
        EQUAL: 'Exact',
        EQUAL_RANDOM: 'Exact (willekeurige volgorde)',
        NOT_EQUAL: 'Niet Gelijk',
        EQUAL_NULL: 'Gelijk aan Null',
        FUZZY_PERSON: 'Namen van personen',
        FUZZY_COMPANY_EXTRA_STRICT: 'Bedrijfsnaam',
        PHONE: 'Telefoonnummer',
        PHONE_ADVANCED: 'Telefoonnummer Geavanceerd',
        EMAIL_EXACT: 'E-mailadres',
        EMAIL: 'E-mail',
        DOMAIN_EXACT: 'Domein',
        DOMAIN_FUZZY: 'Domein Fuzzy',
        URL_EXACT: 'URL',
        URL_FUZZY: 'URL Fuzzy',
        PRODUCT: 'Productnummer',
        POSTAL_CODE: 'Postcode',
        PERSON_NAME: 'Fuzzy',
        FUZZY_COMPANY: 'Gedeeltelijk Fuzzy Licht',
        FUZZY_COMPANY_STRICT: 'Gedeeltelijk Fuzzy Medium',
        COMPANY_NAME: 'Gedeeltelijke Fuzzy Zwaar',
        COMPANY: 'Bedrijf',
        TEXT: 'Lange tekst',
        DATE_DISTANCE_DAYS: 'Datumafstand in Dagen',
        HAS_VALUE: 'Bevat Waarde',
    },
    frequentWords: {
        STREET: 'Straat',
        COMPANY: 'Bedrijf',
        COMMON: 'Algemeen',
        NAME: 'Namen van personen',
        EMAIL: 'E-mail',
        CUSTOM1: 'Aangepast 1',
        CUSTOM2: 'Aangepast 2',
    },
    emptyFieldOptions: {
        DEDUP50: 'Score 50%',
        DEDUP: 'Score 100%',
        SEARCH: 'Negeer',
    },
    pageNavigation: {
        PREVIOUSPAGE: 'Vorige pagina',
        NEXTPAGE: 'Volgende pagina',
    },
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTSVIEW: 'Duplicaat Resultaten-overzicht',
    DCJOB_OVERALLJOBRESULTS_OVERALLJOBRESULTS: 'Globale Job-resultaten',
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTS: 'Duplicaat-resultaten',
    DCJOB_OVERALLJOBRESULTS_OPENALLGROUPS: 'Open Alle Groepen',
    DCJOB_OVERALLJOBRESULTS_CLOSEALLGROUPS: 'Sluit Alle Groepen',
    DCJOB_OVERALLJOBRESULTS_SEARCHUSERS: 'Gebruikers zoeken',
    DCJOB_OVERALLJOBRESULTS_APPLYFILTER: 'Filter Toepassen',
    DCJOB_OVERALLJOBRESULTS_PAIRCOUNT: 'Aantal Paren',
    DCJOB_OVERALLJOBRESULTS_RECORDCOUNT: 'Aantal Records',
    DCJOB_OVERALLJOBRESULTS_GROUP: 'Groep',
    DCJOB_OVERALLJOBRESULTS_MINSCORE: 'Min. Score',
    DCJOB_OVERALLJOBRESULTS_MAXSCORE: 'Max. Score',
    DCJOB_OVERALLJOBRESULTS_AVGSCORE: 'Gem. Score',
    DCJOB_OVERALLJOBRESULTS_ONEERROR: '1 fout',
    DCJOB_OVERALLJOBRESULTS_MERGESELECTEDRECORDS: 'Geselecteerde Records Samenvoegen',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTION: 'Selectie Uitsluiten',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTIONFOREVER: 'Selectie Voorgoed Uitsluiten',
    DCJOB_OVERALLJOBRESULTS_DELETINGRECORDSNOTUNDOABLE: 'Records verwijderen kan niet ongedaan worden gemaakt.',
    DCJOB_OVERALLJOBRESULTS_MERGEPAIR: 'Paar Samenvoegen',
    DCJOB_OVERALLJOBRESULTS_QUICKMERGEPAIR: 'Paar Snel Samenvoegen',
    DCJOB_OVERALLJOBRESULTS_CONVERTPAIR: 'Paar Converteren',
    DCJOB_OVERALLJOBRESULTS_QUICKCONVERTPAIR: 'Paar Snel Converteren',
    DCJOB_OVERALLJOBRESULTS_AREYOUSUREYOUWANTTODELETE: 'Weet u zeker dat u [[insertHTMLWithLink]] uit Salesforce wil verwijderen',
    DCJOB_OVERALLJOBRESULTS_DELETERECORD: 'Verwijder Record',
    DCJOB_OVERALLJOBRESULTS_RECORD: 'Record',
    DCJOB_OVERALLJOBRESULTS_SELECTANOPTION: 'Optie Selecteren...',
    DCJOB_OVERALLJOBRESULTS_SEARCHOPTIONS: 'Zoek opties...',
    validation: {
        required: 'Dit veld is verplicht',
        max: 'Dit veld moet minder dan {max} karakters bevatten',
        invalid_cron_format: 'Ongeldige Cron-string. Controleer de indeling.',
        invalid_seconds_or_minutes: 'Ongeldige Cron-string. Gebruik alleen numerieke waarden voor seconden en minuten.',
        invalid_day_of_week_and_day_of_month_combination: 'Ongeldige Cron-string. Geef alleen de dag van de week of dag van de maand op.',
    },
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWPAIRVIEW: 'Overschakelen naar Paarweergave',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWGROUPVIEW: 'Overschakelen naar Groepsweergave',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFROMJOB: 'Groep uitsluiten van Job',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPINJOB: 'Groep in deze Job uitsluiten',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFOREVER: 'Groep voor altijd uitsluiten',
    DCJOB_OVERALLJOBRESULTS_FILTER_JOBTYPE: 'Type Job',
    DCJOB_OVERALLJOBRESULTS_FILTER_OWNER: '{objectName} Eigenaar',
    DCJOB_OVERALLJOBRESULTS_FILTER_RECORDTYPE: '{objectName} Recordtype',
    DCJOB_OVERALLJOBRESULTS_FILTER_PREDEFINED: 'Voorgedefinieerd Filter {objectName}',
    DCJOB_OVERALLJOBRESULTS_FILTER_FIELD: '{objectName} {fieldName}',
};
