export default {
    DCJOB_INFOMODALTAB_GENERALINFO: '基本信息',
    DCJOB_INFOMODALTAB_SELECTEDRECORDS: '选定的记录',
    DCJOB_INFOMODALTAB_APPLIEDSCENARIOS: '应用脚本',
    DCJOB_INFOMODALTAB_UNPROCESSEDRESULTS: '未处理结果',
    DCJOB_INFOMODALTAB_DUPLICATERESULTS: '发现重复项',
    DCJOB_INFOMODALTAB_CONVERTLOG: '转换日志',
    DCJOB_INFOMODALTAB_MERGELOG: '合并日志',
    DCJOB_OBJECT_USERS: '用户',
    DCJOB_OBJECT_GROUPS: '組',
    DCJOB_OBJECT_QUEUES: '队列',
    DCJOB_BUTTON_CANCEL: '取消',
    DCJOB_BUTTON_CALCULATING: '正在计算记录计数',
    DCJOB_BUTTON_TAKINGLONGER: '计算耗时稍长...',
    DCJOB_BUTTON_NEXTWITHLIMIT: '下一个有限制',
    DCJOB_BUTTON_ABORTING: '中止',
    DCJOB_BUTTON_REFRESH: '刷新',
    DCJOB_LINK_READMORE: '阅读更多',
    DCJOB_SHAREMODAL_SHAREMETHOD: '分享方法',
    DCJOB_SHAREMODAL_LINK: '链接',
    DCJOB_SHAREMODAL_COPY: '复制到剪贴板',
    DCJOB_SHAREMODAL_COPIED: '已复制到剪贴板',
    DCJOB_SHAREMODAL_SHAREJOB: '分享作业',
    DCJOB_SHAREMODAL_DIRECTLINK: '直接链接',
    DCJOB_SHAREMODAL_TASK: '创建一个任务',
    DCJOB_SHAREMODAL_EMAIL: '发送电子邮件',
    DCJOB_SHAREMODAL_RECIPIENTS: '收件人',
    DCJOB_SHAREMODAL_SUBJECT: '主题',
    DCJOB_SHAREMODAL_TEXT: '文本',
    DCJOB_SHAREMODAL_ASSIGNTO: '分配给',
    DCJOB_SHAREMODAL_STATUS: '状态',
    DCJOB_SHAREMODAL_DUEDATE: '到期日期',
    DCJOB_SHAREMODAL_DESCRIPTION: '描述',
    DCJOB_SHAREMODAL_PRIORITY: '优先级',
    DCJOB_SHAREMODAL_CREATETASK: '创建任务',
    DCJOB_SHAREMODAL_TASKSUCCESS: '任务创建成功',
    DCJOB_SHAREMODAL_EMAILSUCCESS: '邮件已发送',
    DCJOB_SHAREMODAL_SHAREINFO: '必须要有变量 {0} 来分享，请不要从文本字段中删除它。',
    DCJOB_PLACEHOLDER_SEARCH: '搜索',
    DCJOB_PLACEHOLDER_SUBJECT: '请输入主题',
    DCJOB_EDITJOB_SCHEDULE: '计划',
    DCJOB_NEWJOB_RUNONPLAUTICLOUD: '在 Plauti Cloud 上运行',
    DCJOB_NEWJOB_PLAUTICLOUDPROCESSDESCRIPTION: '使用 Plauti 提供的新处理选项 Plauti Cloud 来运行此作业。',
    DCJOB_NEWJOB_FILTERLOGIC: '筛选逻辑',
    DCJOB_NEWJOB_FILTERLOGICDESCRIPTION: '添加筛选器后，筛选器将被编号。 第一个筛选器将编号为筛选器 1，第二个筛选器将编号为筛选器 2，依此类推。 您应用基于这些数字筛选器的筛选逻辑。',
    DCJOB_NEWJOB_ADDSCHEDULE: '添加计划',
    DCJOB_NEWJOB_AUTOCONVERT: '自动转换',
    DCJOB_NEWJOB_AUTOMERGE: '自动合并',
    DCJOB_NEWJOB_ADDAUTOCONVERT: '添加自动转换',
    DCJOB_NEWJOB_ADDAUTOMERGE: '添加自动合并',
    DCJOB_NEWJOB_AUTOCONVERTTHRESHOLD: '自动转换阈值',
    DCJOB_NEWJOB_AUTOMERGETHRESHOLD: '自动合并阈值',
    DCJOB_NEWJOB_SCHEDULEDESCRIPTION: '计划此作业在设定的频率和时间运行。',
    DCJOB_NEWJOB_AUTOMERGEDESCRIPTION: '添加最低分数以在作业完成后立即自动合并重复记录。',
    DCJOB_NEWJOB_AUTOCONVERTDESCRIPTION: '添加最低分数以在作业完成后立即自动转换重复记录。',
    DCJOB_NEWJOB_REMOVEAUTOMERGE: '删除自动合并',
    DCJOB_NEWJOB_REMOVEAUTOCONVERT: '删除自动转换',
    DCJOB_NEWJOB_AUTOCONVERTWARNING: '转换记录不可撤销。',
    DCJOB_NEWJOB_AUTOMERGEWARNING: '合并记录不可撤销。',
    DCJOB_NEWJOB_CONVERTOWNERINFO: '潜在客户将作为新的联系人转换到目标客户。决定哪个用户应该是新联系人的所有人。',
    DCJOB_NEWJOB_CONVERTSTATUS: '转换后的状态',
    DCJOB_NEWJOB_CONVERTOWNER: '新联系人记录的所有人',
    DCJOB_NEWJOB_LEADOWNER: '当前潜在客户所有人',
    DCJOB_NEWJOB_ACCOUNTOWNER: '当前客户所有人',
    DCJOB_NEWJOB_LOOKUPUSER: '查找用户',
    DCJOB_NEWJOB_SFPROCESSDESCRIPTION: '在Salesforce 平台上运行此作业，无需任何数据传输。',
    DCJOB_NEWJOB_DCLOCALPROCESSDESCRIPTION: '使用 DC Local Desktop (DC Local 桌面) 或 DC Local Server (DC Local 服务器) 运行此作业。',
    DCJOB_NEWJOB_RECORDLIMITREACHED: '已达到许可记录限制',
    DCJOB_NEWJOB_RECORDLIMITDESCRIPTION: '根据当前选择的记录数量，这个作业将会进入许可的记录限制。 因此，并非所有选定的记录都会被分析以查找重复项。',
    DCJOB_NEWJOB_NORECORDSSELECTED: '没有选择记录。',
    DCJOB_NEWJOB_SELECTSCENARIO: '请选择至少一个脚本',
    DCJOB_NEWJOB_NOSCENARIO: '找不到 {0} 的脚本',
    DCJOB_NEWJOB_NOSELECTIONDESCRIPTION: '当前没有符合筛选条件的记录。考虑更改您的筛选器。您仍然可以继续配置计划的作业。',
    DCJOB_NEWJOB_SFRECOMMENDATION: '根据当前选择的记录数，我们建议处理 Salesforce 平台上的作业。 从15 000 条记录及以上，将建议使用 DC Local 进行更好的性能。',
    DCJOB_NEWJOB_DCLOCALRECOMMENDATION: '根据当前选择的记录数 (超过 15 000 条记录)，我们建议使用 DC Local 处理作业以提高性能。',
    DCJOB_NEWJOB_FILTERNOTFOUND: '所选的 {0} 筛选器选项“{1}”不再可用。',
    DCJOB_AUTOCONVERT_DCLOCALMESSAGE: '使用 DC Local Desktop (DC Local 桌面) 或 DC Local Server (DC Local 服务器) 运行此作业。目前尚不可用于自动转换。',
    DCJOB_AUTOCONVERT_CONVERTSTATUS: '转换后的状态',
    DCJOB_AUTOCONVERT_SELECTEDRECORDS: '为自动转换选择的记录数',
    DCJOB_AUTOCONVERT_NEWCONTACTOWNER: '新联系人记录的所有人',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE: '我承认开始这个自动转换作业将会转换 {0} 重复记录，并且转换记录不能撤消。',
    DCJOB_AUTOCONVERT_CONVERTACKNOWLEDGE_WITHOUT_RECORDCOUNT: '我承认开始这个自动转换作业将会转换重复记录，并且转换记录不能撤消。',
    DCJOB_AUTOCONVERT_NORECORDSSELECTED: '当前没有符合筛选条件的记录。请考虑更改您的筛选器。',
    DCJOB_AUTOCONVERT_TRIALWARNING: '由于您的试用许可证，自动转换限为 20 条记录。升级到付费许可证以取消限制。',
    DCJOB_AUTOMERGE_FILTERLOGIC: '筛选逻辑',
    DCJOB_AUTOMERGE_FILTERLOGICDESCRIPTION: '添加筛选器后，筛选器将被编号。 第一个筛选器将编号为筛选器 1，第二个筛选器将编号为筛选器 2，依此类推。 您应用基于这些数字筛选器的筛选逻辑。',
    DCJOB_AUTOMERGE_SELECTEDRECORDS: '为自动合并选择的记录数',
    DCJOB_AUTOMERGE_SELECTEDDUPLICATEPAIRS: '为自动合并选择的重复对数',
    DCJOB_AUTOMERGE_TRIALWARNING: '由于您的试用许可证，自动合并限为 20 条记录。升级到付费许可证以取消限制。',
    DCJOB_OVERVIEW_PROCESSEDBY: '处理于',
    DCJOB_OVERVIEW_DELETINGJOB: '删除作业',
    DCJOB_OVERVIEW_JOBABORTED: '作业已中止',
    DCJOB_ACCESS_CURRENTUSERNOACCESS: '当前用户无权访问必要的Apex 类。',
    DCJOB_ACCESS_REACHOUTTOADMINISTRATOR: '请联系您的Salesforce 管理员',
    DCJOB_ACCESS_DEACTIVATEDCJOBBETA: '停用 DC 作业测试版',
    DCJOB_ACCESS_YOUHAVENOACCESS: '您无权访问 Apex 类',
    DCJOB_FILTER_JOBTYPE: '作业类型',
    DCJOB_FILTER_DUPCHECKJOB: '重复作业',
    DCJOB_FILTER_DUPCHECKLOCAL: 'DC Local / Plauti Cloud',
    DCJOB_FILTER_UNIQUEBULKAPIINSERT: '唯一的导入 / 批量API 插入',
    DCJOB_FILTER_WEBTOLEAD: '网络到潜在客户',
    DCJOB_FILTER_SETFORMERGE: '设置为合并',
    DCJOB_FILTER_SINGLEAPIINSERT: '单个 API 插入',
    DCJOB_FILTER_FLOW: '流',
    DCJOB_FILTER_ABORTED: '已中止',
    DCJOB_FILTER_FAILED: '失败',
    DCJOB_FILTER_COMPLETED: '已完成',
    DCJOB_FILTER_HOLDING: '暂停',
    DCJOB_FILTER_PROCESSING: '正在处理',
    DCJOB_FILTER_INCAMPAIGN: '在市场活动中',
    DCJOB_FILTER_FILTER: '筛选器',
    DCJOB_JOBCARD_PROCESSEDWITHDCLOCAL: 'DC Local 作业',
    DCJOB_JOBCARD_PROCESSEDWITHCLOUD: 'Plauti Cloud 作业',
    DCJOB_JOBPAGE_APEXJOBID: 'Apex 作业 ID',
    ONBOARDING_NEXT: '下一个',
    ONBOARDING_BACK: '返回',
    ONBOARDING_FINISH: '结束',
    ONBOARDING_DOCUMENTATION: '文件',
    ONBOARDING_WATCH_VIDEO: '观看视频',
    ONBOARDING_GETTING_STARTED: '开始使用 Duplicate Check',
    ONBOARDING_THANK_YOU_FOR_INSTALLING: '感谢您安装 Duplicate Check',
    ONBOARDING_RUNNING_A_DC_JOB: '运行 DC 作业',
    ONBOARDING_SETUP_DUPLICATE_PREVENTION: '设置重复预防',
    ONBOARDING_LEARN_ABOUT_DCLIVE: '了解 DC 直播',
    ONBOARDING_HOW_TO_CONFIGURE_DC: '如何配置 Duplicate Check',
    ONBOARDING_OPTIONS_FOR_AUTOMATION: '自动化选项',
    ONBOARDING_INTEGRATION: '集成',
    ONBOARDING_CUSTOMISATION: '自定义',
    ONBOARDING_GET_STARTED: '让我们开始吧！',
    ONBOARDING_NOTIFICATION_JOB_STARTED: 'DC 作业于 {0} 开始',
    ONBOARDING_NOTIFICATION_VIEW_PROGRESS: '单击以在 DC 作业概述中查看进展',
    ONBOARDING_JOB_INFO_CARD_OPEN_RESULTS: '打开结果',
    ONBOARDING_JOB_INFO_CARD_STATUS: '状态',
    ONBOARDING_JOB_INFO_CARD_RESULT: '结果',
    ONBOARDING_INTRO_THANK_YOU_FOR_INSTALLING: '感谢您安装 Duplicate Check！',
    ONBOARDING_INTRO_OPENING_MESSAGE: '你好 Trailblazer! 我们很高兴看到你安装了 Salesforce的 Duplicate Check。 您要离开一个没有重复的无Salesforce 环境的几步，这个环境具有准确和可靠的数据。 这有助于改善决策，提高生产力，提高客户满意度。',
    ONBOARDING_INTRO_START_LOOKING_FOR_DUPLICATES: '我们冒昧地开始寻找一些重复…',
    ONBOARDING_INTRO_LOOKING_FOR_DUPLICATE_MESSAGE: '我们冒昧地在 1 000 {0} 记录上开始快速的作业，这样我们就可以向您展示在 {0} 对象中找到这些重复的记录是多么容易。 点击"打开结果"，随时查看新标签中的结果。',
    ONBOARDING_RUN_JOB_OPENING_MESSAGE: 'DC 作业是您所有重复据删除努力的出发点。 要在任何 Salesforce 对象中找到所有重复的记录，您可以运行一个 “Duplicate Check 作业“ ，也称为“DC 作业”。',
    ONBOARDING_RUN_JOB_START_FIRST_JOB_HELP: '让我们帮助你开始你的第一个作业！',
    ONBOARDING_RUN_JOB_START_NOW: '现在开始',
    ONBOARDING_RUN_JOB_STARTED: '已开始',
    ONBOARDING_RUN_JOB_LEAD_TITLE: '在潜在客户上运行作业',
    ONBOARDING_RUN_JOB_LEAD_DESCRIPTION: '通过比较名字、姓氏、电子邮件、公司和电话来查找重复之处。',
    ONBOARDING_RUN_JOB_CONTACT_TITLE: '在联系人上运行作业',
    ONBOARDING_RUN_JOB_CONTACT_DESCRIPTION: '通过比较名字、姓氏、电子邮件和电话查找重复之处。',
    ONBOARDING_RUN_JOB_ACCOUNT_TITLE: '在客户上运行作业',
    ONBOARDING_RUN_JOB_ACCOUNT_DESCRIPTION: '根据比较公司名称、开单城市和电话查找重复之处。',
    ONBOARDING_RUN_JOB_THINGS_TO_KNOW: '关于 DC 作业的信息',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_FEATURE: '跨对象功能',
    ONBOARDING_RUN_JOB_CROSS_OBJECT_MESSAGE: '使用 {0}比较任何对象的记录和任何其他对象的记录',
    ONBOARDING_RUN_JOB_PLAUTI_CLOUD: 'Plauti Cloud',
    ONBOARDING_RUN_JOB_LOCAL: 'DC Local',
    ONBOARDING_RUN_JOB_PROCESSING: '决定在哪里处理 DC 作业——完全在 Salesforce 内，或外部通过 {0} 或 {1}',
    ONBOARDING_RUN_JOB_MANUALLY: '手动',
    ONBOARDING_RUN_JOB_AUTOMATICALLY: '自动',
    ONBOARDING_RUN_JOB_MERGE_OR_CONVERT: '选择合并或转换 {0} 或 {1}',
    ONBOARDING_RUN_JOB_SCHEDULE_A_JOB: '计划作业',
    ONBOARDING_RUN_JOB_SCHEDULE_MESSAGE: '{0} 在您决定的频率和时间运行',
    ONBOARDING_PREVENTION_DUPLICATE_PREVENTION: '预防重复项',
    ONBOARDING_PREVENTION_OPENING_MESSAGE: '下面找到记录可以进入 Salesforce 的不同方法，并看看 DC 如何确保重复被检测到和处理。',
    ONBOARDING_PREVENTION_MANUAL_INSERT: '手动插入',
    ONBOARDING_PREVENTION_MANUAL_INSERT_DESCRIPTION: '即使是额外小心，重复也可以通过最终用户手动输入 Salesforce。 Duplicate Check 有一个很好的功能，您可以决定实现这个我们称之为“DC 条目”。通过访问文档了解更多信息。',
    ONBOARDING_PREVENTION_IMPORT: '导入',
    ONBOARDING_PREVENTION_IMPORT_DESCRIPTION: '当通过 Data Loader 或 Data Import 向导导导入记录时，重复数据将会找到到您的 Salesforce 环境的路径。 使用 Duplicate Check，在导入过程中标记了重复，然后您可以选择合并记录。 通过不阻止您的重复，您有机会保存最新信息。',
    ONBOARDING_PREVENTION_INTEGRATIONS: '集成(Salesforce API)',
    ONBOARDING_PREVENTION_INTEGRATIONS_DESCRIPTION: 'Salesforce 的平均实施与十几种外部工具相关联，所有这些工具都通过 Salesforce API 进行沟通，每天都有很多新记录。 Duplicate Check 可以监视 Salesforce API 频道，并在入口点检测任何重复。',
    ONBOARDING_PREVENTION_WEBFORMS: '网页表格',
    ONBOARDING_PREVENTION_WEBFORMS_DESCRIPTION: '如果您有与您的 Salesforce 环境链接的网页表格，您可能会很熟悉获取重复。 通过使用 Duplicate Check，您可以从任何网页表格中检测重复并实时处理重复。',
    ONBOARDING_DCLIVE_OPENING_MESSAGE: '在 Plauti，我们认为数据质量是整个组织的共同责任。这就是我们创建 DC 直播的原因。',
    ONBOARDING_DCLIVE_DESCRIPTION: 'DC 直播是一个您可以添加到任何对象页面布局的组件，并且是任何在 Salesforce 的用户都可以访问的。 当打开一个记录时，DC 直播显示打开的记录重复。',
    ONBOARDING_DCLIVE_EMPOWER_END_USERS: '让最终用户了解他们数据的质量，从而增强他们的能力，并决定允许他们进入 {0}或 {1}。',
    ONBOARDING_DCLIVE_MERGE_RECORDS_THEMSELVES: '自行合并记录',
    ONBOARDING_DCLIVE_FLAG_FOR_ADMIN: '标记它们以便管理员可以处理它们',
    ONBOARDING_DCLIVE_HOW_TO_CONFIGURE: '如何配置 DC 直播',
    ONBOARDING_CONFIGURE_OPENING_MESSAGE: 'Duplicate Check 擅长的事情之一是配置该工具，使其适应您独特的 Salesforce 实施。 为了充分利用该工具，请务必阅读以下主题。',
    ONBOARDING_CONFIGURE_SCENARIOS_SEARCH_INDEX: '脚本与搜索指数',
    ONBOARDING_CONFIGURE_SCENARIO_EXPLANATION: 'Duplicate Check 的脚本就像 Salesforce 中的“匹配规则”一样，它决定如何比较记录，并决定重复记录是什么。 为了最大限度地利用工具，我们建议阅读它可以做些什么以及如何配置它。',
    ONBOARDING_CONFIGURE_SEARCH_INDEX_EXPLANATION: '为了使脚本能够最佳运行，我们请您启用并创建搜索指数。 Duplicate Check 使用搜索指数来查找重复记录，使用的应用脚本。没有搜索指数，Duplicate Check 无法找到所有重复。',
    ONBOARDING_CONFIGURE_MERGE_RULES: '合并规则',
    ONBOARDING_CONFIGURE_MERGE_RULES_EXPLANATION: '当合并对象内的记录时， Duplicate Check 会调用合并规则来选择主记录并确定应该存储在主记录中的字段。 合并规则还决定在手动合并页面上预先选定哪些字段，并且在执行自动合并时执行合并规则。学习如何配置合并规则。',
    ONBOARDING_AUTOMATION_OPENING_MESSAGE: '作为原生 Salesforce，Duplicate Check 提供最好的实时重复检测和处理。',
    ONBOARDING_AUTOMATION_DC_LEVEL_OFFER: 'Duplicate Check 提供不同的自动化级别',
    ONBOARDING_AUTOMATION_EXPLANATION: '自动化水平不同，从人类操作到完全自动化流程。了解更多关于自动化的信息并选择对您合适的内容。',
    ONBOARDING_AUTOMATION_AUDIT_LOG: '审计日志',
    ONBOARDING_AUTOMATION_AUDIT_LOG_DESCRIPTION: '手动或自动执行的任何合并或转换活动都可以在审计日志中进行跟踪。 需要启用审计日志才能存储日志，因为这需要一些存储空间。',
    ONBOARDING_AUTOMATION_DIRECT_PROCESSING: '直接处理',
    ONBOARDING_INTEGRATION_OPENING_MESSAGE: '您选择了Salesforce，因为它具有整合您所有业务流程的灵活性。我们的 Apex 插件、流操作、API 插件和 SFDX 插件可确保重复据删除与您现有的流程无缝集成。',
    ONBOARDING_INTEGRATION_APEX_API: 'Duplicate Check Apex API',
    ONBOARDING_INTEGRATION_APEX_API_DESCRIPTION: 'Duplicate Check 提供了一个 Apex API ，使您能够实现您自己的 Apex项目中的所有 DC 功能。 这包括通过 DC 搜索引擎找到重复记录，合并和转换，但也允许您通过 API 导出 DC 配置集。合并和转换找到重复记录，但也允许您通过 API 导出 DC 配置集。',
    ONBOARDING_INTEGRATION_REST_API: 'Duplicate Check Rest API',
    ONBOARDING_INTEGRATION_REST_API_DESCRIPTION: 'Duplicate Check 提供了一个 REST API，可用来搜索或插入/更新 Salesforce 中的记录通过数据 API。REST 数据 API 允许您创建记录而不创建重复记录。 当一个记录通过数据API添加时，它将直接与Salesforce中所有现有记录进行比较。 如果存在重复记录，它将更新现有记录，而不是创建重复记录。',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS: 'Duplicate Check 流操作',
    ONBOARDING_INTEGRATION_FLOW_ACTIONS_DESCRIPTION: 'Duplicate Check 以流操作的形式提供了它的大多数功能。 因此，您可以在任何 Salesforce 流中实现与重复预防、合并、转换和更多功能相关的所有功能。',
    ONBOARDING_CUSTOMISATION_OPENING_MESSAGE: '您选择了Salesforce，因为它具有整合您所有业务流程的灵活性。我们的 Apex 插件、流操作、API 插件和 SFDX 插件可确保重复据删除与您现有的流程无缝集成。',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS: 'Duplicate Check 插件',
    ONBOARDING_CUSTOMISATION_DC_PLUGINS_DESCRIPTION: '我们知道，企业有非常具体的程序，很难找到一个能够适应困难要求的工具。 如果您希望更改开箱即用的功能，请使用 Duplicate Check 提供的插件。',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS: 'SFDX 插件',
    ONBOARDING_CUSTOMISATION_SFDX_PLUGINS_DESCRIPTION: 'SFDX 插件允许开发者将与 Duplicate Check 许可以及 Duplicate Check 配置相关的任务自动化。 例如，如果您构建了具有不同暂存环境的管道，则可以自动同步 Duplicate Check 配置，以便它在所有环境中都相同。',
    ONBOARDING_GET_STARTED_A_LOT_OF_INFO: '这是很多信息，对吗？',
    ONBOARDING_GET_STARTED_OPENING_MESSAGE: '您现在知道 Duplicate Check 可以做什么的基础知识。我们知道需要接受的东西有很多。 您现在已经准备好开始走向一个无重复的 Salesforce 境的旅程，它将提供令人惊奇的优势。',
    ONBOARDING_GET_STARTED_FEELING_LOST: '感觉丢失了？可以自由地安排与我们的产品专家一对一的会议。',
    ONBOARDING_GET_STARTED_SCHEDULE_CALL: '用我们的产品专家来安排通话！',
    ONBOARDING_GET_STARTED_FLYING_START: '想要一个飞行开始实现您的组织 Duplicate Check 吗？ 请免费安排与我们的一位产品专家通话。 我们非常乐于引导您探索和配署 Duplicate Check 。',
    ONBOARDING_GET_STARTED_SCHEDULE_A_CALL: '安排来电',
    ONBOARDING_GET_STARTED_INTERESTING_LINKS: '有趣的链接',
    ONBOARDING_GET_STARTED_SCHEDULE_PRODUCT_EXPERT: '用产品专家安排来电',
    ONBOARDING_GET_STARTED_KNOWLEDGEBASE: '知识库',
    ONBOARDING_GET_STARTED_HOWTO_VIDEOS: '有关如何使用的视频',
    ONBOARDING_GET_STARTED_GUIDE: '入门指南',
    ONBOARDING_GET_STARTED_CONTACT_SUPPORT: '联系客服',
    general: {
        DCJOB_AUTOCONVERT_LEARNMORE: '了解更多',
        DCJOB_AUTOMERGE_LEARNMORE: '了解更多',
        DCJOB_NEWJOB_LEARNMORE: '了解更多',
        DCJOB_AUTOMERGE_SPEED: '速度',
        DCJOB_NEWJOB_SPEED: '速度',
        DCJOB_NEWJOB_MEDIUM: '中',
        DCJOB_AUTOMERGE_MEDIUM: '中',
        DCJOB_NEWJOB_RECOMMENDED: '推荐的',
        DCJOB_AUTOMERGE_RECOMMENDED: '推荐的',
        DCJOB_AUTOCONVERT_RECOMMENDED: '推荐的',
        DCJOB_DELETEMODAL_ALLTIME: '全部时间',
        DCJOB_DELETEMODAL_SETDATE: '设定日期',
        DCJOB_DELETEMODAL_SETDATERANGE: '设定日期范围',
        DCJOB_DELETEMODAL_FROM: '从',
        DCJOB_DELETEMODAL_UNTIL: '到',
        DCJOB_DELETEMODAL_TYPE: '类型',
        DCJOB_DELETEMODAL_DATE: '日期',
        DCJOB_JOBPAGE_OBJECT: '对象',
        DCJOB_SCHEDULEDJOBPAGE_OBJECT: '对象',
        DCJOB_SCHEDULEDJOBPAGE_NOTAPPLICABLE: '不适用',
        DCJOB_SCHEDULEDJOBPAGE_NOME: '名称',
        DCJOB_SCHEDULEDJOBPAGE_FREQUENCYANDTIME: '频率和时间',
        DCJOB_SCHEDULEDJOBPAGE_STATUS: '状态',
        DCJOB_SCHEDULEDJOBPAGE_NEXTSTART: '下一次开始',
        DCJOB_PAGINATIONCOMPONENT_PAGE: '页',
        DCJOB_PAGINATIONCOMPONENT_OF: '共',
    },
    groupObject: {
        GROUPNUMBER: '组号',
        GROUPPAIRCOUNT: '此组中的重复对计数',
        GROUPRECORDCOUNT: '此组中的记录计数',
        GROUPCONTAINSMERGEERROR: '包含合并错误的组',
        GROUPCONTAINSCONVERTERROR: '包含转换错误的组',
        GROUPFOUNDJOB: 'Found in Job',
    },
    days: {
        DCJOB_NEWJOB_MONDAY: '周一',
        DCJOB_NEWJOB_TUESDAY: '周二',
        DCJOB_NEWJOB_WEDNESDAY: '周三',
        DCJOB_NEWJOB_THURSDAY: '周四',
        DCJOB_NEWJOB_FRIDAY: '周五',
        DCJOB_NEWJOB_SATURDAY: '周六',
        DCJOB_NEWJOB_SUNDAY: '周日',
    },
    monthly: {
        LAST_DAY: '最后一天',
        LAST_WEEKDAY: '上一周日',
    },
    frequency: {
        DCJOB_SCHEDULED_FREQUENCY_PLACEHOLDER: '选择一个选项...',
        DCJOB_SCHEDULED_FREQUENCY_DAILY: '每天',
        DCJOB_SCHEDULED_FREQUENCY_WEEKLY: '每周',
        DCJOB_SCHEDULED_FREQUENCY_MONTHLY: '每月',
        DCJOB_SCHEDULED_FREQUENCY_CUSTOM: '自定义',
    },
    titles: {
        DCJOB_JOBPAGE_JOBOVERVIEW: '作业概况',
        DCJOB_SCHEDULEDJOBPAGE_SCHEDULEDJOB: '计划作业概况',
        DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOB: '删除计划的作业',
        DCJOB_JOBPAGE_LISTVIEWS: '列表视图',
    },
    buttons: {
        DCJOB_JOBCARD_ABORT: '中止',
        DCJOB_BACK: '返回',
        DCJOB_NEWJOB_BACK: '返回',
        DCJOB_AUTOMERGE_BACK: '返回',
        DCJOB_AUTOCONVERT_BACK: '返回',
        DCJOB_JOBPAGE_CANCEL: '取消',
        DCJOB_NEWJOB_CANCEL: '取消',
        DCJOB_JOBCARD_CANCEL: '取消',
        DCJOB_EXPORTMODAL_CANCEL: '取消',
        DCJOB_DELETEMODAL_CANCEL: '取消',
        DCJOB_AUTOMERGE_CANCEL: '取消',
        DCJOB_AUTOCONVERT_CANCEL: '取消',
        DCJOB_SCHEDULEDJOBPAGE_CANCEL: '取消',
        DCJOB_SCHEDULEDJOBPAGE_DELETEJOBS: '删除作业',
        DCJOB_JOBPAGE_DELETEJOBS: '删除作业',
        DCJOB_DELETEMODAL_DELETEJOBS: '删除作业',
        DCJOB_SCHEDULEDJOBPAGE_DELETE: '删除',
        DCJOB_JOBCARD_DELETE: '删除',
        DCJOB_DELETEMODAL_DELETE: '删除',
        DCJOB_EXPORTMODAL_EXPORTDCLOCAL: '通过 DC Local 导出',
        DCJOB_EXPORTMODAL_EXPORTCLOUD: '通过 Plauti Cloud 导出',
        DCJOB_JOBPAGE_FILTER: '筛选器',
        DCJOB_NEWJOB_FILTER: '筛选器',
        DCJOB_FILTER: 'Filter',
        DCJOB_SCHEDULEDJOBPAGE_INFO: '信息',
        DCJOB_JOBCARD_INFO: '信息',
        DCJOB_SCHEDULEDJOBPAGE_EDIT: '编辑',
        DCJOB_SCHEDULEDJOBPAGE_JOBOPTIONS: '作业选项',
        DCJOB_JOBCARD_JOBOPTIONS: '作业选项',
        DCJOB_SCHEDULEDJOBPAGE_NEWJOB: '新建作业',
        DCJOB_JOBPAGE_NEWJOB: '新建作业',
        DCJOB_NEWJOB_NEXT: '下一个',
        DCJOB_AUTOMERGE_NEXT: '下一个',
        DCJOB_AUTOCONVERT_NEXT: '下一个',
        DCJOB_JOBPAGE_SAVE: '保存',
        DCJOB_NEWJOB_START: '开始',
        DCJOB_NEWJOB_SCHEDULE: '计划',
        DCJOB_AUTOMERGE_START: '开始',
        DCJOB_AUTOCONVERT_START: '开始',
        DCJOB_JOBPAGE_SORTJOBS: '排序作业',
        DCJOB_SCHEDULEDJOBPAGE_RUNNOW: '立即运行一次',
        DCJOB_SCHEDULEDJOBPAGE_DEACTIVATED: '停用',
        DCJOB_SCHEDULEDJOBPAGE_ACTIVATE: '激活',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS_NUMBER: '查看结果 {0}',
        DCJOB_OVERALLJOBRESULTS_VIEWRESULTS: '查看结果',
        MERGE: '合并',
        QUICKMERGE: '快速合并',
        QUICKCONVERT: '快速转换',
        MORE: '更多',
        edit: '编辑',
        DCJOB_JOBCARD_VIEWRESULTS: '查看结果 {0}',
        DCJOB_JOBPAGE_DELETESELECTEDJOBS: 'Delete Selected Jobs',
        DCJOB_JOBPAGE_SELECTALL: 'Select All',
        DCJOB_JOBPAGE_DESELECTALL: 'Deselect All',
    },
    badges: {
        DCJOB_JOBCARD_REVIEWERRORS: '检查错误',
        DCJOB_JOBCARD_READMORE: '阅读更多',
        DCJOB_JOBCARD_LIMITTEXT: '已达到许可记录限制。',
        DCJOB_JOBCARD_DELETESELECTED: `{count} job selected | {count} jobs selected`,
    },
    metaData: {
        DCJOB_JOBPAGE_AVERAGESCORE: '平均得分',
        DCJOB_OVERALLJOBRESULTS_AVERAGESCORE: '平均得分',
        DCJOB_JOBPAGE_STORAGESPACETAKEN: '已拿取存储空间',
        DCJOB_JOBPAGE_TOTALGROUPS: '组总数',
        DCJOB_JOBPAGE_TOTALJOBS: '全部作业',
        DCJOB_JOBPAGE_TOTALPAIRS: '总对数',
        DCJOB_JOBPAGE_TOTALRECORDS: '总记录数',
        DCJOB_OVERALLJOBRESULTS_RECORDS: '记录',
        DCJOB_OVERALLJOBRESULTS_GROUPS: '組',
        DCJOB_OVERALLJOBRESULTS_PAIRS: '配对',
        DCJOB_OVERALLJOBRESULTS_OBJECT: '对象',
    },
    job: {
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDTITLE: '审计日志在您的许可证中不可用',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDSUBTITLE: '审计日志在高级版及更高版本中可用',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDBUTTON: '立即升级',
        DCJOB_EMPTYAUDITLOG_NOTLICENSEDRUPGRADEURL: 'https://go.plauti.com/l/640773/2023-03-27/53tydt',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDTITLE: '审计日志已禁用',
        DCJOB_EMPTYAUDITLOG_NOTENABLEDSUBTITLE: '请询问您的 Salesforce 管理员以启用 Duplicate Check 审计日志。',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGETITLE: '合并日志为空',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTTITLE: '转换日志为空',
        DCJOB_EMPTYAUDITLOG_NOLOGSMERGESUBTITLE: '此作业还没有合并活动。',
        DCJOB_EMPTYAUDITLOG_NOLOGSCONVERTSUBTITLE: '此作业还没有转换活动。',
        DCJOB_AUDITLOGTABLEHEADER_MASTERRECORD: '主记录',
        DCJOB_AUDITLOGTABLEHEADER_MERGEDRECORDS: '合并的记录',
        DCJOB_AUDITLOGTABLEHEADER_LEADRECORD: '潜在客户记录',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOPERSON: '转换为个人客户',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOACCOUNT: '转换到客户',
        DCJOB_AUDITLOGTABLEHEADER_CONVERTTOCONTACT: '转换到联系人',
        DCJOB_AUDITLOGTABLEHEADER_METHOD: '方法',
        DCJOB_AUDITLOGTABLEHEADER_DATETIME: '日期和时间',
        DCJOB_AUDITLOGTABLEHEADER_USER: '用户',
        DCJOB_AUDITLOGTOOLTIP_CONVERTEDRECORD: '转换的记录',
        DCJOB_AUDITLOGTOOLTIP_MERGEDRECORD: '合并的记录',
        DCJOB_AUDITLOGTOOLTIP_RECORDID: '记录 ID:',
        DCJOB_AUDITLOGTOOLTIP_AUDITID: '审计 ID：',
        DCJOB_AUDITLOGSUMMARY_NUMBEROFRECORDS: '记录数 {0}',
        DCJOB_JOBCARD_JOBS: '作业',
        DCJOB_JOBCARD_TASK: '任务',
        DCJOB_JOBCARD_STARTED: '开始于',
        DCJOB_JOBCARD_FINISHED: '完成于',
        DCJOB_JOBCARD_USER: '开始人',
        DCJOB_JOBCARD_STATUS: '状态',
        DCJOB_JOBPAGE_STATUS: '状态',
        DCJOB_JOBCARD_RESULT: '结果',
        DCJOB_JOBPAGE_JOBNAME: '作业名称',
        DCJOB_NEWJOB_JOBNAME: '作业名称',
        DCJOB_JOBCARD_JOBNAME: '作业名称',
        DCJOB_AUTOMERGE_JOBNAME: '作业名称',
        DCJOB_AUTOCONVERT_JOBNAME: '作业名称',
        DCJOB_JOBPAGE_JOBID: '作业 ID',
        DCJOB_JOBCARD_JOBID: '作业 ID',
        DCJOB_JOBPAGE_NOJOBS: '无作业。',
        DCJOB_SCHEDULEDJOBPAGE_NOSCHEDULEDJOBS: '没有计划的作业。',
        DCJOB_NEWJOB_JOBNAMEPLACEHOLDER: '请输入作业名称',
        DCJOB_JOBCARD_AUTOMERGE: '自动合并',
        DCJOB_JOBCARD_MANUALMERGE: '手动合并',
        DCJOB_JOBCARD_QUICKMERGE: '快速合并',
        DCJOB_JOBCARD_AUTOCONVERT: '自动转换',
        DCJOB_JOBCARD_MANUALCONVERT: '手动转换',
        DCJOB_JOBCARD_MERGELOG: '合并日志',
        DCJOB_JOBCARD_CONVERTLOG: '转换日志',
        DCJOB_JOBCARD_QUICKCONVERT: '快速转换',
        DCJOB_JOBCARD_AUTOMERGEDCLOCAL: '通过 DC Local 自动合并',
        DCJOB_JOBCARD_AUTOMERGECLOUD: '通过 Plauti Cloud 自动合并',
        DCJOB_AUTOMERGE_CONFIGUREAUTOMERGE: '配置自动合并',
        DCJOB_AUTOCONVERT_CONFIGUREAUTOCONVERT: '配置自动转换',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE: '我承认开始这个自动自动合并作业将会合并 {0} 重复记录，并且合并记录不能撤消。',
        DCJOB_AUTOMERGE_AUTOMERGEACKNOWLEDGE_WITHOUT_RECORDCOUNT: '我承认开始这个自动自动合并作业将会合并重复记录，并且合并记录不能撤消。',
        DCJOB_EXPORTMODAL_EXPORTRESULTS: '导出结果',
        DCJOB_JOBCARD_EXPORTRESULTSDCLOCAL: '通过 DC Local 导出结果',
        DCJOB_JOBCARD_EXPORTRESULTSCLOUD: '通过 Plauti Cloud 导出结果',
        DCJOB_JOBCARD_NUMBEROFRECORDS: '记录数',
        DCJOB_JOBPAGE_NUMBEROFRECORDS: '记录数',
        DCJOB_JOBCARD_NUMBEROFPAIRS: '配对数',
        DCJOB_JOBCARD_RESULTFIELDS: '结果字段',
        DCJOB_AUTOMERGE_CONFIRMATION: '确认',
        DCJOB_AUTOCONVERT_CONFIRMATION: '确认',
        DCJOB_AUTOMERGE_PROCESSEDBY: '处理于',
        DCJOB_AUTOCONVERT_PROCESSEDBY: '处理于',
        DCJOB_DELETEMODAL_CURRENTNUMBEROFJOBS: 'DC 作业中当前作业的数量',
        DCJOB_DELETEMODAL_JOBSCREATEDAT: '作业创建于',
        DCJOB_DELETEMODAL_CONTAINSDUPLICATERESULTS: '包含重复结果',
        DCJOB_DELETEMODAL_JOBSSELECTEDFORDELETION: '选择要删除的作业数',

        infoModal: {
            DCJOB_INFOMODAL_GENERALINFO_STARTEDBYUSER: '由用户启动',
            DCJOB_INFOMODAL_GENERALINFO_STATUS: '状态',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMESTARTED: '开始日期和时间',
            DCJOB_INFOMODAL_GENERALINFO_DATETIMEFINISHED: '完成日期和时间',
            DCJOB_INFOMODAL_GENERALINFO_TOTALTIMETAKEN: '总耗时',
            DCJOB_INFOMODAL_GENERALINFO_PROCESSEDBY: '处理于',
            DCJOB_INFOMODAL_GENERALINFO_LASTDUPLICATEADDED: '最后一次添加重复项时间',
            DCJOB_INFOMODAL_GENERALINFO_APPLIEDSCENARIOS: '应用脚本',
            DCJOB_INFOMODAL_GENERALINFO_JOBID: '作业 ID',
            DCJOB_INFOMODAL_GENERALINFO_APEXJOBID: 'Apex 作业 ID',
            DCJOB_INFOMODAL_GENERALINFO_CREATEDBYUSER: '由用户创建',
            DCJOB_INFOMODAL_GENERALINFO_FREQUENCY: '频率',
            DCJOB_INFOMODAL_GENERALINFO_LASTRUNAT: '最后运行时间',
            DCJOB_INFOMODAL_GENERALINFO_NEXTRUNAT: '下一次运行时间',
            DCJOB_INFOMODAL_GENERALINFO_NUMBEROFTIMESRUN: '运行次数',
            DCJOB_INFOMODAL_GENERALINFO_AUTOPROCESS: 'Auto process',
            DCJOB_INFOMODAL_GENERALINFO_SCHEDULED_LASTMODIFIED: '计划的作业最后修改时间 + 日期和时间',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEGROUPS: '重复组',
            DCJOB_INFOMODAL_DUPLICATESINFO_DUPLICATEPAIRS: '重复配对',
            DCJOB_INFOMODAL_DUPLICATESINFO_RECORDSINVOLVED: '涉及的记录',
            DCJOB_INFOMODAL_DUPLICATESINFO_AVERAGESCORE: '平均得分',
            DCJOB_INFOMODAL_SELECTEDINFO_OBJECT: '对象',
            DCJOB_INFOMODAL_SELECTEDINFO_NUMBEROFRECORDS: '记录数',
            DCJOB_INFOMODAL_SELECTEDINFO_SOURCE: 'Source',
            DCJOB_INFOMODAL_SELECTEDINFO_MATCH: 'Match'
        },
        sortOptions: {
            DCJOB_JOBPAGE_SORTBY: '排序方式',
            DCJOB_JOBPAGE_DATETIMESTARTED: '开始于',
            DCJOB_JOBPAGE_DATETIMEFINISHED: '完成于',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEGROUPS: '重复组数',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATEPAIRS: '重复配对数',
            DCJOB_JOBPAGE_NUMBEROFDUPLICATERECORDSINVOLVED: '涉及重复记录的数',
            DCJOB_JOBPAGE_LASTDUPLICATEADDED: '最后一次添加重复项时间',
            DCJOB_JOBPAGE_ORDER: '顺序',
            DCJOB_JOBPAGE_ASCENDING: '升序',
            DCJOB_JOBPAGE_DESCENDING: '降序',
        },
        menuOptions: {
            DCJOB_SCHEDULEDJOBPAGE_TITLE: '作业选项',
            DCJOB_JOBCARD_TITLE: '作业选项',
            DCJOB_JOBCARD_OPTION_RESTART: '重新启动',
            DCJOB_JOBCARD_OPTION_STARTAUTOMERGE: '开始自动合并',
            DCJOB_JOBCARD_OPTION_STARTAUTOCONVERT: '开始自动转换',
            DCJOB_JOBCARD_OPTION_EXPORTRESULTS: '导出结果',
            DCJOB_JOBCARD_OPTION_SHAREJOB: '分享作业',
            DCJOB_JOBCARD_OPTION_DELETEJOB: '删除作业',
        },

        new: {
            DCJOB_NEWJOB_STEP: '步骤',
            DCJOB_AUTOMERGE_STEP: '步骤',
            DCJOB_AUTOCONVERT_STEP: '步骤',
            DCJOB_NEWJOB_SELECTRECORDS: '选择记录',
            DCJOB_NEWJOB_JOBOPTIONS: '作业选项',
            DCJOB_NEWJOB_PROCESSOPTIONS: '处理选项',
            DCJOB_NEWJOB_SELECTOBJECT: '选择对象',
            DCJOB_NEWJOB_SELECTOBJECTPLACEHOLDER: '请选择对象',
            DCJOB_NEWJOB_SELECTOPTIONSPLACEHOLDER: '搜索选项...',
            DCJOB_NEWJOB_ADDCROSSOBJECT: '添加跨对象',
            DCJOB_NEWJOB_REMOVECROSSOBJECT: '删除跨对象',
            DCJOB_NEWJOB_ADDFILTER: '添加筛选器',
            DCJOB_NEWJOB_MATCHWITH: '匹配',
        },

        deleteAll: {
            DCJOB_DELETESELECTED_TITLE: 'Delete Selected Jobs',
            DCJOB_DELETESELECTED_MESSAGE: 'Are you sure you want to delete {count} selected job? This action cannot be undone. | Are you sure you want to delete {count} selected jobs? This action cannot be undone.',
        },

        delete: {
            DCJOB_DELETEMODAL_DELETEJOBSMESSAGE: '您确定要删除 {0} 作业吗？删除作业不能撤消。',
            DCJOB_JOBCARD_DELETEMESSAGE: '您确定要删除 {0} 吗？',
            DCJOB_JOBCARD_DELETEUNDONE: '{0} 删除无法撤销。',
            DCJOB_SCHEDULEDJOBPAGE_DELETESCHEDULEJOBMESSAGE: '您确定要删除 "{0}" 计划的作业吗？',
        },

        options: {
            DCJOB_NEWJOB_SCHEDULE: '计划',
            addScheduler: '添加计划',
            scheduleDescription: '决定计划此批次运行在配置的频率和时间。',
            autoMergeDescription: '决定在批处理完成后立即自动合并重复记录的阈值。 请注意，自动合并也可以随时手动启动。',
            DCJOB_NEWJOB_REMOVESCHEDULER: '删除计划',
            addAutoMerge: '添加自动合并',
            removeAutoMerge: '删除自动合并',
            DCJOB_NEWJOB_FREQUENCY: '频率',
            DCJOB_NEWJOB_CRONSTRING: 'Cron 字符串',
            DCJOB_NEWJOB_CRONSTRING_INFO: '使用 Cron 字符串格式 \* * * * * * * \ 通过指定秒、分、小时、日、月和星期几计划 DC 作业。',
            DCJOB_NEWJOB_RECURS: '每周重复日',
            DCJOB_NEWJOB_MONTHRECURS: '每月重复一次于',
            DCJOB_NEWJOB_PREFERREDSTARTTIME: '首选开始时间',
            DCJOB_NEWJOB_PREFERREDSTARTTIMEINFO: 'Salesforce 计划 DC 作业在指定时间执行。实际执行可能会根据服务可用性而延迟。',
            DCJOB_AUTOMERGE_AUTOMERGETHRESHOLD: '自动合并阈值',
            DCJOB_AUTOMERGE_AUTOMERGETEXT: '完成作业后，所有具有等于或高于 {0}%的匹配百分比的重复对将被自动合并。',
            DCJOB_NEWJOB_AUTOMERGETEXT: '完成作业后，所有具有等于或高于 {0}%的匹配百分比的重复对将被自动合并。',
            DCJOB_NEWJOB_AUTOCONVERTEXPLANATION: '所有具有等于或高于 {0}%的匹配百分比的重复对都会自动转换。',
            DCJOB_AUTOCONVERT_AUTOCONVERTEXPLANATION: '所有具有等于或高于 {0}%的匹配百分比的重复对都会自动转换。',
            DCJOB_AUTOMERGE_AUTOMERGEWARNING: '合并记录不可撤销。',
            DCJOB_NEWJOB_PROCESSINGOPTIONS: '处理选项',
            DCJOB_AUTOMERGE_PROCESSINGOPTIONS: '处理选项',
            DCJOB_AUTOCONVERT_PROCESSINGOPTIONS: '处理选项',
            DCJOB_NEWJOB_RUNONSF: '在Salesforce 平台上运行',
            DCJOB_AUTOMERGE_RUNONSF: '在Salesforce 平台上运行',
            DCJOB_AUTOCONVERT_RUNONSF: '在Salesforce 平台上运行',
            DCJOB_NEWJOB_RUNONDCLOCAL: '在 DC Local 运行',
            DCJOB_AUTOMERGE_RUNONDCLOCAL: '在 DC Local 运行',
            DCJOB_AUTOCONVERT_RUNONDCLOCAL: '在 DC Local 运行',
            DCJOB_AUTOMERGE_SFINFO: '基于被选择用于自动合并进程的重复对数，我们建议处理Salesforce平台上的作业。',
            DCJOB_AUTOCONVERT_SFINFO: '基于被选择用于自动合并进程的重复对数，我们建议处理Salesforce平台上的作业。',
            DCJOB_AUTOMERGE_DCLOCALINFO: '基于被选择用于自动合并过程的重复对数，我们建议处理 DC Local 上的作业。',
            DCJOB_AUTOCONVERT_DCLOCALINFO: '基于被选择用于自动合并过程的重复对数，我们建议处理 DC Local 上的作业。',
            DCJOB_AUTOMERGE_SFPLATFORMMESSAGE: '在 Salesforce 平台上运行此作业(原生)。',
            DCJOB_AUTOMERGE_DCLOCALMESSAGE: '使用 DC Local Desktop (DC Local 桌面) 或 DC Local Server (DC Local 服务器) 运行此作业。',
            DCJOB_AUTOMERGE_ADDOBJECTFILTER: '添加 {0} 筛选器',
            DCJOB_AUTOMERGE_REMOVEOBJECTFILTER: '删除 {0} 筛选器',
            DCJOB_AUTOMERGE_ADDFILTERLINE: '添加筛选线',
            DCJOB_AUTOCONVERT_ADDFILTERLINE: '添加筛选线',
            DCJOB_AUTOMERGE_OBJECTFILTER: '{0} 筛选器',
        },
    },
    scenario: {
        DCJOB_NEWJOB_SCENARIO: '脚本',
        DCJOB_NEWJOB_SCENARIOINFO: '在跨对象作业中，只有匹配对象的脚本是可用的。',
        DCJOB_SCENARIOCARD_SCENARIONAME: '脚本名称',
        DCJOB_SCENARIOCARD_THRESHOLD: '阈值',
        DCJOB_SCENARIOCARD_EMPTYFIELDS: '空字段',
        fields: {
            DCJOB_SCENARIOCARD_FIELD: '字段',
            DCJOB_SCENARIOCARD_FREQUENTWORDS: '常用词',
            DCJOB_SCENARIOCARD_MATCHINGMETHOD: '匹配方法',
            DCJOB_SCENARIOCARD_WEIGHT: '权重',
        },
    },
    filter: {
        DCJOB_INFOMODAL_READMOREINFO: '添加筛选器后，筛选器会被编号。您的第一个筛选器会变成筛选器1，您的第二个筛选器会变成筛选器2。根据这些数字应用筛选逻辑。点击本图标阅读更多信息 。',
        DCJOB_INFOMODAL_FILTER: '筛选器',
        DCJOB_INFOMODAL_SOURCEFILTER: '源筛选器',
        DCJOB_INFOMODAL_MATCHFILTER: '匹配筛选器',
        DCJOB_INFOMODAL_AUTOMERGE_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOMERGE_GROUPFILTER: 'Auto Merge Group Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_SOURCEFILTER: 'Auto Merge Source Filter',
        DCJOB_INFOMODAL_AUTOCONVERT_GROUPFILTER: 'Auto Convert Group Filter',
        DCJOB_JOBPAGE_FILTERJOBS: '筛选作业',
        DCJOB_JOBPAGE_NOFILTERAPPLIED: '未应用任何筛选器。',
        addFilter: '添加筛选器',
        operators: {
            DCJOB_SCHEDULEDJOBPAGE_OR: '或',
            DCJOB_JOBINFO_OR: '或',
        },
        removeFilter: '删除筛选器',
        DCJOB_NEWJOB_SETFILTER: '设置筛选器',
        DCJOB_NEWJOB_ALLRECORDS: '没有过滤器，处理所有记录',
        DCJOB_NEWJOB_COMPARERECORDSINABOVEFILTERWITH: '将上面筛选器中的记录与',
        DCJOB_NEWJOB_RECORDSTHATMEETCRITERIA: '符合以上筛选条件的记录',
        jobFilterFields: {
            DCJOB_JOBPAGE_STARTEDBYUSER: '启动用户',
            DCJOB_JOBPAGE_CONTAINSFILTER: '包含筛选器',
            DCJOB_JOBPAGE_CONTAINSAUTOMERGE: '包含自动合并',
            DCJOB_JOBPAGE_CONSTAINSAUTOCONVERT: '包含自动转换',
        },
        startedScheduledJob: '{0} 正在运行',
        activeScheduledJob: '{0} 现已激活',
        deactivatedScheduledJob: '{0} 现已停用',
        DCJOB_JOBPAGE_FILTERSAVED: '成功保存筛选器。',
        addFilterlineLabel: '添加筛选线',
        newFilterlinePlaceholder: '添加筛选线',
        fieldLabel: '字段',
        fieldPlaceholder: '选择一个选项...',
        fieldPlaceholderSearch: '搜索选项...',
        operatorLabel: '运算符',
        emptyValueLabel: '空',
        emptyOptionLabel: '- none -',
        addFilterLogicLabel: '添加筛选逻辑。',
        removeFilterLogicLabel: '移除筛选逻辑。',
        doneButton: '完成',
        inputLabels: {
            Value: '值',
            Date: '日期',
            Time: '时间',
            'Start date': 'Start Date',
            'End date': 'End Date',
            'Start Time': 'Start Time',
            'End Time': 'End Time',
        },
        logic: {
            ErrorUnusedFilters: '有一个未使用的筛选线',
            ErrorTypo: '有一个错字',
            ErrorBadNumber: '{0} 不能在过筛选逻辑中使用',
            ErrorMissingRightOperand: '缺少括号',
            ErrorAmbiguousAndOr: '使用 AND + OR 时添加括号',
            ErrorMissingOperand: 'NOT 后面应该跟一个操作数',
            ErrorParen: '意外的括号',
        },
    },
    matchingMethods: {
        EQUAL: '精确的',
        EQUAL_RANDOM: '精确(随机顺序)',
        NOT_EQUAL: '不等于',
        EQUAL_NULL: '等于空值',
        FUZZY_PERSON: '人员姓名',
        FUZZY_COMPANY_EXTRA_STRICT: '公司名称',
        PHONE: '电话号码',
        PHONE_ADVANCED: '电话号码先进的',
        EMAIL_EXACT: '电子邮件地址',
        EMAIL: '电子邮件',
        DOMAIN_EXACT: '域',
        DOMAIN_FUZZY: '域模糊',
        URL_EXACT: '网址',
        URL_FUZZY: '网址模糊',
        PRODUCT: '产品编号',
        POSTAL_CODE: '邮政编码',
        PERSON_NAME: '模糊',
        FUZZY_COMPANY: '部分模糊浅',
        FUZZY_COMPANY_STRICT: '部分模糊中',
        COMPANY_NAME: '部分模糊重',
        COMPANY: '公司',
        TEXT: '大文本',
        DATE_DISTANCE_DAYS: '日期距离（天）',
        HAS_VALUE: '包含值',
    },
    frequentWords: {
        STREET: '街道',
        COMPANY: '公司',
        COMMON: '常用',
        NAME: '人员姓名',
        EMAIL: '电子邮件',
        CUSTOM1: '自定义 1',
        CUSTOM2: '自定义 2',
    },
    emptyFieldOptions: {
        DEDUP50: '得分 50%',
        DEDUP: '得分 100%',
        SEARCH: '忽略',
    },
    pageNavigation: {
        PREVIOUSPAGE: '上一页',
        NEXTPAGE: '下一页',
    },
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTSVIEW: '重复结果概述',
    DCJOB_OVERALLJOBRESULTS_OVERALLJOBRESULTS: '全部作业结果',
    DCJOB_OVERALLJOBRESULTS_DUPLICATERESULTS: '重复结果',
    DCJOB_OVERALLJOBRESULTS_OPENALLGROUPS: '打开所有组',
    DCJOB_OVERALLJOBRESULTS_CLOSEALLGROUPS: '关闭所有组',
    DCJOB_OVERALLJOBRESULTS_SEARCHUSERS: '搜索用户',
    DCJOB_OVERALLJOBRESULTS_APPLYFILTER: '应用筛选器',
    DCJOB_OVERALLJOBRESULTS_PAIRCOUNT: '重复对计数',
    DCJOB_OVERALLJOBRESULTS_RECORDCOUNT: '记录数',
    DCJOB_OVERALLJOBRESULTS_GROUP: '组',
    DCJOB_OVERALLJOBRESULTS_MINSCORE: '最低分',
    DCJOB_OVERALLJOBRESULTS_MAXSCORE: '最高分',
    DCJOB_OVERALLJOBRESULTS_AVGSCORE: '平均得分',
    DCJOB_OVERALLJOBRESULTS_ONEERROR: '1 个错误',
    DCJOB_OVERALLJOBRESULTS_MERGESELECTEDRECORDS: '合并选中的记录',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTION: '忽略选择项',
    DCJOB_OVERALLJOBRESULTS_DISCARDSELECTIONFOREVER: '永远忽略选择',
    DCJOB_OVERALLJOBRESULTS_DELETINGRECORDSNOTUNDOABLE: '删除记录不可撤销。',
    DCJOB_OVERALLJOBRESULTS_MERGEPAIR: '合并配对',
    DCJOB_OVERALLJOBRESULTS_QUICKMERGEPAIR: '快速合并配对',
    DCJOB_OVERALLJOBRESULTS_CONVERTPAIR: '转换配对',
    DCJOB_OVERALLJOBRESULTS_QUICKCONVERTPAIR: '快速转换配对',
    DCJOB_OVERALLJOBRESULTS_AREYOUSUREYOUWANTTODELETE: '您确定要从 Salesforce 删除 [[insertHTMLWithLink]] 吗？',
    DCJOB_OVERALLJOBRESULTS_DELETERECORD: '删除记录',
    DCJOB_OVERALLJOBRESULTS_RECORD: '记录',
    DCJOB_OVERALLJOBRESULTS_SELECTANOPTION: '选择一个选项...',
    DCJOB_OVERALLJOBRESULTS_SEARCHOPTIONS: '搜索选项...',
    validation: {
        required: '此字段为必需。',
        max: '该字段必须少于 {max} 个字符',
        invalid_cron_format: '无效的 Cron 字符串。请检查格式。',
        invalid_seconds_or_minutes: '无效的 Cron 字符串。请只对秒数和分钟使用数值。',
        invalid_day_of_week_and_day_of_month_combination: '无效的 Cron 字符串。请只指定周或月份的日子。',
    },
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWPAIRVIEW: '切换到对视图',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_SHOWGROUPVIEW: '切换到组视图',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFROMJOB: '从此作业中忽略此组',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPINJOB: '放弃此作业中的组',
    DCJOB_OVERALLJOBRESULTS_ACTIONS_DISCARDGROUPFOREVER: '永远放弃群组',
    DCJOB_OVERALLJOBRESULTS_FILTER_JOBTYPE: '作业类型',
    DCJOB_OVERALLJOBRESULTS_FILTER_OWNER: '{objectName} 所有人',
    DCJOB_OVERALLJOBRESULTS_FILTER_RECORDTYPE: '{objectName} 记录类型',
    DCJOB_OVERALLJOBRESULTS_FILTER_PREDEFINED: '{objectName} 的预设筛选器',
    DCJOB_OVERALLJOBRESULTS_FILTER_FIELD: '{objectName} {fieldName}',
};
